### ISSUE TITLE
Pipe on a newline ?

### ISSUE THREAD

**Issue by vindarel** [evhub/coconut#101]
Hi !

In Coconut, the following throws a compilation error:

```
"hello"
|> print
```

Writing pipes on newlines is possible in Mochi, Elixir, Livescript… and is really handy, not to say necessary to decompose long processings.
Would that be possible in Coconut, what's your take on it ?

Thanks !

**Comment by evhub** [comment]
@vindarel Just surround your expression in parentheses and it should work fine! Coconut follows the Python indentation rule that any new lines inside of parentheses are ignored. Instead of what you have above, just do:
```
("hello"
|> print)
```

**Comment by vindarel** [comment]
Quite very nice, thanks !
