### ISSUE TITLE
Add to the list of available Jupyter Kernels.

### ISSUE THREAD

**Issue by Carreau** [evhub/coconut#107]
Hi there, I invite you to add your kernel on the list of [available kernels for Jupyter](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages). 

You also welcomed to make an announce that this exists on the Jupyter and or IPython ML. 

Sidenote, this look similar to [mochi](https://github.com/i2y/mochi) in case you are not aware of it. 

Thanks !

**Comment by evhub** [comment]
Thanks! As soon as I push https://github.com/evhub/coconut/issues/97 to master (which is preventing the kernel from always working properly right now), I will go ahead and do that.

And I am familiar with mochi, although I think Coconut has a lot of advantages over Mochi, namely that Coconut syntax is a strict superset of Python 3 and Coconut supports all major versions of Python.

**Comment by Carreau** [comment]
Great !


Sidenote, I see that you have lowercase class names:

https://github.com/evhub/coconut/blob/master/coconut/icoconut/root.py

IPython via traitlets make assumptions that class names do start with an upper letter and that attribute start with a lower one. 

You might get into trouble with weird bugs if you don't follow that.

**Comment by evhub** [comment]
Fixed—renamed the main class in `icoconut.root` in develop.

**Comment by Carreau** [comment]
Ah, great ! I missed the `develop` branch !

**Comment by evhub** [comment]
Done—Coconut has been added to the list of kernels and posted to the mailing list.
