### ISSUE TITLE
self referencing iterator causes Segmentation fault

### ISSUE THREAD

**Issue by bj0** [evhub/coconut#108]
I tried creating an infinite sequence like I would using streams in Scala:

    seq = (1, 2) :: seq

    seq$[:10] |> print
    // <itertools.islice object at 0x7f2e10faa908>
    seq$[:10] |> list |> print
    Segmentation fault (core dumped)

I was trying to create a fibonacci sequence like:

    fib = (1, 2) :: ((fib, fib$[1:]) |*> map$(+))

I can do it by making fib() a function, but that exponentially eats up memory

**Comment by evhub** [comment]
That segmentation fault is a Python issue I've had to deal with a lot. I'll try to work on finding a way to compile
```
seq = (1, 2) :: seq
```
so that it works, but for now, I'd suggest
```
def seq() = (1, 2) :: seq()
```
as a replacement, although you're right about the function calls eating up memory. Not a perfect solution. I'm going to keep this open and investigate ways to fix this.

**Comment by bj0** [comment]
I found it trying to do Project Euler problem #2, I had to kill it once memory hit 10gigs.

**Comment by evhub** [comment]
If you use
```
def seq() = (1, 2) :: seq()
```
then as long as you access it with something like
```
seq()$[:10]
```
the memory usage shouldn't be anywhere near that large.

**Comment by bj0** [comment]
well what I tried was:

    # memory blows up
    def fib() = (1, 2) :: ((fib(), fib()$[1:]) |*> map$(+))

    # python function works better
    def fib():
        x,y = 0,1
        while True:
            yield x
            x,y = y, x+y

    fib() |> takewhile$((i) -> i < 4000000 ) |> filter$((i) -> i % 2 == 0 ) |> sum

**Comment by evhub** [comment]
When I do
```
>>> def fib() = (1, 2) :: ((fib(), fib()$[1:]) |*> map$(+))
>>> fib() |> takewhile$((i) -> i < 400 ) |> filter$((i) -> i % 2 == 0 ) |> sum
188
```
it works, so yeah, that's definitely a memory error. Every time `fib` is called Python creates a closure that takes up memory. That's a hard one to fix, but I'll see what I can do.

**Comment by bj0** [comment]
If it helps, I was able to get the correct behavior.  Coconut compiles:

    seq = (1, 2) :: seq

into something like

    seq = chain.from_iterable(s() for s in (lambda: (1, 2), lamda: seq))

It segfaults on the 3rd `next(seq)` call.  Using a pure-python version of `from_iterable`, you get an Exception about using the same iterator twice.  I can work around it by using `tee`:

    seq, b = tee(chain.from_iterable(s() for s in (lambda: (1, 2), lambda: b)))

Similarly the fibonacci one can be made with:

    fib, b, c = tee(chain.from_iterable(s() for s in (lambda:(1,2), lambda: map(operator.add, b, islice(c,1,None)))), 3)

    fib |> takewhile$((i) -> i < 4000000 ) |> filter$((i)-> i%2 == 0) |> sum
    # instantly prints 4613732


So maybe auto-detect self referenced iterators and split them with `tee`? Not sure how complicated this is.

*in a more coconut-y syntax:*

    fib, b, c = tee((1,2) :: ((b, c$[1:]) |*> map$(+)),3)

**Comment by evhub** [comment]
@bj0 That's a good observation! I'll see if I can use `tee` to work around this problem.

**Comment by evhub** [comment]
Alright, using `tee`, I think I can do this with a decorator, so that
```
@recursive_iterator
def fib() = (1, 2) :: ((fib(), fib()$[1:]) |*> map$(+))
```
will work without filling up memory with calls to `fib`.

**Comment by evhub** [comment]
Fixed! `@recursive_iterator` is working beautifully in develop right now and will be included in the next release.

**Comment by bj0** [comment]
Just tested it in the development branch, works great!

**Comment by evhub** [comment]
@bj0 Great! Good to hear it.
