### ISSUE TITLE
Installation issue on Ubuntu 16.04.

### ISSUE THREAD

**Issue by danipozodg** [evhub/coconut#109]
After running `python -m pip install coconut`, and getting a successful installation message, running `coconut` doesn't work, the command is not found.

Is this an issue or am I just doing something wrong?

**Comment by evhub** [comment]
Strange. `pip` should take care of adding the script to your path. Try `python -m coconut`?

**Comment by danipozodg** [comment]
Yes, `python -m coconut` does work.

**Comment by evhub** [comment]
I think it must be an issue with your `pip` installation. I would recommend just adding
```
alias coconut='python -m coconut'
```
to your `~/.zshrc` file.

**Comment by vindarel** [comment]
Speaking about `zsh`, with it we usually must `rehash` to get new commands available (or start a new shell).
