### ISSUE TITLE
Add MyPy support

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#121]
Should add a `--mypy` flag that works similarly to the `--autopep8` flag in that it runs MyPy as an extra pass on the compiled Python.

**Comment by Boscillator** [comment]
OK so their is a problem with this,
MyPy throws an error and crashes when it tries to parse a class that contains import statements at the top level, like the _coconut class in compiled coconut.

```
class _coconut:
    import collections, functools, imp, itertools, operator, types, copy   #This line causes the error
    if _coconut_sys.version_info < (3, 3):
        abc = collections
    else:
        import collections.abc as abc
```

I will submit an issue to mypy.

**Comment by evhub** [comment]
@Boscillator Imports inside of a class are perfectly valid Python, so this definitely seems like a MyPy error.

**Comment by evhub** [comment]
This is blocked and waiting on <https://github.com/python/mypy/issues/1839>.

**Comment by Boscillator** [comment]
I would remove this from the milestone, I don't see `mypy` getting it's stuff together anytime soon.

**Comment by cabalamat** [comment]
Instead of Coconut using MyPy's syntax for types, would it not be better to use a more |Haskell-like syntax, which I think would look clearer. For example, this in MyPy:

    A = typevar('A')
    B = typevar('B')
    def myMap(f: Callable[[A], B], xs: List[A]) -> List[B]:

Would be this in Haskell:

    myMap :: (a->b) -> [a] -> [b]

We could extend the [...] syntax in a natural way for dicts and set, e.g. `{k:v}` would mean a dict where the keys are ks and the values are vs, and `{v}` would mean a set of vs.

**Comment by Boscillator** [comment]
I'm not apposed to better function typing syntax, I'm just not sure that this is the write way to do it. The Haskell syntax look rather similar to lazy functions and lambdas, so I'm not sure it's the best idea.

**Comment by evhub** [comment]
@cabalamat @Boscillator I like the idea of providing an improved syntax for MyPy type definitions, although `myMap :: (a->b) -> [a] -> [b]` wouldn't work, since `::` is valid coconut (the iterator chain operator). But I think something Haskell-y along those lines would be nice, though.

**Comment by Boscillator** [comment]
Could we just to some kind of automatic `typevar` creation?
So `def myMap(f: (a->b), xs: [a]) -> (b): pass`

**Comment by evhub** [comment]
@Boscillator Yeah, that's definitely a possibility. I'm still not really sure yet what the best way to go about this is.

**Comment by Boscillator** [comment]
To help differentiate between generic types and real types we could have generics prefixed like in OCaml.
For example `def myMap(f: ($a->$b), xs: [$a]) -> $b: pass`

**Comment by evhub** [comment]
@Boscillator I worry about overusing the `$` symbol, since Coconut already gives it two meanings (partial application and iterator slicing).

**Comment by Boscillator** [comment]
I agree, with you that `$` may be a bad idea, but we could pick some other symbol. Maybe `^` or `@`

**Comment by cabalamat** [comment]
Haskell gets away with using lower-case identifiers because types always start with upper case. But Coconut can't adopt that solution because Python has built in types that stsart with lower case, such as `int`. Maybe just allow a single character for generic types, and require that an actual type cannot be a single lower-case character (which would look odd anyway)? 

Alternately, OCaml uses ` which would make Boscillator's example look like this:

    def myMap(f: (`a->`b), xs: [`a]) -> [`b]: pass

**Comment by Boscillator** [comment]
I would have suggested the OCaml approach, but I couldn't figure out how to type it in GitHub, also it might look somewhat like infix notation.

**Comment by Boscillator** [comment]
The blocking bug just cleared up in mypy. However, since we are getting rid of autopip8 support, I would imagine that we no longer want mypy support. If this is true, can we rename the issue something like "Add better mypy syntax"

**Comment by evhub** [comment]
@Boscillator I do still want MyPy support, actually, since I think there's a valid use case there (since static typing on the compiled code will still apply to the source code), unlike for autopep8 (which is really only useful when you're running it on the source code).

**Comment by darkf** [comment]
@Boscillator, @evhub Was the issue with MyPy fixed in mypy master (the issue blocking this was closed/fixed)?

**Comment by evhub** [comment]
@darkf It has been fixed on MyPy master, but has not made it into a MyPy release yet.

**Comment by evhub** [comment]
MyPy v0.4.5 fixes the imports inside of classes error! This is now unblocked.

**Comment by evhub** [comment]
@Boscillator @cabalamat @darkf @mikeiavelli @sebastiankwiatkowski @achauve `coconut-develop` now has working MyPy integration! These are the changes that have been made so far in `coconut-develop` (which you can get just by running `pip install coconut-develop`):
- added a `--mypy` argument which runs MyPy on the compiled code
- made Python 3 type annotations compile to MyPy-compatible type comments for cross-version compatibility

These are additional things I'm planning to do to make MyPy integration even better:
- resolve #194, which will add a nice syntax for adding type annotations to variable definitions
- refactor the header to remove as many MyPy errors as possible

If you test out the MyPy integration and find anything else, just leave a comment here! This is still very much in development.

**Comment by evhub** [comment]
The additional things from my previous comment are now finished! Next (potential) step is attempting to create a Haskell-like type annotation syntax that's nicer than MyPy's default.

**Comment by evhub** [comment]
I'm closing this and marking it as resolved now that `--mypy` has been implemented. Potentially creating a new, enhanced type definition syntax has been moved to #200.
