### ISSUE TITLE
Allow to invoke `addpattern` (and `prepattern`) without function name

### ISSUE THREAD

**Issue by moigagoo** [evhub/coconut#125]
Currently, `addpattern` is used so:
```
def f(0) = 1

@addpattern(f)
def f(n) = n * f(n-1)
```
Notice how `f` is duplicated as an `addpattern` argument and after `def`. Also, this notation is ambiguous: does that mean "add pattern below to previously defined f" or "add previously defined pattern f to the function defined below".

Would it be possible to infer the function name automatically?
```
def f(0) = 1

@addpattern
def f(n) = n * f(n-1)
```
This way this is unambiguous—"add pattern defined below to the function of the same name defined previously."

I do understand that theoretically it's possible to have different names for the first and the second function, but this is never observed in the docs and the purpose is unclear—the whole idea of `addpattern` is to be able to extend *the same* function with multiple patterns.

**Comment by evhub** [comment]
There's no way to make an argument-less version except through compilation tricks which is possible but I'd prefer not to. What I could do is create a zero-argument version that tries to find the old function by checking `globals()[new_func.__name__]`, which would work, but only when the function was defined at the top level. Thus, you'd be able to do
```
def f(0) = 1

@addpattern()
def f(n) = n * f(n-1)
```
but not
```
def get_f():

    def f(0) = 1

    @addpattern()
    def f(n) = n * f(n-1)
```

**Comment by Boscillator** [comment]
I like the 0 argument version working with `globals()`, but the named version should be keep for the second use case.

**Comment by moigagoo** [comment]
Thanks for the clarification. I think we should keep the current version and  *not* add the zero-argument one. It's unreliable and magic, whereas argument version is solid although a bit too explicit.

**Comment by Boscillator** [comment]
I just implemented a zero-argument version and their is quite a bit of magic in it. It may not be such a good idea to include it, but I do think would be useful.
If you do want me to continue development on it, I would like to know what kind of exception it should throw if you `addpatern`/`prepattern` a function that doesn't exist.

**Comment by evhub** [comment]
@moigagoo I considered adding a zero-argument version when I was creating it, but rejected it for exactly those reasons. The other remaining possibility is to try a compilation trick, but then the problem becomes that
```
@addpattern
def ...
```
works, but
```
my_addpattern = addpattern
@my_addpattern
def ...
```
does not, which is also unreliable and magic, although maybe in a better way, but I'm not sure.

@Boscillator Thanks for the PR, although I think I'll probably be closing it with a won't fix, for the reasons above.

**Comment by Boscillator** [comment]
This is probably a bad idea, but another solution would be to make all pattern matching functions do something like this compile side. Then you would not have to worry about `my_addpattern = addpattern` because their would be no `addpattern`.

**Comment by evhub** [comment]
@moigagoo @Boscillator Another option is to support `locals()` as an argument to `addpattern`, so then you could do
```
def f(0) = 1

@addpattern(locals())
def f(n) = n * f(n-1)
```
which should work regardless of scoping, solving the major problem of the zero-argument version. The only disadvantage is that `@addpattern(locals())` is somewhat clunky, arguably just as clunky as if not more so than `@addpattern(f)`.

**Comment by Boscillator** [comment]
I think that would be mostly confusing for people learning `@addpattern` for the first time, and it is rather clunky.

**Comment by evhub** [comment]
@Boscillator Yeah, I think I agree. Probably going to close this whole issue with a won't fix, since I can't seem to think of any good way to do this.
