### ISSUE TITLE
add an equivalent to scala's for-comprehension syntax

### ISSUE THREAD

**Issue by bj0** [evhub/coconut#127]
I was trying to figure out how I could re-use the result of a function call in a filter lambda (since you can't make assignment statements).  The only way I could figure out is pretty clunky:

    range(N) |> filter$((i) -> i == fun(fun(i)) and i != fun(i) )       // fun(i) calculated twice

    range(N) |> map$((i) -> (i, fun(i))) |> filter$((t)-> t[0] == fun(t[1]) and t[0] != t[1]) |> map$((t)-> t[0])   // only calculated once, but super clunky

In Scala, this is an easy for [comprehension][1]:

    for( i <- 0 to N; k = fun(i); if i == fun(k) and k != i ) yield i     // or { lambda funciton }

Not sure how difficult implementing this feature would be and I'm guessing the syntax would have to change to fit with coconut's pipe syntax, but it would be pretty useful.

   [1]: http://docs.scala-lang.org/tutorials/FAQ/yield.html

**Comment by evhub** [comment]
@bj0 I believe resolving #90 should resolve this as well. Once #90 is implemented, you'll be able to do
```
range(N) |> filter$((i) -> k = fun(i); i == fun(k) and i != k)
```
which is simple, straightforward, and only calculates `fun(i)` once.

**Comment by evhub** [comment]
I have marked #90 as high priority and it is slated for development for the next release, so that both that and this can be resolved.

**Comment by bj0** [comment]
Ahh yea, that's a good one and solves this specific problem.  I think for comprehensions are useful in many other cases too (like nested maps), so it might be worth adding them in as a low-priority future feature request?

**Comment by evhub** [comment]
@bj0 I'm not super familiar with Scala--can you give some examples of things Coconut can't do but Scala's for comprehension can? Maybe I don't understand what you mean by nested maps, but you can certainly do
```
list_of_lists |> map$((inner_list) ->
    inner_list |> map$(inner_list_transform)
)
```
if that's what you mean.

**Comment by bj0** [comment]
Right, some examples are in the link from my post: http://docs.scala-lang.org/tutorials/FAQ/yield.html

It essentially gets translated into nested maps (and filter) like that, it's just much more concise.  More syntactic sugar now that #90 is done, but it does clean up the syntax some.  Especially for someone like me who learned FP on scala.

**Comment by evhub** [comment]
@bj0 Alright, makes sense. I'll unmark this as duplicate and look into how I might implement this.

**Comment by evhub** [comment]
@bj0 I believe Python's list (or iterator/set/dict) comprehension syntax can already do everything that Scala's for comprehension syntax can. To show this, translating the example in the link from Scala
```
for{
  sl <- l
  el <- sl
  if el > 0
} yield el.toString.length
```
to Python
```
(
  len(str(el))
  for l in sl
  for el in sl
  if el > 0
)
``
which is also valid Coconut.

**Comment by bj0** [comment]
Ah yea, I had forgot about nested comprehension.  I must have been too focused on the case where you can assign a local variable:

        for(x <- c; y = f(x)) yield { multiple uses of y }

I'm not sure how this case would translate to python comprehensions.

**Comment by evhub** [comment]
@bj0 Hard to do in Python, but in Coconut (using the statement lambda in develop right now), you could do that as:
```
((def -> y = f(x); multiple uses of y)() for x in c)
```
