### ISSUE TITLE
Support early termination for parallel and concurrent map

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#128]
Currently, if the iterator doesn't finish, then the executor never gets closed.

**Comment by evhub** [comment]
@moigagoo I still want to fix this, since it should never be easy to leave processes or threads unclosed, but I think that not using the full iterator from a parallel or concurrent map pretty much always indicates that you shouldn't be using a parallel or concurrent map. This is because both will submit every job at the beginning, thus you're always computing the whole iterator, so if you only want part of the iterator, using a parallel or concurrent map will ensure you're always doing more work than you have to.

**Comment by moigagoo** [comment]
> I think that not using the full iterator from a parallel or concurrent map pretty much always indicates that you shouldn't be using a parallel or concurrent map.

Not necessarily. Parallel and concurrent maps are means of improving performance with minimal code changes. Ideally, you should be able to replace `map` with `parallel_map` without having to worry about breaking the code. The samples from #129 show one case where replacing `map` with `parallel_map` would be much desired.

**Comment by evhub** [comment]
@moigagoo Agreed that it shouldn't break the code. But if you're only using part of the iterator, then your performance gains will be a lot less, since you'll still have to compute the whole iterator. Regardless, this has now been fixed in develop so that parallel and concurrent map return tuples.
