### ISSUE TITLE
Make creating data with no methods easier

### ISSUE THREAD

**Issue by Boscillator** [evhub/coconut#134]
Right now if you want to create a data type with no methods you have to do
```
data Vector(x,y):
    pass
```
It would be great if you could do something like
```
data Vector(x,y)
```

I know you can use a named tuple, but the `data` construct makes code more legible and if you want to add methods later it's easier.

**Comment by evhub** [comment]
@Boscillator What's wrong with:
```
data Vector(x, y): pass
```

**Comment by Boscillator** [comment]
It's wordier. It's not too bad, but I think it would be nice to not require it.

**Comment by evhub** [comment]
@Boscillator Should this feature generalize to classes as well? So you could do:
```
class A(B)
```

**Comment by Boscillator** [comment]
Probably, if it were in one place, It should be everywhere it makes sense.

**Comment by evhub** [comment]
Live in develop.
