### ISSUE TITLE
Support keyword-only arguments

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#135]
Currently, use of keyword-only argument syntax results in a `CoconutParseError`, when it should result in a `CoconutTargetError`.

**Comment by evhub** [comment]
Now results in a `SyntaxError` on Python 2, and works fine on Python 3.

**Comment by chuckwondo** [comment]
@evhub Would you mind providing an example or two?

**Comment by evhub** [comment]
@chuckwondo Python 3 supports keyword-only syntax that looks like:
```
def func(pos_arg_1, pos_arg_2, *, kwd_only_arg_1, kwd_only_arg2):
    pass
```
Previously, Coconut would throw a `CoconutParseError` when it encountered the lone `*` in the function definition. Now, it happily passes it right through into the compiled Python. I think that behavior is preferable, but it's still not ideal. Ideally, Coconut should raise a `CoconutTargetError` when it encounters the lone `*`, and ask the user to pass `--target 3` if they want to dismiss the error. That way, the user knows that the compiled code will break on Python 2.

**Comment by chuckwondo** [comment]
Ah, makes sense. Thanks for the clarification.
