### ISSUE TITLE
Split command and compiler into multiple files and remove * imports

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#138]
These are relics of old bad coding habits of mine that should be cleaned up and removed. It would be nice to use an automated tool for at least some of this.

**Comment by chuckwondo** [comment]
@evhub Would you provide some specific references to places in your code that you're thinking about, with perhaps a bit more detail on your thoughts here?

**Comment by evhub** [comment]
@chuckwondo `command.py` and `compiler.py` are the two real big offenders here. `compiler.py` because it's way too long (3000+ LOC) and needs to be split into multiple files, and `command.py` because it uses `from .compiler import *` (it should use `from .root import *` and `from .compiler import <list>` or `from . import compiler` instead) which makes it very difficult to read, since it's hard to tell what's defined in `command` and what's defined in `compiler`. Of those two problems, I think fixing the imports in `command.py` is the easier one and shouldn't be too bad. Splitting up `compiler.py` is actually much harder because most of the stuff there is all in one big class (`processor`), although separating out just the utilities and handlers to start with will still be a big step. I'm planning on working on both of those pretty soon.

**Comment by evhub** [comment]
Merged into develop from #145.
