### ISSUE TITLE
Support inline nonlocal and global assignments

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#140]
In [PEP 3104](https://www.python.org/dev/peps/pep-3104/), it was proposed to add
```
nonlocal a, b = x, y
global a, b = x, y
```
syntax, but it was never done. Coconut should compile this to
```
nonlocal a, b; a, b = x, y
global a, b; a, b = x, y
```

**Comment by chuckwondo** [comment]
@evhub I'm curious as to why you have marked this as high priority. (If you'd like some help with Coconut, I'd like to contribute, so I've started looking through your current list of issues to see where I may be able to help, which is why I'm wondering about priorities.)

**Comment by evhub** [comment]
@chuckwondo "high priority" basically just means I want to put this in the next release (I should probably rename the label or use milestones or something). The reason I want this in the next release is just because I figured this would be a nice feature to have--it's useful, easy to implement, and I can't think of any real downsides to doing so.

**Comment by evhub** [comment]
This is now live in develop.
