### ISSUE TITLE
In compiler output, include relative file paths of input and output files

### ISSUE THREAD

**Issue by chuckwondo** [evhub/coconut#160]
For projects with code in a hierarchy, it would be helpful for the compiler to print the full relative paths of both the Coconut files and the Python files (relative to the directory from which the compiler was invoked), particularly when there are multiple files with the same names, such as `__init__.coco`.

Even when all files are uniquely named, when there is a hierarchy, seeing only the file name can make it difficult to quickly find a file that causes compilation failure.

**Comment by evhub** [comment]
Live in develop.

**Comment by chuckwondo** [comment]
Perfect! Looks good. Thanks!
