### ISSUE TITLE
coconut kernel cannot parse ipython %magic commands

### ISSUE THREAD

**Issue by ankostis** [evhub/coconut#168]
(excellent project...thanks)
After installing _coconut_ kernel with `coconut --jupyter`, I managed to run coconut code.
But it fails parsing ipython magics:

```
CoconutParseError: parsing failed (line 2)
    %matplotlib notebook
```

![image](https://cloud.githubusercontent.com/assets/501585/18362762/647bbcee-7607-11e6-8c29-86783c38cbd3.png)

**Comment by evhub** [comment]
@ankostis Thanks for the issue! You are correct that currently the Coconut kernel does not support IPython magics. That's definitely a feature I'd like to add, and I'll keep this issue open for doing so. Until then, if you want to use IPython magics you'll have to use the IPython kernel as the base and run Coconut code using the `%coconut` and `%%coconut` magics, like so:
```
%load_ext coconut
%coconut "hello, world" |> print

# in a new cell
%%coconut --strict
def hello(): "hello" |> print
hello()
```

**Comment by fredcallaway** [comment]
Another issue that is likely related: `IPython.display.display` which is used to render nice-looking tables does not function correctly with a Coconut shell.

**Comment by evhub** [comment]
@ankostis @fredcallaway This should be fixed in the latest `coconut-develop`--just `pip install coconut-develop` to get the new behaviour!

**Comment by ankostis** [comment]
Thank you!

A new problem now is that *coconut* depends on an older version of *ipython*. `v4.x.x` instead of the recent `v5.x.x`, and that makes it unpossible to use it outside a virtualenv.

**Comment by evhub** [comment]
@ankostis Yeah, I know. I can't update Coconut to the `v5` branch until my Jupyter pull request https://github.com/jupyter/jupyter_console/pull/102 is released. It's been merged, but hasn't made it into a `v5` release yet. Once it does, I'll update Coconut's dependency to that version.
