### ISSUE TITLE
Ctrl-C fails to terminate compiler on Windows using more than one job

### ISSUE THREAD

**Issue by darkf** [evhub/coconut#174]
`multiprocessing` can be pretty fickle on Windows. Ideally Coconut would gracefully shut down each subprocess (when it receives `KeyboardInterrupt`) and let the executor pool die out naturally, and then exit.

**Comment by evhub** [comment]
@darkf My machine is Windows and I haven't seen the error you're describing. What Python version are you running?

**Comment by darkf** [comment]
@evhub Python 3.5. Compile any Coconut source with any number of jobs greater than 0, then interrupt it in the middle of the compilation step.

**Comment by evhub** [comment]
@darkf Should be fixed now.
