### ISSUE TITLE
Support Tail Recursion Elimination

### ISSUE THREAD

**Issue by darkf** [evhub/coconut#175]
Now that #115 is down, which adds tail call optimization, there is the specific form of tail recursion, e.g.:

	def factorial(n, acc=1):
	    case n:
	        match 0: return acc
	        match _ is int if n > 0: return factorial(n-1, acc*n)

Where the tail call is recursive. In Coconut currently this is just trampolined using the same mechanism as for TCO, but the overhead of trampolining is not desirable. Tail recursion should be just as efficient as iteration.

As I originally noted in #115, this may be rewritten to something of the form

	def factorial(n, acc=1):
		while True:
		    case n:
		        match 0: return acc # return as per the base case
		        match _ is int if n > 0:
		        	# re-bind arguments
		        	n = n-1
		        	acc = acc*n
		        	continue # perform the next iteration
		    return None # explicit return to stop spinning in the loop

Of course, there might be other ways to write this, and special care might need to be taken for exception handling, but the performance gain is worth it.

**Comment by evhub** [comment]
@darkf Putting this on the v1.2.1 milestone, hopefully it'll be included in the next release.

**Comment by darkf** [comment]
@evhub Sound good to me!

**Comment by evhub** [comment]
@darkf Tail recursion elimination is now supported on the develop branch! To test it out, just `pip install coconut-develop`.
