### ISSUE TITLE
Add linux shebang support for runnable Coconut scripts

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#178]
Should be able to add
```
#!/usr/bin/env coconut-run
```
to make a Coconut file a runnable script file.

**Comment by malkarouri** [comment]
As it stands, coconut-run creates a .py file as a byproduct of running the script. Is this required functionality?
Looks to me like coconut-run should compile in memory. No?

**Comment by evhub** [comment]
@malkarouri If `coconut-run` compiled in memory, it would mean all Coconut scripts were incredibly slow, since they would have to be compiled every single time before they were run. By creating a `.py` file, next time the script needs to be compiled Coconut will detect that `.py` file and just run that, which means the script is only slowed down the first time it's run, not every time.

**Comment by malkarouri** [comment]
Makes sense. Thanks for the response.
