### ISSUE TITLE
Segfault when using --run with --jobs sys

### ISSUE THREAD

**Issue by x10an14** [evhub/coconut#186]
Hiya! Working on dockerizing Coconut in PR #183, and may have come across a segfault bug?

In [this commit](https://github.com/x10an14/coconut/commit/8231b1ed12d83c8f165d2f11c144cc8c80ff3c25), I've managed to minimize the developer docker container image from 600+MB to 389.2MB, but there's ONE test which fails.

[Here's](https://gist.github.com/x10an14/294e2e788ef361797698f94ecb62900b) a gist showing what happens when I tried to briefly look into it.
(There's two runs of the tests in that gist, first run fails 6 tests due to tests having hardcoded use of the `python` binary, which was fixed by symlinking the `python3` binary on line 2056).

@evhub Would you have a chance/capacity to help me look into whether this is Coconut's fault, or the minimized alpine base container image's fault?

**Comment by evhub** [comment]
@x10an14 Looks like the command that's failing is
```
coconut tests/src/extras.coco tests/dest --run --jobs sys
```
What happens when you run that locally inside of the docker container?

**Comment by x10an14** [comment]
All the commands from the gist were executed inside the Docker container =)

If you ctrl+f after the command you quote in the gist file, the 3rd match
from the top is my attempt at running the command myself inside the Docker
container.

--
Med vennlig hilsen/Kind Regards,
Christian Chavez,
Tlf./Phone: +47 922 22 603

**Comment by evhub** [comment]
@x10an14 Ah, yeah, I see it now. Huh. That definitely shouldn't happen, considering Python really isn't supposed to segfault--although there are some cases in which it will happen. The strange thing, though, is that it's only happening when that command is run inside of docker. Quite the mystery. I would try varying the command or commenting out parts of the file to figure out what's causing the error. My first guess would be multiprocessing, so I'd try removing `--jobs sys`, otherwise it's probably one of the tests in the file? But it's quite the bug, I'm not sure what's causing it.

**Comment by x10an14** [comment]
I'm @ a Docker training course, and attempted quickly to run without `--jobs sys`.

[It seems to have run correctly](https://gist.github.com/x10an14/294e2e788ef361797698f94ecb62900b#file-attempt_nr2-txt), but there might be an issue due to me doing this on winblows. (It modifies access bits for files copied into the docker container).

Does this help you narrow down where the error is coming from? I'm not familiar with this command. I can try to get more familiar with it in the weekend.

**Comment by evhub** [comment]
@x10an14 Cool! And if the error doesn't happen when you remove `--jobs sys`, then it's not something I'm super concerned about. `--jobs sys` tells Coconut to perform multiprocessing to speed up compiling multiple files, but Python multiprocessing is really buggy and tends to cause weird stuff like that to happen. If that's the only thing that's failing I wouldn't worry about it.

**Comment by x10an14** [comment]
'Aight! How do I go about modifying this correctly to run without segfault on Docker, with changes implying the least maintenance?

It's currently the command `make test` that invokes the `--jobs sys`.

Do you have any suggestion for how to avoid that invocation, with the least required maintenance (as opposed to just utilizing the makefile rules?).

**Comment by evhub** [comment]
@x10an14 It's only a temporary solution, but for right now just change `["--run"]` to `["--run", "--jobs", "0"]` in <https://github.com/evhub/coconut/blob/develop/tests/main_test.py#L183>.
