### ISSUE TITLE
Watcher compiling same file twice

### ISSUE THREAD

**Issue by Nexus6** [evhub/coconut#189]
I'm using coconut -w while editing my .coco files in vim.  Most of the time (but not always I think) the file is compiled twice.  For instance, when I'm editing foo.coco and save it, I see
**Coconut: Compiling         foo.coco ...
Coconut: Compiled to       foo.py .
Coconut: Compiling         foo.coco ...
Coconut: Compiled to       foo.py .**

If I introduce a compile error, for example putting '/1' on a line, I see
**Coconut: Compiling         foo.coco ...
CoconutParseError: parsing failed (line 32)
  /1
Coconut: Compiling         foo.coco ...
CoconutParseError: parsing failed (line 32)
  /1**

Version/platform info:
$ coconut -v
Version 1.2.0 [Colonel] running on Python 3.5.2 (default, Sep 10 2016,
08:21:44) [GCC 5.4.0 20160609]

**Comment by evhub** [comment]
@Nexus6 Definitely seems like a bug. I'll look into it and figure out what's going on.

**Comment by Nexus6** [comment]
I forgot to mention, here's my invocation of coconut where the problem is manifest:
coconut -w -t35 -f -s .

**Comment by evhub** [comment]
@Nexus6 Fixed in `coconut-develop`! Run `pip install coconut-develop` to get the new behaviour.

**Comment by Nexus6** [comment]
Got it.  Tested and the fix is working.  Thanks!

**Comment by evhub** [comment]
Reopening--it looks like this is now happening again.

**Comment by evhub** [comment]
This should now been fixed again.

**Comment by Nexus6** [comment]
After updating coconut-develop and friends I can't reproduce the problem. If 1.2.2-post_dev17 this the right version to be testing with then I guess the bug is fixed.

**Comment by evhub** [comment]
@Nexus6 Yep, that's right--good to hear it's fixed.
