### ISSUE TITLE
Strip type hints when targeting Python 2.x

### ISSUE THREAD

**Issue by Nexus6** [evhub/coconut#191]
The title says it all.  Right now, with a .coco source containing type hints, an attempt to target Python 2.x when compiling fails because of the hints.  It would be a nice feature of Coconut to have Python-style type hints _as part of the language itself._  Hints could be stripped all of the time, or could be propagated to the target Python source (or not) depending on the target interpreter version.

This behavior would be especially useful for library authors who find type hinting valuable but who want to support both 2.x and 3.x Python users.  I have one library (eventually to be open-sourced) from which I've had to strip type hints because of the need for 2.x compatibility.  If Coconut had type-hint-stripping behavior then I could port my code (with hints) to Coconut and have both source-level hinting and Python version independence at the same time.

**Comment by evhub** [comment]
@Nexus6 Done! Just `pip install coconut-develop` to get the new behaviour. In the long run, I think I'd like to compile type hints to MyPy comments in Python 2 (once #121 is resolved), but until then I agree that stripping is definitely better than throwing an error.

**Comment by Nexus6** [comment]
NIce! I think that apart from the intrinsic language features of Coconut, no-hassle cross-compilation across Python versions might have a lot of appeal to existing Python developers.  I'll install coconut-develop and give it a try.  Thanks for the quick response to this issue.
