### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by Nexus6** [evhub/coconut#196]
Some code that used to compile in the last dev version now leads the compiler to crash in a spectacular manner.  My code has a mixture of normal type hints and the MyPy style #type: annotations, but I'm not invoking the compiler with the --mypy argument.

Version 1.2.0-post_dev13 [Colonel] running on Python 3.5.2
Invoked with "coconut -t35 -w -s -f ."
```
Coconut: Compiling         workflows/deciders/basedecider.coco ...
Traceback (most recent call last):
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/coconut/logging.py", line 224, in wrapped_handler
    return _trim_arity(handler)(s, l, t)
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/coconut/compiler/compiler.py", line 1262, in decoratable_normal_funcdef_stmt_handle
    func_name, func_args, func_params = parse(self.split_func_name_args_params, def_stmt)
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/coconut/compiler/util.py", line 188, in parse
    return grammar.parseWithTabs().parseString(text)
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1617, in parseString
    raise exc
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 3359, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 3681, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1514, in _parseCache
    value = self._parseNoCache(instring, loc, doActions, callPreParse)
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/eric/proj/Taps/lib/python3.5/site-packages/pyparsing.py", line 2386, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected ")" (at char 60), (line:1, col:61)
CoconutInternalException: error calling handler decoratable_normal_funcdef_stmt_handle with tokens: (['def __init__(self, *args: List[Any], **kwargs: Dict[Any, Any],)-> None:\n\u204bself.identity, self.domain, self.version, task_name = args#3\u23f9\nself.task_list = {\u25b64\u23f9: task_name}#5\u23f9\nsuper().__init__(group=None, target=None, name=self.identity)\n\nimport boto3\nfrom botocore.client import Config\n\ncfg = Config(connect_timeout=50, read_timeout=70)#6\u23f9\nself.swf_client = boto3.client(\u25b67\u23f9, region_name=config.AWS_REGION, config=cfg)#8\u23f9\n\n\xb6'], {})
Coconut: Exiting due to CoconutInternalException.
```
My offending .coco, as far as I can tell, a bit of AWS SWF-related code, is
```
    def __init__(self, *args:List[Any], **kwargs:Dict[Any,Any]) -> None:
        self.identity, self.domain, self.version, task_name = args          #type: str, str, str, str
        self.task_list = {'name' : task_name}                               #type: Dict[str,str]
        super().__init__(group=None, target=None, name=self.identity)
        import boto3
        from botocore.client import Config
        cfg = Config(connect_timeout=50, read_timeout=70)   #type: Config
        self.swf_client = boto3.client('swf', region_name=config.AWS_REGION, config=cfg) #type: Any
```
In this case my #type: comments are gratuitous, for my own reference, I'm not even sure that MyPy would do anything with them but again I'm not using --mypy .

**Comment by evhub** [comment]
@Nexus6 Yeah, sorry--definitely a bug! I'll try to fix it and get out a new dev version as soon as possible. In the meantime, you can go back to the old dev version (where you said it was working) by running `pip install coconut-develop==1.2.0.post0.devX` where `X` is the old dev version number.

That's the problem with dev versions--I can tell people to use them when I fix bugs in the release version, but then often times there are more bugs in the dev version!

**Comment by evhub** [comment]
@Nexus6 Should be fixed now in the latest `coconut-develop`!

Also, if you want to use it, `coconut-develop` now supports [PEP 526](https://www.python.org/dev/peps/pep-0526/) variable type annotations, so instead of
```
self.task_list = {'name' : task_name}                               #type: Dict[str,str]
```
you can do
```
self.task_list: Dict[str, str] = {'name': task_name}
```

Just a note, also, about type annotations if you do intend to use `--mypy` (which will invoke MyPy to type-check your compiled code, including properly type-checking Coconut built-ins). For `*args` and `**kwargs`, just annotate the elements inside the list for `*args` and the dictionary values for `**kwargs` (the keys are always strings)--that is, don't include the `List` and `Dict`.

**Comment by Nexus6** [comment]
Verified fixed  Wow, what fast turnaround, thanks!  
I don't understand your comments re: *args & **kwargs.  I understand that Any does not correctly describe the contents of these, but is there a reason to leave out the annotations completely?  What (if any) annotations are you suggesting, can you give an example?  I see that *args* should have been a Tuple not a List.  I was not aware of the PEP526 style annotations, I'm definitely going to use these in my .coco.  Are you going to preserve them (vs turning them into type: comments) in the future for -t36 and above?

**Comment by evhub** [comment]
@Nexus6 Great, good to hear!

Type annotations (including PEP526-style) are preserved if the `--target` is a Python version that supports them, otherwise, they are compiled into MyPy-compatible comments.

For `*args` and `**kwargs`, you want to do this:
```
def any_args_kwargs(*args: Any, **kwargs: Any): pass
```
which will result in `args` typed as `Tuple[Any, ...]` and `kwargs` typed as `Dict[str, Any]`.
