### ISSUE TITLE
Request for contrast

### ISSUE THREAD

**Issue by Nexus6** [evhub/coconut#197]
This is a bit of a nit (as in nit-pick) but it would be nice to have more contrast-y colors in the Coconut REPL.  In my Linux terminal I use a stock (i.e. one of the ordinary, non-custom schemes on Ubuntu) black on light-yellow color scheme.  Inside the Coconut REPL I often cannot see my code at all due to the lack of contrast against the background (see screenshot - the line reads "a,b,c = 1,2,3" .  It would be nice if the REPL, by default, would use a color scheme where text could be distinguished across a wide variety of (common) background colors.
![screenshot from 2016-10-19 20-11-42](https://cloud.githubusercontent.com/assets/556221/19545425/f96eaaca-963a-11e6-9c00-ec48bf37795b.png)

**Comment by evhub** [comment]
@Nexus6 I've been playing around with the default `--style` a lot to figure out which one seems to offer the best contrast, and I've been going back and forth a lot. The default in the release is currently `emacs`, which seemed to work pretty well, but wasn't great with dark backgrounds, so I changed develop over to `monokai`, which is what it looks like you're using.

I think I'll change the default back to `emacs`, and add an environment variable (`COCONUT_STYLE`, perhaps) so people can globally modify the default to work best with their terminal colors.

In the meantime, just pass `--style emacs` or any other valid Pygments style that looks nice. You can pass `--style list` to list out all of them.

**Comment by Nexus6** [comment]
"--style none" and "--style emacs" and "--style default" all look fine with my color scheme.  As you seem to be suggesting, I would think it would be safest to leave custom styling turned off by default (none or default).  That way you're not forcing users who have issues with colors/contrast to figure out how to fix things.  "Power users" who care enough about styling to customize it can expend the effort to figure out how to do so.  Maybe this is what your new COCONUT_STYLE approach does?

**Comment by evhub** [comment]
@Nexus6 I changed the default style to `default` in the newest `coconut-develop`, if you want to test it out! Marking this as resolved.

**Comment by Nexus6** [comment]
Verified fixed.  Thanks for the quick update!
