### ISSUE TITLE
Compile time

### ISSUE THREAD

**Issue by fredcallaway** [evhub/coconut#199]
If I copy the tutorial `vector` class 4 times, resulting in a ~170 line file, it takes 10 seconds to compile on my 2015 macbook pro 2.9 Ghz dual core. This is long enough to be pretty annoying  while developing, when I often execute a file very frequently.

I wonder if there might be a way to improve compile time. Perhaps an incremental compiler?

**Comment by evhub** [comment]
@fredcallaway Compile time is definitely a big concern. My goal will be to make 1.2.1 the fastest version of Coconut yet.

**Comment by evhub** [comment]
@fredcallaway Increasing the cache size of Coconut's packrat parser has led to a 150% - 175% compilation speed increase in `coconut-develop`, according to my testing. If you're still having problems, I'd `pip install coconut-develop` and see if it works for you too!

**Comment by fredcallaway** [comment]
Now I get a compile time of 6 seconds. Cool!
