### ISSUE TITLE
Add enhanced type definition syntax

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#200]
See comments in #121. The idea is to add a Haskell-like type definition syntax that will compile down to a MyPy-compatible type annotation.

**Comment by eshansingh** [comment]
Hey, I would love to help with this issue if you would consider it.

**Comment by evhub** [comment]
@eshansingh Yeah, absolutely! The first thing that needs to be done is just come up with a consistent system for what syntax Coconut is going to support, and what MyPy annotations that should compile to. So, for example,
```
F: int -> str
```
could compile to
```
F: typing.Callable[int, str]
```

**Comment by evhub** [comment]
Maybe steal some ideas from TypeScript here?

**Comment by evhub** [comment]
@eshansingh @fredcallaway @alexandrethsilva This has now been implemented in `develop`! Just `pip install coconut-develop`, then test out the new behavior, which you can find documented here: http://coconut.readthedocs.io/en/develop/DOCS.html#enhanced-type-annotations

**Comment by fredcallaway** [comment]
Nice! I think another example might do a better job of showcasing the full range of possibilities:

`def int_map(f: (int->int), xs: int[]) -> int[]: return list(map(f, xs))`

**Comment by evhub** [comment]
@fredcallaway And... there's a reason I have a `develop` branch to test new features. That's a bug! It's been fixed, though; `pip install --upgrade coconut-develop` and it should work.

**Comment by fredcallaway** [comment]
It sure does!

**Comment by evhub** [comment]
@fredcallaway Great! Also, [take a look](http://coconut.readthedocs.io/en/develop/DOCS.html#enhanced-type-annotations); I used your example in the documentation--good suggestion!

**Comment by evhub** [comment]
@eshansingh @fredcallaway @alexandrethsilva Add another transformation for `typing.Iterable`! Closing this, since I'm pretty happy with the new syntax Coconut has for this now.

See http://coconut.readthedocs.io/en/develop/DOCS.html#enhanced-type-annotations for the final spec.
