### ISSUE TITLE
Enhance the syntax for pipelining to a comprehension.

### ISSUE THREAD

**Issue by Sitwon** [evhub/coconut#201]
Currently, the best way I've found to pipeline to a comprehension is to wrap it in a lambda. For instance:
```
foo |> ((iterable) -> [func(item) for item in iterable])
bar |> ((iterable) -> {key: func(val) for key, val in iterable})
```

The syntax I would prefer:
```
foo |> [func(item) for item in $_]
bar |> {key: func(val) for key, val in $_}
```

**Comment by evhub** [comment]
@Sitwon Interesting suggestion. The classic FP solution would be just to do `foo |> map$(func)`, but that clearly doesn't work for the dictionary comprehension, and I'm wary to abandon Python's comprehensions that quickly. However, you can use Coconut's [implicit lambda syntax](http://coconut.readthedocs.io/en/master/DOCS.html#lambdas) to shorten your examples to:
```
foo |> (-> [func(item) for item in _])
bar |> (-> {key: func(val) for key, val in _})
```
which is nice, but could probably be improved further. Your proposed syntax seems somewhat unintuitive and non-obvious for someone reading it for the first time, however. Possible other options that I've come up with are:
```
foo |> [func(item) for item in ?]
foo |> [func(item) for item]
```
which I like better, but I'm still not sure if they're more readable than the implicit lambda version.

**Comment by evhub** [comment]
I think resolving this will also get rid of the need to resolve #170, so I'm going to close that issue with a link to this one.

**Comment by Sitwon** [comment]
I like `foo |> [func(item) for item in ?]`, but I would argue against `foo |> [func(item) for item]` as it wouldn't work well for comprehensions with nested loops.

For example:
```
table |> {cell: func(cell) for row in ? for cell in row}
```

**Comment by evhub** [comment]
I've decided that at least for now I think implicit lambdas are sufficient for this use case, so I'm closing this with a won't fix.
