### ISSUE TITLE
Enhance the syntax for partial application

### ISSUE THREAD

**Issue by Sitwon** [evhub/coconut#202]
The Coconut documentation shows an example of partial application with `pow` as:
```
map(pow$(2), range(5))
```
That works fine if you want to partially apply the first argument to pow, but what about if you want to partially apply the second argument to pow?

In Scala I could write:
```scala
(1 to 5).map(Math.pow(_, 2))
```
I would propose a similar syntax for Coconut:
```
map(pow($_, 2), range(5))
```

**Comment by evhub** [comment]
@Sitwon That's a great idea--I've added it to the v1.2.1 milestone. Most of the time, you can use keyword arguments if you want to pass the second argument (e.g. `pow$(b=2)`), but for built-ins like `pow`, keyword arguments often don't work. Adding a syntax for explicitly partially applying an arbitrary argument would be nice. I'm thinking I'll probably try to add something like this:
```
map(pow$(?, 2), range(5))
```

**Comment by evhub** [comment]
I think resolving this will also get rid of the need to resolve #170, so I'm going to close that issue with a link to this one.

**Comment by Nexus6** [comment]
I've run into a problem with the reduce() built-in that I think the proposed enhancement might solve.  Namely, there doesn't seem to be a way to supply the initializer when using (non-multi-arg) pipelining.  While I can, for example,
`reduce(func, alist, []) # in python`
... I don't see a way to do this with single-arg pipelining in Coconut.

`(alist,[]) |*> reduce$(func)`
... seems to work, but is not nearly as obvious to the reader as
`alist |> reduce$(func, ? , []) `
would be IMO.

**Comment by evhub** [comment]
@Nexus6 Yep, I agree--that's a very compelling use case. I should have this ready in `coconut-develop` fairly soon.

**Comment by Nexus6** [comment]
Great!  Would it be possible to use _ as the placeholder (rather than ?).  It's just something I've grown used to in Scala and in Python lambdas and its usage for this purpose in Coconut might be more immediately recognizable to newcomers.  Not a big deal, just askin'.

**Comment by evhub** [comment]
@Nexus6 The problem with that is that `_` is a valid Python variable name, and is used in Coconut's implicit lambdas, thus using `_` for this purpose in partial application would prevent combining partial application with implicit lambdas or the `_` variable, which is not something I'd like to do.

**Comment by evhub** [comment]
@Sitwon @Nexus6 This is now live in `coconut-develop` and will be included in the next release! Just `pip install coconut-develop` if you want to try it out.

**Comment by Nexus6** [comment]
I tried a simple example and it looks good as far as that goes.
```
>>> range(5) |> reduce$((+), ?, 0)
10
```
I'm sure I'll have plenty of uses for this new syntax.  Thanks for adding it.

**Comment by evhub** [comment]
@Nexus6 Glad to hear it!
