### ISSUE TITLE
Style problem

### ISSUE THREAD

**Issue by Nexus6** [evhub/coconut#203]
I rediscovered the -s option today, and after "fixing" some of the offenses against style, I found my code wouldn't compile any more.  Most problematic seems to be expressions that are split across lines.  Ex:
```
$ coconut -v
Coconut: Version 1.2.0-post_dev20 [Colonel] running on Python 3.5.2
$ coconut -t35
>>> a,b,c =
    1,2,3    
CoconutParseError: parsing failed (line 1)
>>> a,b,c = \
    1,2,3 
>>> a,b,c
(1, 2, 3)
```
I also encountered similar errors with long pipelines that I had to split across lines.  Ex.
```
(1,2,3) |> map$(->_*2) |> filter$(->_<3)
    |> list |> print  # does not compile

(1,2,3) |> map$(->_*2) |> filter$(->_<3)
|> list |> print  #does not compile

(1,2,3) |> map$(->_*2) |> filter$(->_<3) \
    |> list |> print  #compiles
```
Why does strict mode complain about the use of \ to split lines when it appears that such usage is necessary at least in some cases?

**Comment by Sitwon** [comment]
I believe the answer is to use [Parenthetical Continuation](https://coconut.readthedocs.io/en/master/DOCS.html#parenthetical-continuation).

**Comment by evhub** [comment]
@Nexus6 As @Sitwon commented, parenthetical continuation is the way to go. The use of backslash continuation is never necessary in Coconut--surrounding the expression in parentheses should always work, and any indentation inside of parentheses (or brackets or braces) is ignored. Fixing your examples:
```
a,b,c = (
    1,2,3
)

(
    (1,2,3)
    |> map$(->_*2)
    |> filter$(->_<3)
    |> list
    |> print
)
```

**Comment by Nexus6** [comment]
I see, thanks for the help with that.  I did scan the docs and came across the bit that @Sitwon linked to, but it didn't result in an "oh, I see, cool!" moment, most likely because ...

_"Coconut allows for the more elegant parenthetical continuation instead of the less elegant backslash continuation in del, global, nonlocal, and with statements."_

.... made it sound like the feature only applied only to the types of statements specifically enumerated and not to _any_ statement.

**Comment by evhub** [comment]
@Nexus6 The Coconut feature does only apply to those specific statements, because those are the only places where it _doesn't_ work in Python. Parenthetical continuation is a Python feature.
