### ISSUE TITLE
Calling methods on integer literals does not work

### ISSUE THREAD

**Issue by DomoSokrat** [evhub/coconut#204]
The expression `5 .bit_length()` is valid Python. But coconut transforms it to `5.bit_length()` (note the missing space) which gives a SyntaxError when executed, because the Python parser assumes that `5.` is the start of a float literal.
This is probably the only case in Python where space around an operator is relevant.

**Comment by evhub** [comment]
@DomoSokrat Good catch! As a workaround until this is fixed, try using parentheses: `(5).bit_length()`.

**Comment by evhub** [comment]
@DomoSokrat `coconut-develop` now supports `5.bit_length()` even without the space, automatically adding the space in when compiling to Python. This will be included in the next version, but you can get it now with `pip install coconut-develop`.

**Comment by DomoSokrat** [comment]
> @DomoSokrat `coconut-develop` now supports `5.bit_length()` even without the space, automatically adding the space in when compiling to Python. This will be included in the next version, but you can get it now with `pip install coconut-develop`.

Great. Many thanks,
