### ISSUE TITLE
prompt_toolkit versions

### ISSUE THREAD

**Issue by illucent** [evhub/coconut#205]
prompt_toolkit-1.0.7 somewhere  in default install config.
Current version of prompt_toolkit-1.0.9, and if I do system-wide installation:

```
pip3.5 install -U prompt-toolkit
...
```
```
AssertionError: Multiple .dist-info directories: /usr/lib64/python3.5/site-packages/prompt_toolkit-1.0.9.dist-info, /usr/lib64/python3.5/site-packages/prompt_toolkit-1.0.7.dist-info

**Comment by evhub** [comment]
@illucent Fixed in `coconut-develop`, and will be included in the next release. Just `pip install coconut-develop` to get the new version.

**Comment by evhub** [comment]
The larger problem this issue relates to is that Coconut's dependencies are restrictive of later versions. Ideally that should be changed, although it is possible for that to lead to Coconut breaking when one of its dependencies updates. I've moved that discussion to #206.
