### ISSUE TITLE
Simple import fails on Jupyter but not on REPL

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#213]
Error executing this code:
```python
from tensorbuilder.api import *
```

### Dependencies
You first need to install `tensorflow 0.12.1` and then
```
pip install tensorbuilder
```

## Side note
Thanks for creating Coconut!  I wrote this small functional programming library for python called [Phi](https://github.com/cgarciae/phi) upon which [TensorBuilder](https://github.com/cgarciae/tensorbuilder) is based on. Phi has single argument lambda support plus a bunch of other stuff like various combinators and a DSL. I was just testing Coconut and found they get along very well. Take this python example

```python
squares = [ a ** 2 for a in [1, 2, 3] ]  # [1, 4, 9]
```
now in Coconut
```python
squares = [1, 2, 3] |> map$((a) -> a**2) |> list  # [1, 4, 9]
```
Its much better but having the next would be nicer:
```python
squares = [1, 2, 3] |> map$((**2)) |> list  # [1, 4, 9]
```
However, you can get closer to this with Phi
```python
from phi import P
squares = [1, 2, 3] |> map$(P**2) |> list
```

**Comment by evhub** [comment]
@cgarciae Thanks for the issue, and I'm glad you're enjoying using Coconut! I believe this issue has already been resolved on the `develop` branch. You can run `pip install coconut-develop` to test it out and make sure.

**Comment by cgarciae** [comment]
Great! I see the method caller issue has also been resolved :)
A see that now there are 2 coconut commands: `coconut` and `coconut-develop`, but having installed `coconut-develop` they both work correctly. Is there a difference? What is the purpose of this?

**Comment by evhub** [comment]
@cgarciae `coconut-develop` always calls the develop version of coconut, whereas `coconut` calls the most-recently-installed version of coconut.
