### ISSUE TITLE
Elixir style Piping

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#214]
Libraries such as Numpy and TensorFlow feature a function-based API where most functions take in an array or tensor respectively as their first parameter. You end up writing code like this

```python
import tensorflow as tf
from tensorflow.contrib import layers

x = tf.placeholder(tf.float32, shape=[None, 4])

net = layers.fully_conneted(x, 32, activation_fn=tf.nn.elu)
net = layers.fully_conneted(net, 32, activation_fn=tf.nn.elu)
net = layers.fully_conneted(net, 16, activation_fn=tf.nn.elu)
net = layers.fully_conneted(net, 8, activation_fn=tf.nn.elu)

h = layers.fully_conneted(net, 4, activation_fn=tf.nn.softmax)
```
It would be nice if there was a way to do Elixir style Pipes (where the first argument of such pipe would be passed as first parameter to the next function) in Coconut to ease the use of these libraries. Lets imagine that `||>` was an operator such that

```python
a ||> f(b, c) == f(a, b, c)
```
then you could write the previous as
```python
import tensorflow as tf
from tensorflow.contrib import layers

x = tf.placeholder(tf.float32, shape=[None, 4])

h = (
  x 
  ||> layers.fully_conneted(32, activation_fn=tf.nn.elu)
  ||> layers.fully_conneted(16, activation_fn=tf.nn.elu)
  ||> layers.fully_conneted(8, activation_fn=tf.nn.elu)

  ||> layers.fully_conneted(4, activation_fn=tf.nn.softmax) #h
)
```
If possible I'd also like to suggest an operator for doing function composition in a forward manner, like Elm's `>>` operator. Let 
```python
f |>> g == g..f
```

**Comment by evhub** [comment]
@cgarciae You should be able to use partial application for this. Translating your example above,
```
h = (
  x 
  ||> layers.fully_conneted(32, activation_fn=tf.nn.elu)
  ||> layers.fully_conneted(16, activation_fn=tf.nn.elu)
  ||> layers.fully_conneted(8, activation_fn=tf.nn.elu)
  ||> layers.fully_conneted(4, activation_fn=tf.nn.softmax)
)
```
becomes
```
h = (
  x 
  |> layers.fully_conneted$(?, 32, activation_fn=tf.nn.elu)
  |> layers.fully_conneted$(?, 16, activation_fn=tf.nn.elu)
  |> layers.fully_conneted$(?, 8, activation_fn=tf.nn.elu)
  |> layers.fully_conneted$(?, 4, activation_fn=tf.nn.softmax)
)
```
using the new `?` version of partial application in `develop`.

**Comment by cgarciae** [comment]
@evhub Excellent! You've made my day! 

Another question. I couldnt get the `@` operator to work, even on python 3. I was trying to multiply 2 numpy matrices.

**Comment by evhub** [comment]
@cgarciae Thanks, glad to hear it! As for the `@` operator, make sure you're passing `--target 3.5` to specify that you want to allow 3.5-specific syntax (the compiled output will no longer be compatible with lower Python versions). You should be getting an error telling you to do that, which should look like this:
```
Coconut Interpreter:
(type "exit()" or press Ctrl-D to end)
>>> a @ b

CoconutTargetError: found Python 3.5 matrix multiplication (enable --target 35 to dismiss) (line 1)
  a @ b
    ^
```
