### ISSUE TITLE
Forward composition

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#220]
Sorry to bother with this again, but I'd love to see forward composition in coconut, I am already using coconut as default python language and there are things I miss from other functional language like forward composition. See [>>](http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#>>) in Elm.

Id like this expression
```
k = f .. g .. h
```
be equivalent to
```
k = h |>> g |>> f
```
I'd  guess its not that hard to implement since you can just transform it into the `..` notation and continue from there. If I may, continuing the idea of `|*>` you can even add the `|*>>` operator to unpack the output or one function as arguments into the next function.

**Comment by evhub** [comment]
@cgarciae I definitely understand the rational for function composition in the opposite direction. I'm putting this on the `v1.3.0` milestone, although I'm not sure yet what the syntax will look like.

**Comment by evhub** [comment]
Current implementation for spec for this is to introduce two new operators, `..>` and `<..`, as well as change the existing `..`. The idea is that `..` will be changed to be extremely high-precedence (make sure both `f..g(arg)` and `f..g.a(arg)` work), while `..>` and `<..` will be much lower precedence, perhaps right above piping and infix calling. `<..` will be standard mathematical composition like `..`, while `..>` will be reversed. As an extra addition, `..*>` and `<*..` could also be added that would function similarly to `|*>` and `<*|`.

**Comment by cgarciae** [comment]
Excellent! Cant wait for this :)

**Comment by evhub** [comment]
@cgarciae New `..>` and `<..` operators are live in `develop`! `..*>` and `<*..` operators still to come.

**Comment by cgarciae** [comment]
@evhub Excellent! I'll try it out :)

**Comment by evhub** [comment]
@cgarciae Star operators added and in `develop`!

**Comment by cgarciae** [comment]
Excellent! So happy with coconut, all my serious projects are now written in it.
