### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by Nexus6** [evhub/coconut#224]
I deliberately introduced a syntax error in one of my sources (simply added /2 to an empty line) and Coconut complains but then terminates too:
```
Coconut v1.2.2
$ coconut -t27 -j2 -w .

in storage.coco:
  CoconutParseError: parsing failed (line 25)
    /2
Coconut: Exiting due to CoconutParseError.
```
Coconut does **not** exit if the watcher is already running, such as when a prior compilation was successful and it's watching for something new and I subsequently introduce the error in the source and save it.  I then get the expected parser errors but the Coconut process goes back to watching again.  However, if, at that point, I CTRL-C the Coconut process and re-run it with the exact same parameters (as above) I see the parser error message and the process exits.

**Comment by evhub** [comment]
@Nexus6 That is intended behaviour. When Coconut is asked to compile a file it exits with 1 if the compilation fails, to allow other processes invoking it to know that there was an error. This is consistent regardless of what parameters are passed to the compilation. That initial compilation, however, is different from Coconut's behaviour once it begins watching--when watching a file, Coconut does not exit upon a compilation error.

I can see how this behaviour could be confusing, though. The obvious solution is that, if `--watch` is passed, Coconut should assume that it need not indicate to a calling process whether the initial compilation succeed. The argument for this is that the fact that `--watch` can never terminate means that waiting for an exit code is not a very good idea. I think I buy that argument, so I'll probably make that change soon in develop.

**Comment by evhub** [comment]
I just made that change on develop! `pip install coconut-develop` to grab it and test it out.

**Comment by Nexus6** [comment]
Tested.  As far as I can tell this issue is fixed. Thanks!
