### ISSUE TITLE
Why the name coconut?

### ISSUE THREAD

**Issue by ikhthiandor** [evhub/coconut#225]
Just curious.

**Comment by evhub** [comment]
@ikhthiandor The name comes from Monty Python and the Holy Grail--Monty Python being where the Python programming language gets its name as well! See [Why the name Coconut?](http://coconut.readthedocs.io/en/master/FAQ.html#why-the-name-coconut) in Coconut's FAQ.

**Comment by ikhthiandor** [comment]
Oh, thanks.. should've checked the FAQ.
