### ISSUE TITLE
Jupyter not showing correct line of errors on Coconut kernel

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#234]
Hi. I think this is related to the fix where coconut was taking a lot of time compiling and you said that it was because of new lines in the document. I am just guessing but my intuition is that you are removing them from the code so Jupyter compiles fast, but that is now causing the error to be reported on the wrong line.

I have to resort back to the python kernel and change the code when I get error I dont understand just to see the exact line. This is really sad since coconut makes the code a lot cleaner.

**Comment by evhub** [comment]
@cgarciae I'll see what I can do to fix that! Can I see the code you're entering and the error message you're getting?

**Comment by cgarciae** [comment]
@evhub Sadly I am using some local packages so the setting up the code would not be straight forward.   However, here is a simple example that gets the line number wrong

```python
def bar():
    
    
    
    nothing
    
    

def fun():
    
    
    
    
    bar()
    

    
```
Here I get the error

>NameError                                 Traceback (most recent call last)
>\<ipython-input-40-69e6a439c52d> in \<module>()
>
>\<ipython-input-39-cf5f1533a47a> in fun()
>
> \<ipython-input-39-cf5f1533a47a> in bar()
>     10 
>     11 
>---> 12 
>     13 
>     14     bar()
>
>NameError: global name 'nothing' is not defined

As you see the arrow locating the line points at line `12` but the error is on line `14`.

**Comment by cgarciae** [comment]
Using the python kernel I get

```
NameError                                 Traceback (most recent call last)
<ipython-input-2-69e6a439c52d> in <module>()
----> 1 fun()

<ipython-input-1-cf5f1533a47a> in fun()
     12 
     13 
---> 14     bar()
     15 
     16 

<ipython-input-1-cf5f1533a47a> in bar()
      3 
      4 
----> 5     nothing
      6 
      7 

NameError: global name 'nothing' is not defined
```

**Comment by evhub** [comment]
@cgarciae This should be fixed in the latest `coconut-develop`--just `pip install coconut-develop` to test it out!

**Comment by cgarciae** [comment]
Thanks a lot! Back to coconut :)
