### ISSUE TITLE
Add fmap built-in

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#237]
`fmap` would look like:
```
def fmap(func, obj) =
    obj |> map$(func) |*> obj.__class__
```

**Comment by Sitwon** [comment]
Is the intention here a variation on `map` that returns an iterable of the same kind?
Eg, list -> list, tuple -> tuple, str -> str?

**Comment by evhub** [comment]
@Sitwon Yep, that's exactly it! There was a discussion on [Gitter](https://gitter.im/evhub/coconut) that this stems from about adding more FP-style tools to Coconut. The rationale is that if you added a function like the above, it would make it a lot easier to do this:
```
>>> data Nothing()
>>> data Just(n)
>>> Just(3) |> map$(-> _*2) |*> Just
Just(n=6)
>>> Nothing() |> map$(-> _*2) |*> Nothing
Nothing()
```

**Comment by evhub** [comment]
An interesting question--should there also be a `parallel_fmap` and a `concurrent_fmap` in addition to just `fmap`? I can't see an obvious use case, but it's possible one exists.

**Comment by hasufell** [comment]
This doesn't work on lists as expected though:

```
[1,2,3] |> fmap$(_ -> _ + 1)
```
yields
```
TypeError: list() takes at most 1 argument (3 given)
```

**Comment by evhub** [comment]
@hasufell Agreed. I just finished a much more complicated version that should do the trick, however. I've put it up on `coconut-develop`, so if you want to test it out just `pip install coconut-develop` and you should be able to play around with the new `fmap` function there.

**Comment by evhub** [comment]
@hasufell @Sitwon This is now ready to be released on the `v1.2.3` milestone. You can check it out now on `coconut-develop` with `pip install coconut-develop`.

**Comment by hasufell** [comment]
On `develop` branch I get the following error for python-2.7:

```
Compiling /var/tmp/paludis/build/dev-lang-coconut-scm/image//usr/x86_64-pc-linux-gnu/lib/python2.7/site-packages/coconut/command/mypy.py ...
SyntaxError: 'return' with argument inside generator (mypy.py, line 44)
```

**Comment by evhub** [comment]
@hasufell I have no idea how you managed to trigger that error--why are you trying to compile `mypy.py`?

**Comment by hasufell** [comment]
> why are you trying to compile

Because that's what my package manager does when I install coconut.

**Comment by evhub** [comment]
@hasufell Huh. What package manager are you using? Are you not installing Coconut through `pip`?

Regardless, I changed the code around a bit and that file should compile fine on 2.7 now, though it still should never be run except on Python 3. Try it now!

**Comment by hasufell** [comment]
> Huh. What package manager are you using? Are you not installing Coconut through pip?

No, I'm using [paludis](https://paludis.exherbo.org) under [exherbo](https://exherbo.org). I've packaged [coconut](https://github.com/hasufell/hasufell-repository/blob/master/packages/dev-lang/coconut/coconut-1.2.2.exheres-0) manually.
