### ISSUE TITLE
Allow to ignore upper bounds (on dependencies)

### ISSUE THREAD

**Issue by hasufell** [evhub/coconut#238]
Upper bounds are often ignored in (source) distros, because they make the depgraph explode and often turn out to be just "wrong" (as in: too conservative). Coconut currently fails at runtime when upper bounds are not met.

**Comment by evhub** [comment]
@hasufell Which dependencies are you worried about? PyParsing needs its upper bound, for example, since Coconut is very sensitive to minute changes in the PyParsing API. The others can probably live without, though.

**Comment by hasufell** [comment]
> PyParsing needs its upper bound, for example, since Coconut is very sensitive to minute changes in the PyParsing API.

Well, shouldn't that be expressed in the test suite then instead of conservative upper bounds? Source distros use test suites and abort package installation if it fails.

**Comment by evhub** [comment]
@hasufell Coconut's test suite is way too large to run in its entirety on installation--the full thing can take up to 30 minutes. Version-checking is fast and easy. Like I said, for any dependency but PyParsing, though, I'd be willing to relax the constraints, though the upper bounds are already looser for everything else.

**Comment by hasufell** [comment]
well, I don't use pip, as a hack: a magic environment variable could do

**Comment by evhub** [comment]
@hasufell As a hack, yes, that would work--I'd rather not add something hacky like that without a compelling use case, though--what specific error are you encountering?

**Comment by hasufell** [comment]
Nothing right now, but I want to drop the upper bounds from the package. I can't do that when coconut bails out at runtime though. Testing is done distro-internal

**Comment by evhub** [comment]
@hasufell I have removed all of the unnecessary upper bounds, which should hopefully resolve any concerns about this. Currently in develop, will go out in the next version.
