### ISSUE TITLE
Clean header.py

### ISSUE THREAD

**Issue by Boscillator** [evhub/coconut#247]
Right now header.py is difficult to understand. It's very long and the indentation is weird.

I propose we could either use some form of templating to generate it, or we at least split the large, unbroken sections, into separate files. This would have the benefit of IDE features (mostly syntax highlighting) when adding things to the header.

**Comment by evhub** [comment]
@Boscillator Yeah, that's something I've been meaning to work on for a while. I think just making it use .format should do it, though a lot of care has to go into making sure it behaves the same as before. I'll see what I can do.

**Comment by evhub** [comment]
I think I'm going to release v1.2.3 first, then do this, just so that there's no chance this introduces any new bugs into v1.2.3.

**Comment by evhub** [comment]
@Boscillator The main body of the header has successfully been refactored into a template file--check it out! Closing this issue.
