### ISSUE TITLE
DOC: delete, clarify, or update reference to tail_recursive in tutorial

### ISSUE THREAD

**Issue by gdmcbain** [evhub/coconut#250]
The section of the tutorial on [sorting a sequence](http://coconut.readthedocs.io/en/v1.2.3/HELP.html#sorting-a-sequence) says 

> we can’t use `tail_recursive`

but the latter hasn't been defined previously in the tutorial and isn't later.  I saw it mentioned in #154 and #155, but couldn't find it in the current sources. Maybe it's been renamed?

**Comment by evhub** [comment]
@gdmcbain Good catch! `tail_recursive` used to be used for specifying functions for tail recursion elimination, but in v1.2.0 it was removed in favor of automatically detecting functions to which tail recursion elimination could be applied.
