### ISSUE TITLE
.a.b.c notation for nested attrgetter

### ISSUE THREAD

**Issue by Socialery** [evhub/coconut#255]
obj |> .a.b.c
    # currently does:
    obj |> attrgetter('a').b.c  # error!
    # would be neat if it did:
    obj |> attrgetter('a.b.c')  # more expected imo!

**Comment by evhub** [comment]
@Socialery That's a great catch; I'll implement in the next version for sure. Thanks!

**Comment by evhub** [comment]
@Socialery This now works in `coconut-develop`! Just `pip install coconut-develop` to get the new behaviour.
