### ISSUE TITLE
Add string addition pattern

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#256]
An example would be
```
"hello, " + name = inputstr
```
which should match `"hello, world!"`, binding `name = "world!"`. A more advanced implementation might also allow `"hello, " + name + "!"` as a valid pattern.

**Comment by cgarciae** [comment]
+1

**Comment by Sitwon** [comment]
If you can match `"prefix" + name + "suffix" = inputstr` then why not `prefix + "name" + suffix = inputstr`. But then you would have a problem if `inputstr = "XnameXnameX"`.

Regex could resolve this, does it make sense to make Regex matching first-class? Would that turn Coconut into Perl?

**Comment by cgarciae** [comment]
My usecase for an MQTT client would be:

```
case topic:
  match "/device/" + id + "/variables":
    #code
  match "/device/" + id + "/commands":
    #code
```

**Comment by evhub** [comment]
@Sitwon I am not planning on implementing `prefix + "name" + suffix` for exactly the reason you mention, in that there become multiple ways to match the pattern.

**Comment by evhub** [comment]
@cgarciae @Sitwon This has been implemented in develop! Just `pip install coconut-develop` to test it out.
