### ISSUE TITLE
In addition to implicit lambdas, also add implicit partial application for operator functions

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#258]
Broken off of #36. From that issue:

> @evhub: In addition to implicit lambdas as was implemented here, I think it would also be a good idea to add implicit operator functions using the `(? + 5)` syntax, which would be equivalent to `(+)$(?, 5)`, since I think the former is a lot easier to read. Reopening this issue to add that syntax.
> @fredcallaway: I don't love the idea of a special syntax restricted to operator expressions. Can you come up with a syntax that works cleanly for both `(? + 5)` and `(foo(?) + 5)`? For example, something like option 3 above.
> @evhub: @fredcallaway The syntax `(-> _ + 5)` or `(-> foo(_) + 5)` was already added and handles those use cases. The rationale for `(? + 5)` is that it would generate a partially-applied operator function instead of a lambda, which is significantly better for pickling, casting to a str, profiling, etc.
> @evhub: Maybe the right solution is just to detect implicit lambdas of the form `(-> _ + 5)` and automatically compile them to partially-applied operator functions, but that seems too implicit and weird to me, so I'm wary to do it.

**Comment by fredcallaway** [comment]
> Maybe the right solution is just to detect implicit lambdas of the form (-> _ + 5) and automatically compile them to partially-applied operator functions

I like this option. I think this syntax is more readable and only slightly more time-consuming to type than `(? + 5)`. Furthermore, it avoids potential confusion caused by two different meanings of `$`.

> but that seems too implicit and weird to me
I respect this concern, but I don't think it applies in this case. My understanding is that `functools.partial(operator.add, 5))` is semantically identical to `lambda x: x+1`. In any non-pathological program, compiling to the former can only prevent problems.

More generally, the mapping of Coconut code to the compiled Python is already quite complex (unlike e.g. CoffeeScript to JavaScript), so people are likely not (and should not) be making assumptions about how Coconut compiles at this level of granularity.

**Comment by cgarciae** [comment]
I prefer
```
? + 5
```
since `?` already represents the argument in partials. I could even imagine
```
some_list |> map$(? + 5)
```
BTW: Would `?` be ambiguos in this context? If it is, how about a double `??` to differentiate them?

**Comment by evhub** [comment]
@fredcallaway @cgarciae This is a tough one. I definitely think there's a use case for replacing `(+)$(2)` with something nicer, but I agree that having multiple ways of doing the same thing--both `(-> _ + 2)` and `(? + 2)`-- would be confusing. I'll consider just compiling `(-> _ + 2)` to use the operator function, but before I committed to do that I'd want to make sure that there were no use cases for actually getting the lambda instead of the partially applied operator function, which I'm not completely sure is true.

**Comment by yggdr** [comment]
I would prefer some variation of Elixir's syntax: `&(&1 + &2)`. Maybe substituting `$` for `&` since that's already associated with partial functions.

**Comment by evhub** [comment]
Current plan with this is just to go back to implementing some version of the Haskell-style `(<5)` syntax.

**Comment by evhub** [comment]
New proposed syntax is to use a single dot in place of the missing argument. The implicit partial must be contained in parentheses, just like operator functions, and the implicit argument can only be a single atom. Examples of valid syntax:
```python
(.-1)
(a+.)
(f() .. .)
```
