### ISSUE TITLE
Make coconut a true superset of Python

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#26]
That is, allow for the use of the `lambda` statement.

**Comment by candeira** [comment]
Is this decided? It could break future compatibility if Python decides to add syntax that overlaps with Coconuts, but otherwise I think it's a good idea.

**Comment by evhub** [comment]
This was added. Coconut supports use of the `lambda` statement, although it's discouraged in favor of Coconut's lambdas (using `->`). If you enable `--strict` (or `-s`) mode, Coconut will throw an error if you try to use a Python `lambda` statement.

For future reference, all closed issues not marked as `won't fix` are closed because they have been implemented.
