### ISSUE TITLE
Coconut tco optimises when it shouldn't

### ISSUE THREAD

**Issue by Boscillator** [evhub/coconut#261]
A function, who's body is only a call to another function, is tco optimized, even when it is not recursive. The code still works, but this shouldn't happen.

Examples:
```
def bar(x) = None

def foo(x) = bar(x)
```
compiles to
```
def bar(x):
    return None

@_coconut_tco
def foo(x):
    raise _coconut_tail_call(bar, x)
```

**Comment by evhub** [comment]
@Boscillator Coconut applies TCO to every return statement that directly returns a function call, preventing a new stack frame from being created. When a function returns a call to itself, then Coconut applies the more powerful optimization of TRE, which refactors the function into a while loop. See: http://coconut.readthedocs.io/en/master/DOCS.html#tail-call-optimization
