### ISSUE TITLE
Add accumulate built-in

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#266]
Python 3 has `itertools.accumulate`, but Python 2 does not. Coconut should provide an `accumulate` built-in that uses `itertools.accumulate` if it exists otherwise implementing the logic itself.

**Comment by ThomasLaPiana** [comment]
can I get some more details on this? would love to help. basically make an `accumulate` built-in that uses itertools if it is python3, but if it is python2 hit a newly-written function that achieves the same result?

**Comment by evhub** [comment]
@ThomasLaPiana Yep, that's the idea! You'll want to put the new code in [`header.py_template`](https://github.com/evhub/coconut/blob/develop/coconut/compiler/templates/header.py_template) and [`header.py`](https://github.com/evhub/coconut/blob/develop/coconut/compiler/header.py). Make sure to check out [the Contributing Guidelines](http://coconut.readthedocs.io/en/develop/CONTRIBUTING.html) and if you have any questions at all as you go, feel free to ask on [Gitter](https://gitter.im/evhub/coconut)!

**Comment by evhub** [comment]
Added as `scan` (standard FP name) since argument order was changed from `accumulate`.
