### ISSUE TITLE
Add support for MyPy types in data blocks

### ISSUE THREAD

**Issue by jonathanplatzer** [evhub/coconut#276]
It would be great if MyPy types would be allowed in `data` blocks.

If I understand the way that the immutability of the `data` block is achieved, by using a `_coconut.collections.namedtuple`, this could be easily implemented by using MyPys own `NamedTuple`.

So this
```python
data User(uid: int, username: str, friends: List[User])
   ...
```

could be compiled to this:
```python
from typing import NamedTuple

class User(NamedTuple("User", [('uid', int), 
                               ('username', str), 
                               ('friends', List[User])])):
   ...
```

**Comment by evhub** [comment]
@jonathanplatzer That's a great idea! There is the issue that `typing` doesn't exist on old Python versions, but I think I can get around that via stub file magic (real `_coconut.NamedTuple` uses `collections.namedtuple`, but stub file `_coconut.NamedTuple` uses `typing.NamedTuple`).

**Comment by evhub** [comment]
@jonathanplatzer This is now live in `coconut-develop`! Just `pip install coconut-develop` to test it out.
