### ISSUE TITLE
--ipython seems to call the wrong interpreter

### ISSUE THREAD

**Issue by betabrain** [evhub/coconut#281]
```
20:57 ~/coconut $ which python3.6
/usr/bin/python3.6
python3.6 -m coconut --jupyter console
20:56 ~/coconut $ python3.6 -m coconut --jupyter console
/home/betabrain/.local/bin/python3: Error while finding spec for 'coconut.icoconut' (ImportError: No module named 'coconut')
```

Coconut seems to wrongly call on a different Python installation from the one it's started with.

**Comment by evhub** [comment]
@betabrain This is a known issue, and unfortunately, there's not much I can do about it. Jupyter expects kernels to statically provide at install time the console command that will run them, including in this case the Python interpreter command. Coconut provides three kernels, `coconut`, `coconut2`, and `coconut3`, that try to call Python with the commands `python`, `python2`, and `python3`, respectively. I could just add another kernel for every individual Python version command as well (`coconut3.6` that calls `python3.6`), but that's a lot of kernel proliferation. I'll try to look into other ways to solve this issue, but in the meantime, your solutions are: alias `python3` to call `python3.6`, or install Coconut on `python3`.

**Comment by betabrain** [comment]
@evhub I expected that it would use the version/installation that coconut was installed to, i.e. the one that ran pip install coconut.

The luxurious variant would be to have a coconutX.X entry-point created alongside the default for every installation. That's sort of how pip seems to behave on systems with many python installations.

**Comment by evhub** [comment]
This should now be fixed on develop (just `pip install coconut-develop`) along with #540.
