### ISSUE TITLE
Defer parse actions until after parsing the whole ast

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#299]
Should significantly increase compilation speed by preventing parse actions from getting called multiple times.

**Comment by evhub** [comment]
This will also allow us to actually produce and potentially export an ast.

**Comment by iamrecursion** [comment]
Speaking of parsing is there a formal specification of the Coconut grammar? I'd be interested to try and write a parser in Haskell for it, perhaps with a view of generating native Coconut binaries, but mainly as a toy project to play with the new version of `megaparsec`.

**Comment by evhub** [comment]
@iamrecursion There is, unfortunately, no formal grammar specification for Coconut. The closest thing that exists is [`Grammar` in `grammar.py`](https://github.com/evhub/coconut/blob/develop/coconut/compiler/grammar.py#L661). If you just want to generate an AST, and not actually compile any code, you'll want to ignore all the calls to `attach`, `addspace`, `condense`, `fixto`, `Group`, and `.suppress() since those don't have any meaning for the actual grammar. Also, any time you see a name that ends with `_ref`, just imagine the `_ref` part wasn't there, since that also shouldn't matter just for making an AST. Be warned, though, Coconut's grammar is very complicated and unfortunately not super well-documented right now.

**Comment by iamrecursion** [comment]
Thanks for the info! I'll see what I can do. If I manage to create a correct parser it might suffice as a grammatical spec.
