### ISSUE TITLE
Provide a conda release of Coconut

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#300]
This probably means adding a Coconut feedstock to [conda-forge](https://github.com/conda-forge/staged-recipes).

**Comment by evhub** [comment]
If Coconut was added as a feedstock, updating that feedstock should be added to the release process in `CONTRIBUTING.md`.

**Comment by evhub** [comment]
Should use [selectors](https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors) to make this act like `pip install coconut[all]`.

**Comment by szabi** [comment]
Thanks for noting this issue! I have recently migrated from pip / virtualenv to conda, and I'm very satisfied... and wanted to try coconut to be disappointed about it not being available in conda.

Do you have a (very rough) roadmap for 1.3.0? What time horizon do we have to count with, if everything goes well? (Order of magnitude of months, quarters or a year?)

Thanks for your work, with type hints / mypy coconut brings to python what I have been yearning for!

**Comment by evhub** [comment]
@szabi Glad to hear you're enjoying using Coconut! 1.3.0 is nearing completion now, and should probably be out within the next couple of months. In the meantime, try following [these instructions](http://coconut.readthedocs.io/en/develop/DOCS.html#using-conda) to install Coconut with `conda`.

**Comment by evhub** [comment]
Coconut now has a [`conda-forge` feedstock](https://github.com/conda-forge/coconut-feedstock)!
