### ISSUE TITLE
Compile Python 3.6 f-strings to universal code

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#301]
https://www.python.org/dev/peps/pep-0498/

**Comment by creatorrr** [comment]
Any ETA on this? Currently, code inside f-strings is not compiled correctly, e.g.
`f"Hello {user?.name}"` compiles to `f"Hello {user?.name}"`.

**Comment by evhub** [comment]
@creatorrr Should be done by 1.4.0, but if possible I'll see if I can squeeze it into 1.3.2!

**Comment by evhub** [comment]
Digging into PEP 498, it looks like supporting this will be far, far more difficult than I thought. There are a whole host of problems here. Noting my current best set of workarounds for future reference:

- during pre-processing, split f strings into their components,
- then, to determine where the expressions are, parse the string _in reverse_, since otherwise there's no way to tell whether an `!` or `:` is part of the expression or part of a conversion/format specifier,
- finally, recursively pre-process and compile the extracted expressions.

**Comment by creatorrr** [comment]
Hmm I see. Definitely way less trivial than it seemed at the outset. Maybe look at how javascript's [tagged literals are parsed for inspiration](http://www.ecma-international.org/ecma-262/6.0/#sec-tagged-templates)?

**Comment by evhub** [comment]
@creatorrr The real issue here is that f strings don't play well with Coconut's pre-processing model. Coconut has a pre-processing phase in which it handles strings, comments, indentation, etc. which needs to be able to statically determine what is and is not an expression. And this pre-processing phase has to happen before anything can actually get parsed. But f strings require the parsing of expressions to determine what is and is not an expression, which is a problem since Coconut's pre-processing model doesn't allow the dependency to go in that direction. My current workaround for this is parsing the strings in reverse, since format specifiers and conversions should be simple enough that you can just parse those and whatever remains inside the braces is an expression. That way you don't have to actually do any expression parsing to determine what is and is not an expression. This will require writing a reverse grammar for conversions and format specifiers, however, which will be really annoying since you have to specify the whole grammar in reverse, but should be theoretically doable.

**Comment by bj0** [comment]
Oh I didn't think about haveing coconut syntax inside of it.  But you could just make the same restriction right?  What coconut syntax runs into trouble except the `::` operator?

**Comment by evhub** [comment]
@creatorrr @bj0 @Nexus6 This should now be working on `coconut-develop`! Just `pip install -U coconut-develop` to get the latest version.
