### ISSUE TITLE
BytesIO import error on Python 2.7

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#308]
I see that my `.py` file gets this code added

```python
if _coconut_sys.version_info < (3,):
    import BytesIO.BytesIO as BytesIO
else:
    from io import BytesIO
```
which yields the following error
> Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from pilot_cli import UdacityEnv
  File "/data/kiwi/pilot-cli/pilot_cli/__init__.py", line 22, in <module>
    from .udacity_env import UdacityEnv
  File "/data/kiwi/pilot-cli/pilot_cli/udacity_env.py", line 25, in <module>
    import BytesIO.BytesIO as BytesIO
ImportError: No module named BytesIO.BytesIO

My original code for that line is just

```python
from io import BytesIO
```
which works in Python `2.7.12+`

**Comment by evhub** [comment]
@cgarciae I believe this is already fixed on `coconut-develop`; if you `pip install coconut-develop` does the problem go away?
