### ISSUE TITLE
ImportError: cannot import name _coconut_NamedTuple

### ISSUE THREAD

**Issue by cgarciae** [evhub/coconut#310]
I am getting
> from __coconut__ import _coconut, _coconut_NamedTuple, _coconut_MatchError, _coconut_igetitem, _coconut_base_compose, _coconut_forward_compose, _coconut_back_compose, _coconut_forward_star_compose, _coconut_back_star_compose, _coconut_pipe, _coconut_star_pipe, _coconut_back_pipe, _coconut_back_star_pipe, _coconut_bool_and, _coconut_bool_or, _coconut_none_coalesce, _coconut_minus, _coconut_map, _coconut_partial
ImportError: cannot import name _coconut_NamedTuple

on Python 2.7.12+ on `coconut-develop`.

**Comment by evhub** [comment]
@cgarciae Is this happening at the interpreter, or when you execute compiled code? If the latter, did you make sure to recompile everything with the new version? This seems like an incompatibility between code compiled on `develop` and code compiled on `master`.
