### ISSUE TITLE
coconut-run doesn't run without source-compiled .py file

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#313]
Related to #287:
```
ash@mega:~/Desktop/svn/projects/scripts> coconut -n sunatnoon.coco 
Compiling         sunatnoon.coco ...
Compiled          sunatnoon.coco without writing to file.

ash@mega:~/Desktop/svn/projects/scripts> coconut-run -n sunatnoon.coco
Traceback (most recent call last):
  File "<string>", line 532, in <module>
IndexError: list index out of range

ash@mega:~/Desktop/svn/projects/scripts> coconut-run sunatnoon.coco
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib64/python3.4/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ash/Desktop/svn/projects/scripts/sunatnoon.py", line 533, in <module>
    date = sys.argv[1]  # string MMDD
IndexError: list index out of range

ash@mega:~/Desktop/svn/projects/scripts> coconut-run sunatnoon.coco 0622
Sun height (degrees): 56.177154
```

**Comment by evhub** [comment]
@ArneBachmann I think the problem is just that you aren't passing the required `0622` command-line argument to your program in the cases where it's failing. Try `coconut-run -n sunatnoon.coco 0622`.

**Comment by ArneBachmann** [comment]
You're right - but the error message is not helping (what module, what's that line 523). The compiled error message is more clear (`sys.argv` is mentioned).

**Comment by evhub** [comment]
@ArneBachmann Yeah, that's a good point about the error message! Unfortunately, there's not much I can do about that without changing the way `-n` works, since right now `-n` tells Coconut not to actually compile to a file, so it can't get a full error message. Perhaps if `-n` told Coconut to compile to a temporary file, that might work. I've just raised #314 to track that idea!
