### ISSUE TITLE
Extend syntax to multi-line piping

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#315]
After converting some Python code to Coconut, I discovered some drawbacks:
The `<|` and `|>` operators should be usable for purposes of "railway oriented programming", as [other programming languages](https://fsharpforfunandprofit.com/posts/recipe-part2/) have it, but in Coconut all expressions have to be on the same line:

`generate |> filterStep |> consume`

should be able to write

```
generate
  |> filterStep
  |> consume
```
or
```
consumer
  <| filterStep
  <| generator
```
or even using line the continuation
```
generate \
  |> filterStep \
  |> consume
```
This would allow for so much more beautiful code, especially when you have some larger lines (as I tend to have often with long method names and literal string outpuit - bad example following):
```
    message = "  # Computed annual sum of hourly radiation during observed times: {}"
    cityLocation, sides, atHomeTimes, houseLightingObstacles.get(house, defaultObstacle)) |> str.format$(message) |> print
```

**Comment by evhub** [comment]
@ArneBachmann In Python, and therefore in Coconut, any lines wrapped in parentheses are implicitly joined together. Thus, you can just do
```
(consumer
  |> filterStep
  |> consume)
```
