### ISSUE TITLE
Add reversed conditional order

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#322]
I'd like to write `return 0. if degrees >= 90.`, which reads just like English, a feature that Perl (I think) provides.

Speaking of: We could also introduce the unfamous `unless ...` keyword which is the same as `if not ...`, usable in the same way as above condition :-)

**Comment by evhub** [comment]
@ArneBachmann I'm not sure about this. I'm skeptical that there are use cases for these that can't be done equally as nice in Coconut already. I'd like Coconut to stick to the Python ideology of one way to do things than the Perl ideology of multiple ways. Maybe if there was a very convincing use case I'd be willing to consider it.
