### ISSUE TITLE
Add support for kwargs pipes

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#323]
Should support
```
func$(kwd_arg=?)
```

**Comment by ArneBachmann** [comment]
This would make kwargs positional, which may or may not something we want...

**Comment by evhub** [comment]
@ArneBachmann Yeah, this would allow turning a keyword argument into a positional argument, which has a valid use case if you want to pipe into a function that requires keyword parameters, for example.

**Comment by ArneBachmann** [comment]
Maybe I'm not yet into the Coco details yet, but I'm still missing the `|**>`and `<**|` operators that would support kwargs piping anywhere. If this was a thing, above problem with the partial application could be done differently. Basic idea:
```
x = {}
(a = 1, b = 2) |**> x.update  # dictionary update using kw-syntax
{"a": 1, "b": 2} |**> x.update  # dictionary update using dict literal
```
This might allow a different handling of above argument ellipsis issue, replacing the `?` of positional ellipsis with something else.
Not sure about possible syntax, but something like the `str.format` syntax might be an option:
```
func$(kwd_arg = {key}) <**| kwargs
#  or
func$(kwd_arg = ?key)  # requiring a named argument "key", assigned to the argument kwd_arg
```
Or even requiring the omitted parameter to have the same name as the one required.

**Comment by evhub** [comment]
@ArneBachmann Something like `{"a": 1} |**> func` isn't a bad idea! That's definitely another valid way to solve this problem. I'm not sure which I like better, or if I even think we should do both.

**Comment by iamrecursion** [comment]
I have some concerns over turning kwargs into positional arguments. It’s just asking for ‘gotchas’ in my opinion. The `|**>` and `<**|` operators are nicer in my opinion just from that perspective.

**Comment by hoishing** [comment]
I also think `|**>` would be nice, because its consistent with the current `|*>` for destructuring arguments

**Comment by evhub** [comment]
@ArneBachmann @iamrecursion @hoishing @arnauorriols This is now live on `coconut-develop`! Just `pip install -U coconut-develop` to get the latest version.

**Comment by ArneBachmann** [comment]
Since pip upgrading to the latest develop version, coconut -p compiles all files every time, not skipping any. When then importing files via import, it takes a long time, so probably coconut compiles them once more. Probably a version conflict between file metadata and runtime?

**Comment by evhub** [comment]
@ArneBachmann Hmmmm... can you raise an issue for that, and include exactly what the commands are that you're running and what the directory structure looks like for your files?

**Comment by ArneBachmann** [comment]
Must have been a Problem with the `pip update`. After restarting the computer, the problem seems gone. Happy to now test the new features!
