### ISSUE TITLE
How should pattern matching work with lazy lists

### ISSUE THREAD

**Issue by meadsteve** [evhub/coconut#324]
Given the function:

```python
def take_first([x] + _):
     return x
```

should the following match rather than throwing?: 

```python
items = (| "hugin", "munin" |)
take_first(items)
```

**Comment by evhub** [comment]
@meadsteve If you want to match lazy lists, just do
```
def take_first([x] :: _) = x
```
instead! Using `::` tells Coconut that you want to match arbitrary iterators, not just actual sequences.
