### ISSUE TITLE
How to write Python2/3 agnostic modularized imports?

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#328]
In Python 3 I have to do something like `from package.module import *`, it's not possible to omit the entire module hierarchy.
In Python 2 I think it's different `from package import module` is possible.

How do I write imports to be correctly transpiled to Py2 and Py3 as well?

**Comment by ArneBachmann** [comment]
What I mean, is there a single Coconut-sanctioned syntax for all cases of different module imports, that will be transformed to the specified target Python? Maybe through `six.py` or something?

**Comment by evhub** [comment]
@ArneBachmann The syntax `from package import module` will work on both Python 2 and Python 3. Coconut will make sure that if you use the Python 3 name to import a standard library module that goes by different names under Python 2 or 3 it will work on any version, but it currently doesn't do anything to imports beyond that.
