### ISSUE TITLE
Conda forge install coconut kernel add to local jupyter

### ISSUE THREAD

**Issue by Davidnet** [evhub/coconut#336]
Hello! I've added coconut from conda-forge channel and I had installed the last version of jupyter 4.3.0 and every time I try to create a new coconut jupyter notebook it throws that it cannot find a kernel named coconut3

**Comment by evhub** [comment]
@Davidnet You probably just need to tell Coconut to reinstall the kernels, which you can do by running
```
coconut --verbose --jupyter
```
then let me know what you see, and if there's still an issue, the output from that should be enough to figure out what's going on.

**Comment by Davidnet** [comment]
Corrected I been able to solve the issue. Thanks for the amazing work!
