### ISSUE TITLE
Strange return behavior

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#342]
When using
```
import sys
class Exit:
  def __init__(_, msg): print(msg); sys.exit(1)
def func():
  raise Exit("message")

func()
```
I get no error. How is it possible I can raise an object that isn't inheriting from `RuntimeError` or `Exception`? Is that normal?

**Comment by evhub** [comment]
@ArneBachmann What Python version are you using? On Python 3.6, I get
```
Traceback (most recent call last):
  File "c:\users\evan\documents\github\coconut\coconut\command\util.py", line 146, in exec_func
    exec(code, glob_vars)
  File "<string>", line 1, in <module>
TypeError: exceptions must derive from BaseException
```
and on Python 2.7, I get
```
Traceback (most recent call last):
  File "c:\users\evan\documents\github\coconut\coconut\command\util.py", line 146, in exec_func
    exec(code, glob_vars)
  File "<string>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not Exit
```
though in either case I get an error.

**Comment by ArneBachmann** [comment]
It's Python 2.7.13 64bit on OpenSUSE 42.3, but you know my system is a bit messed up regarding Python2/3.

Anyway I'm not getting errors in Python *nor* Coconut, being exited from interpreter back to command line.

**Comment by evhub** [comment]
@ArneBachmann Ah, I see. You're calling `sys.exit` in the constructor, which exits the interpreter before the function has a chance to return. You should see `message` then it should exit, since that's what your `Exit` constructor does.

**Comment by ArneBachmann** [comment]
OK, it seems in Python you can raise any object. That was my confusion and still seems wrong, but it´s just that way.
