### ISSUE TITLE
Add support for annotating multiple assignment

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#343]
```
branch:str, revision:str = "a/b".split("/")
```
doesn't work while
```
tmp = "a/b".split("/")
branch:str = tmp[0]
revision:str = tmp[1]
```
does work. Is the type annotation grammar limited?

**Comment by evhub** [comment]
@ArneBachmann [PEP 526](https://www.python.org/dev/peps/pep-0526/#where-annotations-aren-t-allowed) doesn't support `a: t, b:t = x` syntax, though Coconut could add it as a feature!

**Comment by ArneBachmann** [comment]
Great! Hope this can be parsed in an unambiguous way.

**Comment by evhub** [comment]
I don't think there's an unambiguous way to do this, so closing as won't fix.
