### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#344]
Sorry for not being very constructive, but the Coconut compiler|s performance is somewhat abysmal.
For a 500 LOC tool it takes about 10 seconds on my Linux laptop, and 15s on my 4 years old Windows PC.
This is simply too slow for the typical Python REPL testing/prototyping workflow.

Any ideas on how to improve on speed?

**Comment by evhub** [comment]
@ArneBachmann See the FAQ entry on [how do I achieve maximum performance](http://coconut.readthedocs.io/en/master/FAQ.html#i-want-to-use-coconut-in-a-production-environment-how-do-i-achieve-maximum-performance). If you just use `cPyparsing` or `PyPy`, you can get a lot of the way towards significantly improved performance. In the long run, #299 is my current best bet for how to improve base performance, though it'll be a big undertaking.

**Comment by ArneBachmann** [comment]
I'm reaching 15s per compile for 900 LOC. It becomes harder and harder to test and debug. Splitting the code into many different files is no option either, due to #320

**Comment by evhub** [comment]
@ArneBachmann Yeah, I'll definitely prioritize trying to get some work done on this front as soon as possible, and #320 is on my short list of things to do before the next release.

**Comment by evhub** [comment]
@ArneBachmann Try cloning and installing the new [computation-graph branch](https://github.com/evhub/coconut/tree/computation-graph) and see if it helps with your performance issues! If you do, definitely comment on the [computation graph pull request](https://github.com/evhub/coconut/pull/371) and let me know how it worked out for you.

**Comment by ArneBachmann** [comment]
Hint: the code to upgrade is `sudo pip3 install -U git+https://github.com/evhub/coconut.git`

**Comment by evhub** [comment]
@ArneBachmann Coconut doesn't support installation via `setup.py`--you must use `pip`. Try `make wipe` to remove previous versions of Coconut, then `make install` to install the version you just cloned.

**Comment by ArneBachmann** [comment]
Just tried installing that on the train at 200km/h downloading all kinds of dependencies that the mainline coconut doesn't require, and saw that it was actually installing into Python 2, while I used to install coconut always into Python 3. Anyway it somehow worked, but I couldn't detect any speed improvements so far. It takes 30 seconds to compile a 1000 lines coconut file. I'll keep you posted.

**Comment by evhub** [comment]
@ArneBachmann Thanks for trying it out! If you want to install it locally on Python 3, try `pip3 install -e .` (or `python3 -m pip install -e .`). By default, `make install` just installs into whatever the default `python` is, 2 or 3.

**Comment by ArneBachmann** [comment]
That did the trick. I'm not entirely sure, but coconut feels even slower now :-( it was 10s before, and is 20-30s now I think. Should I try pypy instead? Had good experience with in in the past.

**Comment by ArneBachmann** [comment]
Ah, seems like `--strict` make compilation much slower. Need to test again without.
