### ISSUE TITLE
Add where clauses

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#347]
For example:
```python
foo = bar + baz
   where
       bar = foo * 2
       baz = foo * 5
```

**Comment by evhub** [comment]
Proposed implementation is to compile
```python
b + c where:
    b = 1
    c = 2
````
to
```python
b = 1
c = 2
b + c
del b, c
```

**Comment by evhub** [comment]
In implementing this, it will be important to make sure that the case
```python
def f(x) = a + b where:
    a = 1
    b = 2
```
is handled correctly, such that we get
```python
a = 1
b = 2
return a + b
```

**Comment by srumbalski** [comment]
Bikeshed:
Call it `given` not `where`.  `where` makes me think of SQL where `where` has a different meaning.  `given` in geometry lists a set of assumptions and definitions that are true while doing a problem.

**Comment by dileep-kishore** [comment]
`where-clauses` are commonly used in `haskell` to do the same thing.

```haskell
foo :: Integer -> Integer -> Integer 
foo x y = a - b
    where 
    a = x + y
    b = x * y
```

It is similar to `let ... in ...` found in languages like `ML`. In my opinion, the usage of `where` would make it easier to comprehend for people familiar with `haskell`.

**Comment by evhub** [comment]
@srumbalski @dileep-kishore The keyword `where` was indeed chosen to be similar to Haskell, which is I think a very desirable property for people familiar with Haskell coming to Coconut.

**Comment by evhub** [comment]
@dileep-kishore @srumbalski `where` statements are now available on `coconut-develop`! Just `pip install -U coconut-develop` to get them. Also, thanks @bshlgrs for suggesting this!
