### ISSUE TITLE
Cannot use assigment functions when inside a resource block

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#351]
```
def m(a:str) -> str =
  with open(a, "r") as fd:
    c = fd.read()
  c
```
works while the following doesn't (ParseError):
```
def m(a:str) -> str =
  with open(a, "r") as fd:
    fd.read()
```
although the fd.read() should be a valid the return expression (yet nested in the `with` block).

**Comment by evhub** [comment]
@ArneBachmann Yeah, this is due to #190 not having been implemented yet. Once #190 is done, this should be fixed as well.
