### ISSUE TITLE
What's wrong with ternary open statement?

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#359]
```
with (open("a", "r") if predicate else open("b", "r")) as fd: print(fd.read())

CoconutParseError: parsing failed (line 1)
```

**Comment by ArneBachmann** [comment]
Did abstract it away into its own function as a workaround.

**Comment by auscompgeek** [comment]
Looking at the grammar here:
https://github.com/evhub/coconut/blob/0851ee6505a2152c4841d37b5642a9b80709d2ff/coconut/compiler/grammar.py#L1462-L1463
it looks like it's trying to match a pair of parentheses around `foo as var`. Indeed, `with ((open("a", "r") if predicate else open("b", "r")) as fd): print(fd.read())` works properly from what I can tell.

Either way, a better way of expressing the specific scenario offered in the issue description is something like this:
```python
with open('a' if predicate else 'b', 'r') as f:
  print(f.read())
```

**Comment by auscompgeek** [comment]
There shouldn't really be any reason why parentheses would be allowed here; the Python grammar doesn't allow them.

**Comment by auscompgeek** [comment]
… and yes, even the simplest with statement breaks:
```pytb
CoconutParseError: parsing failed (line 1)
  with (a) as f: pass
```

**Comment by auscompgeek** [comment]
Turns out `coconut.compiler.util.maybeparens` was the wrong way around. Pull request impending, let me try to run the tests quickly. Gosh, these take a while.

**Comment by ArneBachmann** [comment]
I rather guess the ternary expression is not a with-resource itself and that's the reason it doesn't work.
I can't use above mentioned suggestion because in my case it is actually
`with (bz2.BZ2File(file, "r") if compressed else open(file, "rb")) as fd: data = fd.read()`.
But compact code aside I found an easy workaround using a boring if/else structure.

**Comment by evhub** [comment]
@ArneBachmann Thanks to the PR from @auscompgeek this should now be fixed on `develop`! Just `pip install -U coconut-develop`.
