### ISSUE TITLE
Use == instead of = for equality checking in pattern-matching

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#365]
I finally managed to write a match clause
```
          match None in reso:
            pass
          match =ConflictResolution.MINE in reso:
            pass
          match =ConflictResolution.THEIRS in reso:
            pass
          match =ConflictResolution.NEXT in reso:
            pass
```

it seems to work, but the syntax for comparison seems odd... it should be `==` not `=`.
My initial confusion was how to refer to the "in" expression inside the match expression. There is no `it` defined. The `=X` syntax looks more like an assignment though, quite unpythonic.

Am I seeing this wrong?
Also, how would I check membership? `match "1".in in expr`?

The documentation is leaving lots of questions and lacks good examples, imho.

**Comment by evhub** [comment]
@ArneBachmann Yeah, I should definitely improve the documentation on this front. The `=expr` syntax is used to evaluate `expr` and then match against the resulting value, as you've discovered. Really, `match =val in x` is just shorthand for `match temp in x if temp == val`. Thus, if you want to check `in`, you can just use a guard. For example:
```
pair = ([1, 2], (1, "1"))
match (keys, (key, val)) in pair if key in keys:
    ...
```
or, for dictionaries, you can just do
```
d = {"key": 1, "other_key": 2}
match {"key": val, **_} in d:
    ...
```

**Comment by evhub** [comment]
Also, I totally see the rationale for using `==` instead of `=`. When I implemented this, I was debating myself between those two options. It's possible that was the wrong choice, and I should deprecate it in favor of `==` for the next major version.

**Comment by ankostis** [comment]
But is it possible to match any *key*, and not just a fixed one (`"key"` in the example above)?

**Comment by ankostis** [comment]
With coconut 1.3.1, i get the following:
```python
>>> d = {'a': 2}
>>> match {k:v} in d:
...    print(k, v)
CoconutParseError: parsing failed (line 1)
  match {k:v} in d:
```

**Comment by Sitwon** [comment]
How would you expect that to resolve in the case where a dictionary has more than one key/value?

```python
>>> d = {'a': 1, 'b': 2}
>>> match {k:v} in d:
...     print(k, v) # what should be printed? or should this not match?
```

**Comment by ankostis** [comment]
I don't.
It should match only dicts with a single key-value pair.
Or at least, that is what i was expecting to happen.

**Comment by ankostis** [comment]
A relevant question that sprung to mind is, assuming the following code works:
```python
>>> d = {'a': 1, 'b': 2}
>>> match {k1:v1, k2:v2} in d:
...     print(k, v) # what should b
```

which should it be the order of the matched keys?
`k1 == 'a'` or `k1 == 'b'`?

**Comment by Sitwon** [comment]
```python
>>> d = {'a': 2}
>>> match {k:v} in d:
...     print(k, v)
CoconutParseError: parsing failed (line 1)
  match {k:v} in d:
>>> match [(k, v)] in d.items() |> list:  # ugly, but it works for this case
...     print(k, v)
a 2
>>> 
```

**Comment by evhub** [comment]
@ankostis @Sitwon Variable names for keys is something that is purposefully not allowed due to the mentioned ambiguity. If you need to match keys, I'd recommend something like:
```
d = {"a": 1}
match (| (k, v) |) in d.items():
    print(k, v)
```

**Comment by ankostis** [comment]
Which ambiguity? That ordering of the keys?  
But you still get to live with it, using the suggested list-syntax, no?
Doesn't it then worth to support the dict-syntax, directly,

**Comment by evhub** [comment]
@ankostis Consider `{a: 1, b: 2}`. If I have the dictionary `{"a": 1, "b": 2}`, we would theoretically want to match `"a"` to `a` and `"b"` to `b`. But what if the keys are in the opposite order. Then it wouldn't match! That's weird behavior that I don't want to support.

**Comment by ankostis** [comment]
Why is it weird?
The same ambiguity happens when marching with concrete keys. The values are unpredictable.

Or am i getting something wrong?

**Comment by evhub** [comment]
@ankostis With concrete keys, the values are completely predictable, since no two values can have the same key. Since two keys can have the same value, the opposite is absolutely not true.
