### ISSUE TITLE
Make any and all lazy

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#369]
Or better add a lazy/short-circuit version, because semantics differ (all evaluated vs. some evaluated):
```
def any?(pred, *lizt) = reduce(lambda a, b: a or pred(b), lizt[0] if isinstance(lizt, tuple) and len(lizt) == 1 else lizt, False)

def all?(pred, *lizt) = reduce(lambda a, b: a and pred(b), lizt[0] if isinstance(lizt, tuple) and len(lizt) == 1 else list(lizt), True)
```

This is just a rough draft for a common pattern in my codes.

**Comment by ArneBachmann** [comment]
Well then let's build one...
```
def reduce(func, lizt, last):
  for elem in lizt:
    last = func(last, elem)
  return last
```
Since `a or X` won't evaluate `X` if `a` is already `True`, above definition of `any` is somewhat short-circuit-ry...

**Comment by evhub** [comment]
That definition of `reduce` isn't lazy either.

**Comment by evhub** [comment]
@ArneBachmann Also, `any` is already lazy:
```python
>>> l = (| True, print("iterator exhausted!") |)
>>> any(l)
True
```

**Comment by ArneBachmann** [comment]
I see, when calling `any` with a generator, it's lazy, but when called with a list argument, the list needs to process everything before handing over to `any` or `all`.

But my above definition of `reduce` **does** short-circuit and thus save time (same as the built-in reduce does). I can prove it using the `timeit`module.
