### ISSUE TITLE
Don't include unused coconut classes and functions

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#372]
E.g. `class groupsof` or `class scan` are included in my transpiled code, but nowhere used throughout the file.
This decreases my testing code coverage without need.

**Comment by evhub** [comment]
@ArneBachmann This is really only doable for `--stand-alone` mode, not `--package` mode, which makes me doubt its usefulness as I suspect you're probably using `--package`. Unless you're using `--stand-alone` for some reason?

**Comment by ArneBachmann** [comment]
I didn't provide either option. But since I included `-p` in my build process, I made coverage great again (80%+). Could it depend on using `coconut` vs. `coconut-develop`? I might test this later.

**Comment by evhub** [comment]
@ArneBachmann By default, `--package` mode is used when compiling directories, and `--stand-alone` mode is used when compiling individual files. If you have more than one file, you should definitely be using `--package` not `--stand-alone`.

**Comment by ArneBachmann** [comment]
Seems good now. Using `-p` saved me from compiling each file individually and is mandatory for `--mypy`, which I wasn´t aware of.
