### ISSUE TITLE
input()

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#375]
I get `NameError: Coconut uses Python 3 "input" instead of Python 2 "raw_input"` which I understand. I should use `input()` no matter what Python target version I compile to, fine.

But even when using my old workaround
```
def user_input(msg:str) -> str =
  \(eval("input" if sys.version_info.major >= 3 else "raw_input")(msg))
```
and executing the transpiled code only with python2 I get the same error, which seems strange.
Using `input()` works fine, but I have problems mocking the user input for unit tests, as I cannot simply mock the `builtins.input()` anymore.

**Comment by ArneBachmann** [comment]
It seems to get wrapped into
```
return _coconut_tail_call(input, msg)
```

**Comment by evhub** [comment]
@ArneBachmann You should be able to just use `input` directly without any `eval` tricks, then just mock `builtins.raw_input` on Python 2 and `builtins.input` on Python 3.

**Comment by ArneBachmann** [comment]
I found the solution:
When I mock `builtins.raw_input` (which is a reference to `__builtin__.raw_input`), it doesn't work.
What did the trick was:
```
def mockInput(datas:str[], func) -> Any:
  with mock.patch("builtins.input" if sys.version_info.major >= 3 else "utility._coconut_raw_input", side_effect = datas): return func()
```
where `utility.coco` is the package under test.
