### ISSUE TITLE
Introduce int/long compatibility to Coconut

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#377]
I had to define and use a `longint` type
```
longint:Type = eval("long") if sys.version_info.major < 3 else int  # for Python 2 compatibility
```
otherwise I would exceed the `int` capacity on Python 2 versions (either during variable assignment or unpickling). Simply defining and using `long` as `int` in Python 3 didn't suffice.
Could Coconut ensure long-compatibility during transpilation instead?

**Comment by evhub** [comment]
@ArneBachmann Coconut already does this, MyPy just doesn't know about it. I'll see what I can do in modifying the stub file.
