### ISSUE TITLE
Support compiling to arbitrary file names

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#382]
Want to be able to compile `OriginalName.coco` to `OriginalName_coco.py`. Current proposed implementation would be to support accomplishing that via `coconut OriginalName.coco OriginalName_coco.py`.

**Comment by ArneBachmann** [comment]
Very good point! This would allow to track pure Python files while not tracking Coco-generated python files.

**Comment by evhub** [comment]
@ArneBachmann That's the idea, though the big remaining problem is that if you do that you have to import everything with `import file_coco as file` instead of `import file`.
