### ISSUE TITLE
Allow typing objects in type annotations without an explicit import

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#383]
Instead of writing
```python
try:
    import typing
except ImportError:
    pass

x: typing.List[str] = ["a", "b"]
```
you should be able to just write
```python
x: List[str] = ["a", "b"]
```

**Comment by ArneBachmann** [comment]
What about `TypeVar` and `Type`? Do I still need to import them, and if yes, why?

**Comment by evhub** [comment]
@ArneBachmann No, you no longer need to import any of them.

**Comment by ArneBachmann** [comment]
I still need to import manually `from typing import Generic, TypeVar`.

**Comment by ArneBachmann** [comment]
But seems to work now in 1.3.1.dev19! Great, saving again two lines of code.

**Comment by evhub** [comment]
@ArneBachmann Can I see the error message you're getting and the code/commands that produce it?

**Comment by ArneBachmann** [comment]
```
C:\Users\bach_ar\Desktop>coconut x.coco --mypy
Compiling         x.coco ...
Compiled to       x.py .

C:\Users\bach_ar\Desktop>python x.py
Traceback (most recent call last):
  File "x.py", line 20, in <module>
    Number = TypeVar("Number", int, float)
NameError: name 'TypeVar' is not defined
```

and the file is
```
#from typing import Generic, TypeVar
Number = TypeVar("Number", int, float)
```

my Python is
```
C:\Users\bach_ar\Desktop>python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by evhub** [comment]
@ArneBachmann Yeah, so the problem is that `TypeVar` appears in a context which is not a type definition. So I guess for that, you'd have to import it manually. I'll reopen this issue with the idea of finding a way to solve that issue as well, though I'm not sure it's solvable since whatever we do has to support Python 2 as well.

**Comment by evhub** [comment]
Replaced by #403.
