### ISSUE TITLE
Add support for async/await syntax transpiling to python 2

### ISSUE THREAD

**Issue by creatorrr** [evhub/coconut#384]
Similar to what [iced-coffeescript](http://maxtaco.github.io/coffee-script/) did. What do you think @evhub ?

**Comment by evhub** [comment]
@creatorrr Unfortunately, that isn't really possible without tying Coconut to a specific framework for async in Python 2. For example, Coconut could compile to [asyncq](https://github.com/quora/asynq)-compatible Python 2, but that wouldn't work if you were using a different Python 2 async framework. I'm definitely open to suggestions as to how to resolve that issue, though.

**Comment by creatorrr** [comment]
Hmm, right. I think it should be possible to find a workaround of some sort. Shot in the dark but couldn't we use [trollius](https://pypi.python.org/pypi/trollius)?

**Comment by evhub** [comment]
@creatorrr Using trollius, it looks like one possibility, which should be pretty straightforward, would be to compile
```python
async def my_coroutine():
    await another_coroutine()
    return result
```
to
```python
import trollius as asyncio
from trollius import From, Return
@asyncio.coroutine
def my_coroutine():
    yield From(another_coroutine())
    raise Return(result)
```
but the problem with that is that there's no real way to make this universal, since `From` and `Return` aren't in Python 3 `asyncio`, and trollius isn't built for Python 3. Thus, I could do this, but you'd be required to pass either `--target 2` or `--target 3` to be able to use `async`, there wouldn't be a universally-compatible way to do it. I think that's definitely better than the current situation where you have to pass `--target 3`, though I wonder if there's a way to do even better.

**Comment by creatorrr** [comment]
I think we could improve on that but the target requirement is not that bad given py2 folks using async / await syntax is a big win.

**Comment by evhub** [comment]
@creatorrr I looked into this a little bit more, and it looks like [trollius is deprecated and unmaintained](https://groups.google.com/forum/#!topic/python-tulip/mecVwhnVP0A), which makes me a little bit skeptical about using it. Thoughts?

**Comment by creatorrr** [comment]
> it looks like trollius is deprecated and unmaintained

Ah, bummer...

In that case, we could perhaps look at [txaio](https://github.com/crossbario/txaio#how-it-works). It can even be used to write universally-compatible coconut code. Same code would use `asyncio.Future` primitives in `py3` and `Twisted.Deferred` in `py2`. The only downside is that `Twisted` would become a dependency for `py2` code.

What do you think?

**Comment by evhub** [comment]
@creatorrr It looks like txaio uses callback semantics instead of coroutine semantics, so unlike with trollius there wouldn't be a nice translation that the compiler could do to turn `async` functions into txaio functions.

**Comment by creatorrr** [comment]
Oh right. That's probably because `python2` does not support the `yield from` syntax or semantics natively. I think we could maybe crack that by using [yieldfrom](https://github.com/Nurdok/yieldfrom) along with a wrapper to convert generator `yied From.

**Comment by evhub** [comment]
@creatorrr Do any asyncio frameworks support `yieldfrom`, though? At least trollius was supported by tornado--do we know anything about `yieldfrom`?

**Comment by creatorrr** [comment]
It's a real bummer that [trollius](https://pypi.python.org/pypi/trollius) is no longer maintained, that means there is no simple substitute to the `asyncio` library. In any case, here is what I was thinking:

Given coconut input:
```python
async def hi( future ):
    await asyncio.sleep(1)
    print("hi")
    await future

async def there():
    await asyncio.sleep(1)
    print("there")

# Called somewhere else
run_until_complete(hi(there()))
```

With trollius, the first example would have looked like:
```python
import trollius as asyncio

async def hi():
    await asyncio.sleep()
    print("hi")

loop = asyncio.get_event_loop()
loop.run_until_complete(hi())
```

**Comment by creatorrr** [comment]
It's a real bummer that [trollius](https://pypi.python.org/pypi/trollius) is no longer maintained, that means there is no simple substitute to the `asyncio` library. In any case, here is what I was thinking:

Given coconut input:
```python
async def hi( future ):
    await asyncio.sleep(1)
    print("hi")
    await future

async def there():
    await asyncio.sleep(1)
    print("there")

# Called somewhere else
run_until_complete(hi(there()))
```

Would have compiled to something like:
_Pending implementation of course but would work like [co](https://github.com/tj/co) using [txaio](https://github.com/crossbario/txaio#how-it-works) and [yieldfrom](https://github.com/Nurdok/yieldfrom)_
```python
from __coconut import coco_coroutine, coco_await
from yieldfrom import yieldfrom, From

@coco_coroutine
@yieldfrom
def hi( future ):
    yield From( coco_await( asyncio.sleep(1) ))
    print("hi")
    yield From( coco_await( future ))

@coco_coroutine
@yieldfrom
def there():
    yield From( coco_await(  asyncio.sleep(1) ))
    print("there")

# Called somewhere else
run_until_complete(hi(there()))
```

*****

P.S. With trollius, the first example would have looked like:
```python
import trollius as asyncio

async def hi():
    await asyncio.sleep()
    print("hi")

loop = asyncio.get_event_loop()
loop.run_until_complete(hi())
```

**Comment by creatorrr** [comment]
> @creatorrr Do any asyncio frameworks support yieldfrom, though? 

Reason I mention [yieldfrom](https://github.com/Nurdok/yieldfrom) is that `await` has semantics of `yield from` rather than 'yield` meaning that one-to-one compilation would have required some kind of workaround.

> At least trollius was supported by tornado--do we know anything about yieldfrom?

`yieldfrom` does not serve the purpose of replacing or supporting any async framework (see above). Instead, the idea is to use `txaio` for managing the `universal` code working on both py2 and py3 and then use something akin to `trollius` so to answer your question, these last 2 comments solve the **universal** problem but not the **event loop** problem and tbh, the outcome looks a bit dismal at this point.

**Comment by creatorrr** [comment]
I guess it could be a fun weekend project to backport [`python/asyncio@3.4`](https://github.com/python/cpython/tree/3.4/Lib/asyncio) to python 2, lol.

**Comment by evhub** [comment]
@creatorrr Honestly, it seems like the best option is still just to compile to trollius on Python 2, since at least tornado, txaio, etc. are compatible with it, with the disclaimer that you really should update to Python 3 if you want to be using an actively maintained library.

**Comment by creatorrr** [comment]
@evhub agreed. Kick start a PR? Happy to split the work

**Comment by evhub** [comment]
@creatorrr The `async` -> `trollius` translation doesn't look that bad, so hopefully I'll be able to hammer it out the next time I've got some real time on my hands.

**Comment by creatorrr** [comment]
Sounds good. Happy to help

**Comment by evhub** [comment]
@creatorrr This should now be working on `coconut-develop`!
