### ISSUE TITLE
Using f{} does not conform with FrozenSet[Any]

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#390]
```
  def getTrackingPatterns(_, branch:int? = None) -> FrozenSet[str] =
    ''' Returns list of tracking patterns for provided branch or current branch. '''
    f{} if not _.track and not _.picky else frozenset(_.branches[_.branch if branch is None else branch].tracked)
```
complains in mypy with
`Returning Any from function declared to return "FrozenSet[str]"` because it compiles to `return _coconut.frozenset() if not _.track and not _.picky else frozenset(_.branches[_.branch if branch is None else branch].tracked)  # line 441`

**Comment by evhub** [comment]
@ArneBachmann Whatever the typing problem is here, it's not with `f{}`--the following runs with no errors:
```
> coconut -d -c "fs: FrozenSet = f{}" --mypy
fs = _coconut.frozenset()  # type: FrozenSet
```

**Comment by ArneBachmann** [comment]
Not sure, message seems gone.
