### ISSUE TITLE
Strange behaviour of -c code vs. REPL

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#397]
```
D:\Arne\projects\sos>coconut -d -c "from unittest import mock" --mypy
from unittest import mock

<string>:13: error: Module 'unittest' has no attribute 'mock'
Exiting due to MyPy error.

D:\Arne\projects\sos>coconut
Coconut Interpreter:
(type 'exit()' or press Ctrl-D to end)
>>> from unittest import mock
>>>
```

**Comment by evhub** [comment]
@ArneBachmann The only difference is that you passed `--mypy` when you called it with `-c` and didn't pass `--mypy` when you just launched the interpreter. If you pass `--mypy` to the interpreter, you should get the same results.

**Comment by ArneBachmann** [comment]
Ok, when using `coconut --mypy` I do get the same error, but the error is wrong, right?
Since the import does import the mock function/attribute/module/whatever...
```
D:\HOLISHIP\docs\deliverables\d8.4 prep>coconut --mypy
Coconut Interpreter:
(type 'exit()' or press Ctrl-D to end)
>>> from unittest import mock
<string>:13: error: Module 'unittest' has no attribute 'mock'
>>> mock
<module 'unittest.mock' from 'd:\\apps\\miniconda3\\lib\\unittest\\mock.py'>
>>>
```

**Comment by evhub** [comment]
@ArneBachmann The error is right because you're operating in universal mode and `unittest.mock` doesn't exist in Python 2. If you want to specify that you only care about Python 3, you need to pass `--target 3`.

**Comment by ArneBachmann** [comment]
Makes sense, my bad.
