### ISSUE TITLE
Allow any statement after any other statement

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#398]
Should do the same thing Coconut does with [`else` statements](http://coconut.readthedocs.io/en/master/DOCS.html#else-statements) for all statements.

**Comment by ArneBachmann** [comment]
What about `try: 1/0; except: pass` on one line? This doesn´t seem to be supported.

**Comment by ArneBachmann** [comment]
I was eager to test out this feature, but it doesn´t work as I thought:
```
  CoconutParseError: parsing failed (line 217)
    for k, v in map.items(): if k in params: return v

  CoconutParseError: parsing failed (line 225)
    if filename is not None: with open(encode(filename), "rb") as fd: content = fd.read()
```

**Comment by evhub** [comment]
@ArneBachmann All of that is correct code, I just haven't released a new version of `coconut-develop` yet. I'll try to get on that soon.

**Comment by ArneBachmann** [comment]
Cool! Can't wait!

**Comment by evhub** [comment]
@ArneBachmann This should be up now, if you want to try it out!
