### ISSUE TITLE
Recursion problems with reload

### ISSUE THREAD

**Issue by dogwynn** [evhub/coconut#400]
There's an issue with using `importlib.reload` (and potentially reloading capabilities in IDEs) and coconut modules.

#### Problem
After reloading a module, any code that uses one of the modified builtins (I've only tested `map`), results in a `RecursionError`.

#### Replication

**rec_bug.coco**
```
def test() = [1, 2, 3] |> map$(->1) |> list
```
#### Start IPython (or normal console)

```
Jupyter console 5.2.0

Coconut 1.3.1 [Dead Parrot]

In [1]: import rec_bug

In [2]: from importlib import reload

In [3]: rec_bug.test()
Out[3]: [1, 1, 1]

In [4]: reload(rec_bug)
Out[4]: <module 'rec_bug' from '/Users/dogwynn/projects/dowright/rec_bug.py'>

In [5]: rec_bug.test()
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-5-d5f5dcb7a8a0> in <module>()
      5 from coconut.__coconut__ import _coconut, _coconut_NamedTuple, _coconut_MatchError, _coconut_tail_call, _coconut_tco, _coconut_igetitem, _coconut_base_compose, _coconut_forward_compose, _coconut_back_compose, _coconut_forward_star_compose, _coconut_back_star_compose, _coconut_pipe, _coconut_star_pipe, _coconut_back_pipe, _coconut_back_star_pipe, _coconut_bool_and, _coconut_bool_or, _coconut_none_coalesce, _coconut_minus, _coconut_map, _coconut_partial
      6 from coconut.__coconut__ import *
----> 7 rec_bug.test()  # line 1: rec_bug.test()

~/projects/dowright/rec_bug.py in tail_call_optimized_func(*args, **kwargs)
    153             if wkref is not None and wkref() is call_func:
    154                 call_func = call_func._coconut_tco_func
--> 155             result = call_func(*args, **kwargs)  # pass --no-tco to clean up your traceback
    156             if not isinstance(result, _coconut_tail_call):
    157                 return result

~/projects/dowright/rec_bug.py in test()
    654 @_coconut_tco
    655 def test():
--> 656     return _coconut_tail_call((list), map(lambda _=None: 1, [1, 2, 3]))
    657 # Test2([1, 2, 3]) |> print

~/projects/dowright/rec_bug.py in __new__(cls, function, *iterables)
    311         __doc__ = _coconut.map.__doc__
    312     def __new__(cls, function, *iterables):
--> 313         new_map = _coconut.map.__new__(cls, function, *iterables)
    314         new_map._func, new_map._iters = function, iterables
    315         return new_map

... last 1 frames repeated, from the frame below ...

~/projects/dowright/rec_bug.py in __new__(cls, function, *iterables)
    311         __doc__ = _coconut.map.__doc__
    312     def __new__(cls, function, *iterables):
--> 313         new_map = _coconut.map.__new__(cls, function, *iterables)
    314         new_map._func, new_map._iters = function, iterables
    315         return new_map

RecursionError: maximum recursion depth exceeded while calling a Python object
```

#### Potential problem
I think the issue stems from the fact that the `__coconut__.pyi` stub assigns to the `_coconut` class the relevant builtin functions it will replace (i.e. enumerate, filter, map, reversed, and zip). However, it does this from the *global* namespace.

According to the Python documentation for [`reload`](https://docs.python.org/3/library/importlib.html#importlib.reload):

> When a module is reloaded, its dictionary (containing the module’s global variables) is retained.

Unfortunately, this includes the above mentioned functions that overwrote their global builtin counterparts. So, when the reload takes place, it is the *new, coco-ized* version that is saved in the `_coconut` class.

This leads to the infinite recursion happening when using any of those builtins in a module after `reload`-ing.

#### Solutions
I use the following function to obviate the problem:

```
def reload(module) =
    import importlib
    (['enumerate', 'filter', 'map', 'reversed', 'zip']
       |> map$((k) -> module.__dict__.pop(k,None))
       |> consume)
    importlib.reload(module)
```

The longer-term solution would seem to be to modify `__coconut__.pyi` to pull these functions, and perhaps all other relevant builtin objects, from the `builtins` module, rather than the global namespace.

**Comment by evhub** [comment]
@dogwynn Nice catch! As a temporary fix, if you use `--package` instead of `--standalone`, does that resolve the problem?

**Comment by evhub** [comment]
@dogwynn Oh, yikes, that is a separate issue! `--watch` definitely shouldn't be doing that.

**Comment by evhub** [comment]
@dogwynn I believe the main issue here has been fixed in `coconut-develop`, however. If you `pip install -U coconut-develop`, does it go away?

**Comment by dogwynn** [comment]
BTW, this only happens if you don't explicitly pass `--package` to the watcher.

**Comment by dogwynn** [comment]
Boom. Score. Nicely done, sir.
