### ISSUE TITLE
Could you support jupyterlab?

### ISSUE THREAD

**Issue by szsdk** [evhub/coconut#413]
Hi, I am working on numerical physics. My career benefits a lot from coconut and jupyterlab. And from my perspective, the jupyterlab would be the next generation of jupyter. But sadly, I can not use  them at the same time. Could you help me with this?

**Comment by evhub** [comment]
@szsdk I justed tested and this seems to already be working for me, so long as you've already installed the kernel. Just run `coconut --jupyter` to install the kernel, then `jupyter lab` to run jupyterlab. To make this easier on people in the future, I'll go ahead and add a `coconut --jupyter lab` shortcut to run those two commands for you like `coconut --jupyter notebook` does.
