### ISSUE TITLE
How to import user-defined Coconut code?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [evhub/coconut#417]
I'm in a Coconut REPL launched from a folder that contains the file "graph.coco". If I type `import graph`, I get 

```
>>> import graph
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/coconut/command/util.py", line 146, in exec_func
    exec(code, glob_vars)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'graph'
```

But if I change the file extension to .py, then `import graph` works fine.

I'm getting similar problems when I include an import statement at the top of a file loaded via `exec(open( "src/graph.coco").read())`.

**Comment by evhub** [comment]
@JeffreyBenjaminBrown The feature you're looking for is currently only available in `coconut-develop`. Just `pip install -U coconut-develop` and try again!

**Comment by JeffreyBenjaminBrown** [comment]
Yuss!
