### ISSUE TITLE
Make use of multiprocessing to allow compiling many files at once

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#42]
The `command.cli` object should compile each file in a separate `compiler.processor` object in a separate process.

**Comment by evhub** [comment]
Potentially also add a flag to force single-threading. The suggested flag is `-u` or `--uniprocess`.

**Comment by Boscillator** [comment]
Should this be done only if you are compiling a directory, or for single files as well.

**Comment by Boscillator** [comment]
Working on this.

**Comment by Boscillator** [comment]
Or maybe it can wait.

**Comment by evhub** [comment]
@Boscillator This is a _hard_ issue. You're welcome to work on it if you want, but I wouldn't expect it to be easy.

**Comment by evhub** [comment]
Plan is to add `-j --jobs-in-parallel` as an option to pass in the number of processes that should be used.

**Comment by evhub** [comment]
At long last this is finally live in develop!
