### ISSUE TITLE
Discussion: Conditional assignment

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#434]
We probably already discussed this, but I really would like to do conditional assignment:
```
(a if predicate else b) = expression
```
Not sure how this can be parsed unambiguously, but it is easy to transpile to pure Python:
```
if predicate:
  a = expression
else:
  b = expression
```

**Comment by evhub** [comment]
Technically, this is possible with the new `coconut>=1.6.0` pattern-matching features, though it's not pretty. Some ways of writing this that will work:
```python
a `(x, f) -> f(x)` pred or b = arg
((def (x if pred(x)) -> x) -> a) or b = arg
```

You can make it relatively pretty, though, if you do something like:
```python
def match_if(x, f) = f(x)

a `match_if` pred or b = arg
```

**Comment by evhub** [comment]
`coconut>=2.0.0-a_dev7` now has a `match_if` built-in.

**Comment by evhub** [comment]
Another option: instead of `match_if`, just allow `` `isinstance$(int)` = 1 ``-style patterns, allowing for
```
a `pred` or b = arg
`pred` a or b = arg
```
syntaxes.

**Comment by evhub** [comment]
`match_if` is gone—you can still trivially define it with `def match_if(x, f) = f(x)`, but instead the recommended syntax is
```
a `pred` or b = arg
```
