### ISSUE TITLE
Document sequence indexing behavior

### ISSUE THREAD

**Issue by bj0** [evhub/coconut#445]
I was trying to figure out what I could use to get a *first* element from a manipulated sequence, which led me to try what was allowed syntax for indexing sequences.  I found the following:

    range(10)[0]                                        # works
    range(10)$[0]                                       # works
    range(10) |> .[0]                                   # works
    range(10) |> .$[0]                                  # works

    range(10) |> map$(i->i*2)[0]                        # doesn't work
    range(10) |> map$(i->i*2)$[0]                       # doesn't work
    range(10) |> map$(i->i*2) |> .[0]                   # works
    range(10) |> map$(i->i*2) |> .$[0]                  # works

    range(10) |> filter$(i->i>3)[0]                     # doesn't work 
    range(10) |> filter$(i->i>3)$[0]                    # doesn't work
    range(10) |> filter$(i->i>3) |> .[0]                # doesn't work 
    range(10) |> filter$(i->i>3) |> .$[0]               # fixed in develop

I'm not sure if all these are supposed to work, or if there are reasons for some not working, but I couldn't find reasons in the docs about it.

**Comment by evhub** [comment]
Everything you're seeing there is intended behavior. The ones of the form `x |> y[0]` aren't working because indexing has greater precedence than piping, so `x |> y[0] = x |> (y[0])`. The direct `.[0]` indexing on filter doesn't work because there is no efficient `O(1)` way to index a filter. Thus, if you really want to index it, you have to explicitly say you want to use iterator indexing.

**Comment by bj0** [comment]
Ok, that makes sense.  Is `range()[0]` just special cased then?

**Comment by evhub** [comment]
No, not at all--how is `range()[0]` a special case?

**Comment by evhub** [comment]
Yeah, that's right. For `range` and `map` it is possible to do `O(1)` indexing, and thus Coconut adds support for vanilla Python indexing on those objects.

**Comment by eindiran** [comment]
@evhub Did you add the documentation tag because you want the docs on this to be expanded?

**Comment by evhub** [comment]
@eindiran Yeah, that was the idea. Updated the title to reflect that.
