### ISSUE TITLE
Better coconut-mode in Emacs

### ISSUE THREAD

**Issue by r-zip** [evhub/coconut#454]
The language looks really nice, but without some tooling around it I'll find it hard to use at work and for personal projects.

It would be great if there were a coconut-mode for Emacs that did more than just syntax highlighting. If we could get autocomplete and REPL interaction in an Emacs package, I'd be 100x more inclined to try it out seriously.

I'll consider trying to put this together in my spare time if no one else volunteers.

**Comment by evhub** [comment]
For future reference, the currently available Emacs modes appear to be [this one](https://github.com/NickSeagull/coconut-mode) and [this one](https://github.com/padawanphysicist/coconut-mode).

**Comment by kobarity** [comment]
@r-zip , if you are still looking for Coconut mode for Emacs, please take a look at [Coconut language support for Emacs](https://codeberg.org/kobarity/emacs-coconut). It is a porting of python.el and supports completion and REPL (Inferior Coconut process).
