### ISSUE TITLE
Shorter syntax for pattern matching function definitions

### ISSUE THREAD

**Issue by MichalMarsalek** [evhub/coconut#465]
Can we have something like:
```
def factorial(0) = 1
pdef factorial(n) = n * factorial(n - 1)
```
as a syntactic sugar for
```
def factorial(0) = 1

@addpattern(factorial)
def factorial(n) = n * factorial(n - 1)
```
so that it's closer to Haskell way of defining a function with multiple patterns?
Honestly, having to put `@addpattern(function_name)`  before each definition kind of discourages me from doing it this way, instead of something like
`factorial = n -> n*factorial(n-1) if n else 1`
Of course factorial is just an example and `pdef` could be something entirely different.

**Comment by evhub** [comment]
I'd like to add this, but I'm not sure what the right syntax should be. `pdef` is nice and short, but not very informative. `pattern def` matches `async def` or `match def`, though it's a bit weird since `pattern` isn't a keyword on its own and it's somewhat long. Thoughts?

Also we'll want to make sure `match pdef` (or whatever) raises an error, since `pdef` should imply `match def`.

**Comment by MichalMarsalek** [comment]
I don't know, what you wrote are good points.

**Comment by eindiran** [comment]
I like the `pattern def` syntax. It matches with `async def` and `match def` quite well. The difference between the old Python 3.4 syntax
```python
@asyncio.coroutine
def some_function():
    ...
```
and the modern `async def` is analogous to the long form syntax and the proposed new syntax.

Regarding your point that `pattern` is not its own keyword, that matches how `async` is used with `with` or `def`.

The keyword `pattern` is a bit long, but being clear and informative makes typing a few more characters worth it for almost anything than isn't code golfing.

**Comment by evhub** [comment]
This has now been implemented in `coconut-develop` as `addpattern def`!
