### ISSUE TITLE
prompt_toolkit dependency incorrect

### ISSUE THREAD

**Issue by khayyamsaleem** [evhub/coconut#468]
upon `pip install --upgrade coconut coconut-develop`, following error occurs:
`pkg_resources.DistributionNotFound: The 'prompt_toolkit<.2,>=1' distribution was not found and is required by coconut-develop`

Fixed with `pip install "prompt_toolkit<.2,>=1"`

**Comment by evhub** [comment]
Should be fixed in the latest `coconut-develop`!

**Comment by khayyamsaleem** [comment]
thanks! crazy fast
