### ISSUE TITLE
Support assignment expression syntax, Python 3.8

### ISSUE THREAD

**Issue by terrdavis** [evhub/coconut#482]
Python 3.8 has assignment expressions (see [PEP 572](https://www.python.org/dev/peps/pep-0572/)). Coconut does not support this syntax yet.
```python
py -3.8 -m coconut
Coconut Interpreter:
(type 'exit()' or press Ctrl-D to end)
>>> 123 |> print
123
>>> (abc:=123) |> print

CoconutParseError: parsing failed (line 1)
  (abc:=123) |> print
>>> print(abc:=123)

CoconutParseError: parsing failed (line 1)
  print(abc:=123)
>>>
```

```python
py -3.8
Python 3.8.0a1 (tags/v3.8.0a1:e75eeb00b5, Feb  3 2019, 20:47:39) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print(abc:=123)
123
>>> abc
123
>>>
```

**Comment by terrdavis** [comment]
Workaround: [passthroughs](https://coconut.readthedocs.io/en/master/DOCS.html#code-passthrough)
```
>>> \(abc:=123) |> print
123
>>> \(print(abc:=123))
123
>>> print(\(abc:=123))
123
>>> \\print(abc:=123)
123
>>>
```

**Comment by evhub** [comment]
@terrdavis This should now be working on `coconut-develop`! Just `pip install -U coconut-develop` to get the latest version.

**Comment by pavelbraginskiy** [comment]
@evhub Is it universal or does it require a 37 target?

**Comment by evhub** [comment]
@pavelbraginskiy It's not universal--it requires a 3.8 target. If you're interested in having this be universal, you should raise a separate issue for that!

**Comment by pavelbraginskiy** [comment]
@evhub I think I will do that, but in the meantime, DOCS.md doesn't mention it requiring the target.

**Comment by evhub** [comment]
@pavelbraginskiy DOCS should now be fixed on `develop`.
