### ISSUE TITLE
fmap with numpy array

### ISSUE THREAD

**Issue by hoishing** [evhub/coconut#483]
I got a strange output while using fmap with numpy

`fmap(-> _ + 1, np.arange(3))`

produce

```
array([[[2.22809558e-312, 2.14321575e-312, 2.35541533e-312],
        [6.79038654e-313, 2.22809558e-312, 2.14321575e-312]]])
```

instead of 

`array([1, 2, 3])`

Any idea?

I am using coconut 1.4.0 with python 3.7.2

**Comment by narfanar** [comment]
`fmap(f, c)` needs an implementation per `type(c)` that tells it how to package up the result of applying `f` to the contents of `c` (which might be or might not be the same type as the contents of `c`).

**Comment by evhub** [comment]
@hoishing @narfanar I've added a special case to `fmap` to handle numpy arrays by using `np.vectorize` (just `pip install -U coconut-develop` to get the latest version)!

Also, for the record, the strange output is coming from the fact that `fmap` is calling `makedata(np.ndarray, 1, 2, 3)` which produces an array of shape `(1, 2, 3)` with arbitrary data inside of it.
