### ISSUE TITLE
Typing bound variables in context managers

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#487]
I'm wondering, do you have any ideas how to type the variables bound in a `with` block?

```python
import uuid
from tempfile import TemporaryDirectory
with TemporaryDirectory() as (tmp:TemporaryDirectory):
  filename:str = os.path.join(tmp, uuid.uuid4().hex + ".wav")
  print(filename)
```

It looks wrong since the type definition is tacked on somewhere at the end.
But if I introduce `tmp` before, it must allow `None` be `Optional[TemporayDirectory]`).

The same problem exists for `for` loops and `match` statements, but probably it's a problem with Python and Mypy and cannot be solved independently by Coconut.

The specific problem arise from the use of `:` colon for typing, which is also used for block introduction.
Maybe using `#` (no - comment) or another special character could solve it.

What remans? `~``\!^°` or probably `=:` ?

**Comment by evhub** [comment]
@ArneBachmann I think you should be able to do
```python
tmp: TemporaryDirectory
with TemporaryDirectory() as tmp:
    ...
```

**Comment by ArneBachmann** [comment]
OK, I cannot reproduce the `Optional` problem just when I wanted to...

On a sidenote, this particular case has some strange coercion:
```
from tempfile import TemporaryDirectory

tmp:TemporaryDirectory = TemporaryDirectory()
print((type(tmp), tmp))

with TemporaryDirectory() as tmp2:
  print((type(tmp2), tmp2))
```
shows that the context manager coerces the tempdir to a string? That's new to me.
```
(<class 'tempfile.TemporaryDirectory'>, <TemporaryDirectory 'C:\\Users\\Arne\\AppData\\Local\\Temp\\tmpvqof7zxu'>)
(<class 'str'>, 'C:\\Users\\Arne\\AppData\\Local\\Temp\\tmp0jhw4udu')
```

**Comment by evhub** [comment]
@ArneBachmann The `__enter__` method of `TemporaryDirectory()` must return a string--that's what gets called when you use a `with` statement.
