### ISSUE TITLE
data types with pattern matching

### ISSUE THREAD

**Issue by arnauorriols** [evhub/coconut#494]
We use pattern matching extensively as a means to increase the type safety of our applications at runtime. After some experience, we concluded that this was safer than using MyPy. 

We do type-checking-with-pattern-matching in funcion definitions, and also in data types. However, this has the consequence that we are forced to always define the `__new__` method of the data types to specify the pattern matching:

```
data Foo(x, y):
    def __new__(cls, x is int, y is str):
        return makedata(cls, x, y)
```

Apart from tedious, this adds 3 lines where the properties of a data type are explicited, a duplication that sometimes becomes the source of bugs. 

Would it be possible to include pattern-matching in the same data declaration?
```
data Foo(x is int, y is str)
```

**Comment by evhub** [comment]
@arnauorriols This is now live on `coconut-develop` (just `pip install -U coconut-develop`)! Also check out the docs on it [here](https://coconut.readthedocs.io/en/develop/DOCS.html#match-data).
