### ISSUE TITLE
Handle addpattern on a non-pattern-matching function in a useful way

### ISSUE THREAD

**Issue by pavelbraginskiy** [evhub/coconut#496]
Currently, if you have an ordinary function and you either use `@addpattern` or the `addpattern def` keyword on it, it doesn't actually yield any useful result:

```python
def f(n) = [n]
addpattern def f(n, m) = [n,m] # Attempting to call f with two arguments will intead throw an error.
```

Of course, one can use the `match def` keyword to tell Coconut this is a pattern-matching function, however, it's quite easy to forget to add it, especially when the function was originally defined without a second pattern for it in mind. The `addpattern` decorator should be able to detect that `f` is not already a pattern-matching function, and either:
 - Convert `f` to a pattern-matching function, allowing you to elide the `match` keyword altogether,
 - Or, if that's not actually possible for some reason, at least emit a warning/error that immediately clarifies the issue (*addpattern should not be used with non-pattern-matching functions!*) instead of a less obvious error about a wrong number of arguments that doesn't reveal the underying issue later down the line.

**Comment by pavelbraginskiy** [comment]
To determine if a function is pattern-matching or not, perhaps it would be necessary to add a flag to all such functions: `f._is_pattern_matching = True`.

**Comment by m-burst** [comment]
Turns out this doesn't work on Python 2, because `functools.wraps` doesn't set the `__wrapped__` attribute there. I'll take a closer look on what can be done here.

**Comment by evhub** [comment]
@pavelbraginskiy This should now be working on `develop`!

**Comment by evhub** [comment]
@pavelbraginskiy Note that I've changed it so the warnings are only added when `--strict` is passed.
