### ISSUE TITLE
[Idea] Run coconut directly as a .py file

### ISSUE THREAD

**Issue by yangyangxcf** [evhub/coconut#497]
I'm a newbie at coconut, I wonder if I could write coconut code directly in .py file and run it with python.
That is possible using like `# coding: coconut`, as what [dropbox/pyxl](https://github.com/dropbox/pyxl) does.
It makes it more convenient if you don't care a little bit slower in importing but avoid all troubles about compiling.
I can help if many people think it a good idea.

**Comment by pavelbraginskiy** [comment]
You can use `coconut-run` to directly run `.coco` files.

On *nix you can add `#!/usr/bin/env coconut-run` and on Windows you can make a filetype association.

**Comment by evhub** [comment]
@yangyangxcf In addition to the options @pavelbraginskiy mentioned, Coconut also supports [automatic compilation](https://coconut.readthedocs.io/en/master/DOCS.html#automatic-compilation) where your imports will automatically be compiled from Coconut to Python if you `import coconut.convienence` first. I do like the idea of an encoding header, though--that's definitely a possibility that could be implemented in addition to the other options that already exist. I'm not sure if it's actually better than the existing options, though.

**Comment by yangyangxcf** [comment]
@pavelbraginskiy @evhub Thanks for your advice!
I also find that `coconut --watch` can do recompiling on change, so three options now :)
It seems automatic compilation is most approaching to what I want, I don't need to compile anything, just `import my_coconut_code` works.
The differences I can come up with are
- a codec can be preinstalled so `import coconut.codec.reg` (similar to `import coconut.convenience`, but does the registry thing) can be omitted (optional, of course), 
- no extra files in your directory (automatic compilation does create .py files besides the .coco files you write)

I'm not sure neither if using encoding can be better, but as @evhub said, that makes another option, so I will try to implement it and create a new pull request.
Any further discussion or suggestions or help or other replies (spamming excluded) are welcome :)

**Comment by evhub** [comment]
@yangyangxcf I think even in the encoding header approach we would still want to create extra files in the directory, if only for the simple purpose of caching the compiled code so that future imports aren't slowed down by the compilation process.

**Comment by evhub** [comment]
As of `coconut-develop>=1.5.0-post_dev61`, Coconut now supports `# coding: coconut` headers in `.py` files imported after `coconut.convenience` (though nothing is cached, so I'd still recommend automatic compilation instead in most cases).
