### ISSUE TITLE
Installation causes pygmentize command to fail with error

### ISSUE THREAD

**Issue by julius383** [evhub/coconut#499]
For some reason having coconut installed on my system causes the `pygmentize` command to fail even when trying to highlight non-coconut files. The following error is displayed
```
*** Error while highlighting:
pkg_resources.VersionConflict: (prompt-toolkit 2.0.8 (/usr/lib/python3.7/site-packages), Requirement.parse('prompt_toolkit<.2,>=1'))
   (file "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve)
*** If this is a bug you want to report, please rerun with -v
```
I did some digging and the problem seems to be in the `requires.txt` file in the `egg-info` directory of the cocunut installation, the full path on my system is `/usr/lib/python3.7/site-packages/coconut-1.4.0-py3.7.egg-info/requires.txt`. The specific line seems to be under the requirements for `:python_version>=2.7`
```
[:python_version>='2.7']
pygments>=2.2
prompt_toolkit<.2,>=1
```
pygmentize seems to work when I `sudo -e` the file and change the line to `prompt_toolkit>=1`. The python3 and python2 versions of prompt_toolkit are installed as dependencies for ipython and ipython2 if that matters and the system I am on is 64-bit Arch Linux. I also tried installing coconut through pip and from the aur including trying the develop branch but only the above edit fixes the problem. An issue that may be related is filed in the pygments bug tracker by a different user [Issue #1449](https://bitbucket.org/birkenfeld/pygments-main/issues/1449/an-unhandled-exception-occurred-while). It seems something may be going wrong with the parsing of version information to strings for the `requires.txt` file. Let me know if you need more info.

**Comment by evhub** [comment]
@julius383 If you `pip uninstall coconut` and `pip install -U coconut-develop` instead, does that work?

**Comment by julius383** [comment]
Yes it works perfectly now
