### ISSUE TITLE
Design a Coconut logo

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#50]
Website should be rewritten to not be the readme.

**Comment by evhub** [comment]
All syntax highlighting should be done with inline html, and all references to concepts should be linked to their documentation entry.

**Comment by evhub** [comment]
Should also include logo and pictures.

**Comment by evhub** [comment]
Add an FAQ to answer common questions, including why the name Coconut was chosen.

**Comment by ankostis** [comment]
But not addressing the "logo" suggestion :-)

**Comment by evhub** [comment]
@ankostis A logo would be awesome, but I don't have the skills to make one. Hopefully, at some point, I'll find someone who does.

**Comment by mr-ubik** [comment]
@evhub I have skilled designers friends, if you have a concept or an idea for the logo I could ask them.

**Comment by evhub** [comment]
@mr-ubik That would be great! I'm in talks with a company that's using Coconut as their primary language, and they may be willing to fund something like that. I'm not a graphic designer, so I will defer to people who actually are, but possible things to incorporate include: coconuts, pythons, and lambdas. Some examples of the sorts of things I'm looking for: a coconut colored like the Python logo, a coconut with a Python-logo-like python in it, or a Python-logo-like python in the shape of a lambda. Really, though, I'm very open to any possibility!

**Comment by davidjamesknight** [comment]
@evhub I'd like to take a stab at this! I wouldn't recommend riffing on Python's logo, though. At the end of the day, Coconut is a separate language and deserves its own unique brand identity. Look at Elm, TypeScript, and PureScript; they are to JS as Coconut is to Python, but their logos are completely distinct from JS's.

Also, using Python's colors or stylized snakes would raise IP concerns. The logo can contain a nod to Python, but the visual elements need to be distinct. Crystal walks that fine line well; its logo pays homage to Ruby without being derivative.

**Comment by davidjamesknight** [comment]
Here's our version in a few color variations:
<img width="524" alt="screen shot 2018-10-14 at 09 41 40" src="https://user-images.githubusercontent.com/13210154/46917451-7b450e00-cf95-11e8-9916-c197fdf1728c.png">

**Comment by davidjamesknight** [comment]
We started with coconut halves (as in Holy Grail), but it looked like a food brand, so then we tried a coconut with a straw, which in turn evolved into this minimalist design. If you like this concept, we can tweak the line weight or try a different font.

**Comment by ggabogarcia** [comment]
Hello, I would like to join this request, that is why I made these two proposals. The concept is the same in both but executed in a different way. I wanted to represent the lambda inside a circle which represents the shape of a coconut. I hope you like it. :smiley: 
# 
### First proposal
# 
![proposal two](https://user-images.githubusercontent.com/35750428/47676976-f577b400-db8b-11e8-8c5b-bf6f9934e5db.jpg)
# 
### Second proposal
# 
![proposal one](https://user-images.githubusercontent.com/35750428/47677027-193afa00-db8c-11e8-9a81-1a16bbc12c07.jpg)

**Comment by ankostis** [comment]
A flat prospective design... can you reroute the path so it does not produce 3 lines on the left leg of λ?
(my apologies for intervening)

**Comment by ggabogarcia** [comment]
Comments are welcome :) Of course, I could eliminate it, but maybe the aspect will change. I will do the tests.

**Comment by evhub** [comment]
@tropnikova @davidjamesknight @ggabogarcia Wow! This is a really incredible response. Thanks so much everybody for putting your time and effort into this. I'll need some time to think about what design(s) I want to use, but I'll post here soon with my plan for the designs and distributing bounties.

**Comment by timka** [comment]
I think it may be just a vector open coconut (like the bottom left one bellow) while the straw's bending angle symbolizes the lambda. Another straw or whatever may form the other leg of the lambda. Or maybe just one leg is enough? What about a green coconut?

![image](https://user-images.githubusercontent.com/85762/97772168-78ee8600-1b55-11eb-82b4-3b371b679a4a.png)

**Comment by JeffreyBenjaminBrown** [comment]
One leg of lambda is enough for Haskell, which uses a backslash for
anonymous functions.

**Comment by eindiran** [comment]
> One leg of lambda is enough for Haskell
Except for in the logo, where 3 legs and 2 stems were apparently required 😉

**Comment by carloocchiena** [comment]
stumble on the repo out of curiosity, 
saw the issue, got this minimalist-negative idea.

![image](https://user-images.githubusercontent.com/57464184/143056521-14e4d92b-29c6-408e-b45a-b7e9f60ebc98.png)

**Comment by JeffreyBenjaminBrown** [comment]
The lambda-palm and the minimalist one are my favorites.

**Comment by evhub** [comment]
Finally decided to get around to this. Lots of great suggestions here—thanks everybody! I think I'll go with @atropnik's lambda palm. Should be up on the website now.

@atropnik Since this issue had a bounty on it when you worked on it, you're still welcome to claim that if you want—just follow the instructions [here](https://github.com/evhub/coconut/raw/gh-pages/favicon-32x32.png).
