### ISSUE TITLE
Pyparsing version dependency

### ISSUE THREAD

**Issue by paulie-g** [evhub/coconut#501]
Is the strict version dependency on pyparsing necessary? Installing coconut to try it out (via a distro package) managed to break pygments for me (pkg_resources version mismatch errors). It can be worked around of course, but a) the error messages produced didn't identify the source of the problem and required some digging that requires clue > 0 and b) breaking users' systems is generally considered a faux pas.

I don't mean this to come across negatively - coconut is certainly very cool - and no harm was done in my case. I understand you might not want to support installing via distro packages, or non-venv package mgmt with a distro/pip mix. Viewed in that light, this could be considered a problem in that particular AUR package. With that said, it's most easily fixed upstream as the problem is likely to be ubiquitous, distro pkg/pip mixing is commonplace, and even on a purely pip-managed installation this would require a pyparsing downgrade. I don't know enough to confidently suggest a solution, but perhaps allowing higher versioned pyparsing and printing a warning about a particular version being desirable would be a workable resolution?

**Comment by evhub** [comment]
@paulie-g Unfortunately, Coconut is very highly integrated with pyparsing such that pyparsing version changes will often break Coconut. However, an easy fix to this is just to use [cpyparsing](https://github.com/evhub/cpyparsing) instead, since Coconut will always use cpyparsing instead of pyparsing if it is available, so you can have cyparsing on the version Coconut needs and pyparsing on the version you need for everything else. In fact, maybe the best solution to this issue, which would also make Coconut run much faster for the "default" user who just does `pip install coconut` would be to use cpyparsing instead of pyparsing by default.

**Comment by paulie-g** [comment]
Understood. I figured there was a reason. 

 However, my main point is that currently:
 1. If you install coconut with pip and other things that need pyparsing with pkg manager, coconut install will downgrade your pyparsing and possibly break other things
 2. If you install coconut with pkg manager, it will break pygments because pkg_resources will now throw an exception about version inconsistencies

The kludgy, but possible, solution to the first issue is to install cpyparsing and coconut with --no-deps, which is what I've now done. I could've equally well used pipsi presumably. I'm not sure what the solution to 2 is as long as you keep hard version-deping on pyparsing - packages will keep breaking things. Switching to cpyparsing by default will require packagers to package cpyparsing as well (currently not in AUR), which is not ideal, but at least it'll stop the pygments breakage.

**Comment by pavelbraginskiy** [comment]
@evhub I *have* `cpyparsing` installed, but running `coconut` still fails with this error until I downgrade pyparsing:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyparsing 2.4.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('pyparsing<2.3.2,>=2.3.1'), {'coconut-develop'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/coconut", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyparsing<2.3.2,>=2.3.1' distribution was not found and is r
```

**Comment by evhub** [comment]
@paulie-g @auscompgeek @pavelbraginskiy I have switched `coconut-develop` over to `cPyparsing` by default on CPython (Coconut will still use `pyparsing` on PyPy). If you `pip install -U coconut-develop`, it should fix all of the above problems!
