### ISSUE TITLE
Add flag to disable wrapping type hints in strings

### ISSUE THREAD

**Issue by QuestofIranon** [evhub/coconut#514]
When compiling to Python with target set to any version above 3.x the type hints for functions and variables get wrapped in single quotes. This breaks functionality with some libraries which rely on type hints such as pydantic.

I first noticed it with `Coconut: Version 1.4.1 [Ernest Scribbler] running on Python 3.7.4` but tested it out on the online interpreter with Python `3.3` `3.4` `3.5` and `3.6` with the same results.

Based on the documentation at https://coconut.readthedocs.io/en/master/DOCS.html#enhanced-type-annotation it looks like it should be possible to use standard `3.5` type annotation syntax. 

For context I was originally testing to see if I could use coconut with fastapi.

**Comment by evhub** [comment]
From Coconut's documentation:

> Since not all supported Python versions support the typing module, Coconut provides the TYPE_CHECKING built-in for hiding your typing imports and TypeVar definitions from being executed at runtime. Furthermore, when compiling type annotations to Python 3 syntax, Coconut wraps annotation in strings to prevent them from being evaluated at runtime.

For type checkers such as MyPy, wrapping type hints in strings is considered best practice for preventing them from being evaluated at runtime, though it seems like other type checkers don't always follow suit. Possibly Coconut could add a compiler flag to turn that feature off?

**Comment by QuestofIranon** [comment]
That seems like a reasonable compromise. Pydantic is a runtime type enforcer (mainly used to evaluate user provided data) so it's more of use-case difference instead of a contradiction to best practices.
