### ISSUE TITLE
Question: can coconut be run with the ipython repl?

### ISSUE THREAD

**Issue by javadba** [evhub/coconut#516]
As in the title:  the vanilla python repl is too primitive so I use ipython.  But then coconut needs a special compiler pass so i'm not clear if/how to use ipython to get coconut support.

**Comment by sollyucko** [comment]
Have you tried Coconut's built-in REPL? You can start it with `coconut` or `coconut -i` (prefix with `python -m `  if your environment setup requires that)

**Comment by javadba** [comment]
Yes I did: it does not have `ipython` extras that I look for in doing dev: the base `python` repl is too bare bones.  A more important question:  how can we use the existing toolchains with coconut?  I completely depend on debugging within Pycharm: but given coconut requires its own internal compiler it is unclear how running/debugging can be done within an IDE.  Any guidance on that point?  Thanks !

**Comment by sollyucko** [comment]
Actually, it looks like `coconut --ipython` or `coconut --jupyter` should work. ~~Ok. What sort of things are missing? Also, I think `%coconut` might work for running Coconut in IPython, but I'm not really sure.~~

As for debugging, I think the currently best solution is to use the flag that adds line numbers (`-l`, `--line-numbers`, `--linenumbers`) or the full lines (`-k`, `--keep-lines`, `--keeplines`). I do agree that it should be improved,

**Comment by javadba** [comment]
Is my question about the probable inability to run/debug coconut within an IDE correct? Or is it possible to say do something like change the `python` launch path/command within `pycharm` so that it instead points to coconut ? Would the line numbers then be shifted due to statements that coconut would insert?

**Comment by javadba** [comment]
for the `coconut --ipython` that is installing the kernel but it is not for running the `ipython` repl afaict:

```
coconut --ipython
Coconut: Successfully installed Coconut Jupyter kernel.

```

**Comment by evhub** [comment]
@javadba The command you want is `coconut --ipython console` (see [here](https://coconut.readthedocs.io/en/master/DOCS.html#ipython-jupyter-support)). As for IDE support, that's going to depend on the IDE and what exactly it requires. I don't really use Pycharm, so I don't know what it would need from Coconut for debugging to work, though if it just needs a command to run a script and print errors with line numbers, you could try giving it `coconut --line-numbers --quiet --run`. Also, if you just want syntax highlighting, you can take a look at the documentation [here](https://coconut.readthedocs.io/en/master/DOCS.html#syntax-highlighting).
