### ISSUE TITLE
working with Google Colab

### ISSUE THREAD

**Issue by zimzion** [evhub/coconut#518]
Hi!

I'm trying to find out how to run coconut environment in Google Colab. If there is anyone who succeeded in the work, please share your experience. 
Thank you in advance.
Jin

**Comment by Samrose-Ahmed** [comment]
For anyone, was pretty simple with the jupyter integration, [example notebook](https://colab.research.google.com/drive/1y5PthNvzL869zAxO0QGlLRsu4lC0cwTx).
