### ISSUE TITLE
question about data keyword

### ISSUE THREAD

**Issue by zimzion** [evhub/coconut#525]
Hi,

Here is my code
```
data StaticMapping(iterable) from Mapping:
    def __new__(cls, iterable) =
        _data = tuple(iterable)
        _keys = tuple(sorted(key for key, _ in _data))
        makedata(cls, _data, _keys)
```
When running this code, the compiler complains about the different number of parameters. How can I solve this problem?

Thank you!
Sangjin

**Comment by sollyucko** [comment]
1. Could you please put 3 backticks (<code>```</code>) before and after your code to make it display properly?
2. Could you please post your exact error message?

**Comment by evhub** [comment]
@zimzion It's complaining that the `StaticMapping` base constructor being called by `makedata` only takes one argument since you wrote it as `data StaticMapping(iterable)`. Instead, you should do
```python
data StaticMapping(data, keys) from Mapping:
    def __new__(cls, iterable) =
        data = tuple(iterable)
        keys = tuple(sorted(key for key, _ in data))
        makedata(cls, data, keys)
```
