### ISSUE TITLE
`f 'a'` and `def f(0) = 'a'` not working

### ISSUE THREAD

**Issue by vietspaceanh** [evhub/coconut#526]
Calling a function like this `f x y` (which is `f(x,y)`) does not work for many builtin functions (`print`, `sum`, `list`, `tuple`, `int`...) but works for functions imported from libraries, for example `np.random.rand` or `np.add`. 

Being able to `print "some string"` is quite cool and it's a thing I miss from Python 2. I don't know if the feature `f x y` has not been completely done or there are some limitations which make calling builtin functions that way not possible?

Edit: I have just realized that `string`s are the cause of the problem, not builtin functions. `pow 2 3` is fine. 
Also, `def f(0) = 'a'` causes `parsing failed` while `def f(0): return 'a'` is fine.
So is there any restriction about `string` that I'm missing?

**Comment by evhub** [comment]
Strings are not purposefully not allowed in implicit function application. From the docs:

> Supported arguments to implicit function application are highly restricted, and must be either variables/attributes or **non-string** constants (e.g. `f x 1` will work but `f x [1]`, `f x (1+2)`, and `f "abc"` will not). Strings are disallowed due to conflicting with [Python's implicit string concatenation](https://stackoverflow.com/questions/18842779/string-concatenation-without-operator).

However, `def f(0) = 'a'` not working is definitely a bug—I'll look into it and see if I can figure out what's wrong there.

**Comment by evhub** [comment]
@vietspaceanh Strings are not purposefully not allowed in implicit function application. From the docs:

> Supported arguments to implicit function application are highly restricted, and must be either variables/attributes or **non-string** constants (e.g. `f x 1` will work but `f x [1]`, `f x (1+2)`, and `f "abc"` will not). Strings are disallowed due to conflicting with [Python's implicit string concatenation](https://stackoverflow.com/questions/18842779/string-concatenation-without-operator).

However, `def f(0) = 'a'` not working is definitely a bug—I'll look into it and see if I can figure out what's wrong there.

**Comment by evhub** [comment]
@vietspaceanh `def f(0) = 'a'` should now be fixed on `coconut-develop`. Just `pip install coconut-develop` to get the fix.

**Comment by narfanar** [comment]
Quite unrelated but:

How out of the question is restricting bad Python practices in Coconut? From this issue: implicit string concatenation.

**Comment by evhub** [comment]
@narfanar Coconut [already restricts some bad Python practices when `--strict` is passed](https://coconut.readthedocs.io/en/master/DOCS.html#strict-mode), and I definitely think it would be reasonable to add implicit string concatenation to that list, but I wouldn't want to disallow it entirely so long as it remains a part of Python. Thus, the conflict with implicit function application will remain. Implicit function application isn't meant to be general-purpose, though—list literals and parentheses have conflicts as well, for example. In general, if you want a functional way to do function application in Coconut you should be using [pipeline operators](https://coconut.readthedocs.io/en/master/DOCS.html#pipeline) not implicit function application.
