### ISSUE TITLE
Add assignment operator to assign values in the middle of pipelines

### ISSUE THREAD

**Issue by vietspaceanh** [evhub/coconut#529]
For example, we have this pipeline:

```python
3 |> x -> x**2 |> y -> y/3 |> print
```

which gives us the result `3 |> 9 |> 3 |> 3`. Sometimes we may want to get the value in the middle, say `9` in the above example and assign it to a variable so we can use it later (e.g. debugging).

I don't know if something like the following possible?

```python
3 |> x -> x**2 =: a |> y -> y/3 |> print$(a, ?)
# 9, 3
```
or
```python
3 |> x -> x**2 => a |> y -> y/3 |> print$(a, ?)
# 9, 3
```

Thank you `evhub` and all the contributors for making a great language. Piping and compositing really make Python more fun =D

**Comment by sollyucko** [comment]
Couldn't you use `:=`?

```
3 |> x -> a := x**2 |> y -> y/3 |> print$(a, ?)
```

**Comment by vietspaceanh** [comment]
> Couldn't you use `:=`?
> 
> ```
> 3 |> x -> a := x**2 |> y -> y/3 |> print$(a, ?)
> ```

I got `parsing failed` in both Python 3.7 and 3.8.

**Comment by sollyucko** [comment]
From Python or Coconut? What is the full error message do you get?

If the message is from Coconut, it could be that Coconut just hasn't implemented `:=` yet.

**Comment by eindiran** [comment]
Note to anyone in the future trying to use the assignment operator `:=`: This only works in Python 3.8, so you need to pass the `--target 38` to Coconut. Then make sure your interpreter is 3.8+ or you'll end up with:
```
  File "/usr/local/lib/python3.6/dist-packages/coconut/command/util.py", line 167, in exec_func
    exec(code, glob_vars)
  File "<string>", line 1
    (lambda x: (lambda y: (_coconut_partial(print, {0: a}, 2))(y / 3))((a := x**2)))(3)
                                                                                                             ^
SyntaxError: invalid syntax
```

**Comment by eindiran** [comment]
See issue #489.
