### ISSUE TITLE
coconut --jupyter console ignores ipython config

### ISSUE THREAD

**Issue by bj0** [evhub/coconut#530]
If I modify the IPython config options in `~/.ipython/profile_default/ipython_config.py`, It effects the normal `ipython` terminal, but the coconut version is unaffected.  The file is still loaded (errors are thrown), but options are not applied.

I would like to use coconut ipython terminal but customize options (like the prompt).  Is this possible?

**Comment by evhub** [comment]
@bj0 `coconut --jupyter console` just runs `jupyter console --kernel coconut` under the hood—if you run `jupyter console --kernel coconut` directly, do you get the same error? Also, can you run `coconut --verbose --jupyter console` and paste the output?

**Comment by bj0** [comment]
Ah Ok, it looks like `jupyter console` doesn't use the same configs as `ipython` for some reason??  It has it's own config in `~/.jupyter`.  Adding options in here looks like it affects coconut
