### ISSUE TITLE
Compile Coconut into Lisp/Scheme code?

### ISSUE THREAD

**Issue by DonaldTsang** [evhub/coconut#532]
This might sound weird at first, but from seeing some of the claims, Lisp/Scheme is faster than Python, and is very close to C/C++, JS/TS, Go, Java and Swift/C#/Kotlin (these 3 are all platform-specific).
Is it possible to use Python's typing system, and force type checks into functions, to allow programs to compile to Lisp/Scheme for increased speed? Python is known to be as slow as Ruby and Perl.

**Comment by sollyucko** [comment]
If CPython (the standard implementation) is too slow, you could try PyPy (includes a JIT compiler) or Cython (compiles to C).

**Comment by DonaldTsang** [comment]
Has anyone tried benchmarking Coconut in PyPy or Coconut compiled in Cython, with Lisp/Scheme and C/C++/Go?
Right now I am trying to see if functional programming allows for a speedup in Pythonic performance.

**Comment by sollyucko** [comment]
You could try benchmarking it yourself. Also, compiling Coconut to Lisp/Scheme would be a huge project: you'd need to be able to translate all of Python's syntax, and have a compatible standard library. Why do you need to use Coconut? Solely for type checking?

**Comment by DonaldTsang** [comment]
Theoretically speaking, Lisp is a high-level language that is both fast and non-verbose. Go, Nim and Crystal all attempted to be Python-of-the-field without being explicitly Pythonic, which Coconut is.

**Comment by sollyucko** [comment]
What makes a language "Pythonic"?

**Comment by evhub** [comment]
@DonaldTsang Coconut is highly wedded to Python—significantly more so than any of the other languages you mention—as Coconut is a strict superset of Python. As a result, Coconut does not and likely will never compile to anything other than Python. If you are interested in performance, as @sollyucko mentioned you can use something like PyPy or Cython, or also see [these tips on getting Coconut code to run faster](https://coconut.readthedocs.io/en/master/FAQ.html#i-want-to-use-coconut-in-a-production-environment-how-do-i-achieve-maximum-performance).
