### ISSUE TITLE
Integration with Sublime Text/Hermes or Atom/Hydrogen

### ISSUE THREAD

**Issue by zhenyulin** [evhub/coconut#538]
Instead of using Jupyter notebook, I'm using Hermes inside Sublime Text to invoke python code cells, which hugely leveraged all the IDE benefits while giving me the essentials of Jupyter notebook. The plugin is transported from Hydrogen in the Atom ecosystem.

I was wondering if there is an existing way to make the coconut kernel visible to Hermes?

Integrate Python to Hermes, I pretty much did the following:
https://stackoverflow.com/questions/51854996/sublime-text-3-jupyter-interaction-via-hermes

**Comment by zhenyulin** [comment]
the temporary solution doesn't need to be a script, and can just be a documented way to add kernel__spec to jupyter

https://ipython.readthedocs.io/en/stable/install/kernel_install.html

**Comment by zhenyulin** [comment]
temporary solutions:
- find your local icoconut_kernel_dir (e.g. <some root>/site-packages/coconut/icoconut/coconut)
- `jupyter kernelspec install <icoconut_kernel_dir> --replace` or just copy `coconut/icoconut` folders to `/usr/local/share/jupyter/kernels/`

**Comment by evhub** [comment]
@zhenyulin If you just run `coconut jupyter` it will automatically install the Coconut kernel—if that's all you need you shouldn't have to do it manually; that command should do it for you.
