### ISSUE TITLE
Require explicit parameter to specify output file

### ISSUE THREAD

**Issue by dryprogrammer** [evhub/coconut#541]
Has coconut ever overwritten other .coco files when you tried to compile your code?

If I have `file1.coco` and `file2.coco` in a folder, `coconut *.coco` will overwrite the other .coco files as python output:
```
Compiling        file1.coco ...
Compiled to      file2.coco .
```

`coconut file1.coco file2.coco` will do the same. I know adding additional parameters like `-o` is a bit of a hassle, but it may be worth it, if other users have made this mistake.

I've made both the above mistakes, but fortunately I had a commit from last night, and I just vimdiff the old compiled `file2.py` file to recover today's changes.

Please share if you have made this silly mistake as well.

**Comment by evhub** [comment]
@dryprogrammer The problem with `coconut file1.coco file2.coco` is a fair point, though `coconut *.coco` simply shouldn't work as Coconut doesn't handle grep strings like that (just pass the directory instead). Regardless, `coconut-develop` should now throw an error if you try to compile to a `.coco` file. You should be able to `pip install -U coconut-develop` to get the new version.
