### ISSUE TITLE
Coconut formal Grammar

### ISSUE THREAD

**Issue by darleybarreto** [evhub/coconut#546]
Is there any file with a formal specification of the grammar, like an EBNF or Peg syntax? I want to build a simple compiler for a small subset of coconut, so the specification of the grammar would be great start.

Thanks in advance.

**Comment by evhub** [comment]
@darleybarreto Coconut's grammar is specified using parser combinators from [`pyparsing`](https://github.com/pyparsing/pyparsing) (a recursive descent parser) in [`coconut.compiler.grammar.Grammar`](https://github.com/evhub/coconut/blob/master/coconut/compiler/grammar.py#L705).
