### ISSUE TITLE
Add coconut --annotation command

### ISSUE THREAD

**Issue by phillui-37** [evhub/coconut#549]
# Issue Type
Feature Request

# Description
Add coconut command option for compiling
- `--target (2/3)`: choose different policy on compiling to different python platform (if coconut has)
- `--annotation`: use Python 3 type annotation (`typing` module) instead of comment type hint
    - dynamic injection of `__annotations__` is also an option

# Request Reason
- Some libraries rely on runtime reflection lib like inspect, the lack of annotation after compilation greatly affects the ability of these libraries.
- Python 2's support reached its EOL. The target option can help current development focus on Python 3 and make use of Python 3 features

**Comment by phillui-37** [comment]
There should be other runtime behaviour will be affected due to lack of metadata after compiling. I think they should have the command option also.

**Comment by evhub** [comment]
What about the [existing `--target` options](https://coconut.readthedocs.io/en/master/DOCS.html#allowable-targets) is insufficient for your use case?

**Comment by phillui-37** [comment]
Thx a lot! I miss it from documentation!

**Comment by evhub** [comment]
Coconut will also do actual type annotations when the target supports them, so everything here already exists.
