### ISSUE TITLE
Respect NOQA comments

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#556]
Should suppress `--strict` warnings.

**Comment by PhanatosZou** [comment]
Hi, I'm new here and would love to take this issue. But I may need some help. Is there any advice on getting started? Any response will be appreciated!

**Comment by eindiran** [comment]
I think most of the changes should be to `compiler/compiler.py`, and potentially to `compiler/util.py`.

Take a look at the `make_err` and `strict_err_or_warn` methods, places where `CoconutStyleError` or `CoconutSyntaxError` are raised, and places where `self.strict` is checked. In case I am missing something, it is probably worth grepping through the whole repo for usages of `strict`.

For an example of how end-of-line comments are handled, see the function `split_comment` in `compiler/util.py`. `split_comment` returns a 2-tuple of base line and comment: the comment bit can be used to see if it matches the pattern of a `noqa` comment.

**Comment by PhanatosZou** [comment]
@eindiran Thanks for your quick reply! I'll get started based on information you provided.

**Comment by evhub** [comment]
Hmmm... I'm just realizing that the problem with this is that comments don't get added to `self.comments` until `comment_handle` is called, which only happens at the end of the line when the parser hits the comment. As a result, addressing this issue might be somewhat more complicated than I thought.

**Comment by evhub** [comment]
I think the solution to this has to be to store strict errors/warnings rather than raising them immediately until `Compiler.endline_handle` is hit or parsing finishes, at which point stored errors can either be raised or suppressed based on whether a NOQA comment exists in `Compiler.comments` at that point.

**Comment by evhub** [comment]
As of `coconut-develop>=2.0.0-post_dev23`, NOQA comments will now work to suppress unused import warnings on `--strict` mode.
