### ISSUE TITLE
Future Pattern Matching compatibility with Python

### ISSUE THREAD

**Issue by capissimo** [evhub/coconut#573]
In October, 2021 a new 3.10 release of Python is scheduled. It will feature new pattern matching keywords - match and case whose behaviour is different from that of Coconut's. What measures wil be taken to resolve this problem? Do you plan to create a regular compiler in the future instead of transpiler?

**Comment by evhub** [comment]
See #558. Currently, `coconut-develop` has full support for Python 3.10 pattern-matching syntax and behavior as well as full backwards-compatibility with previous versions of Coconut. This will be released with Coconut v1.6.0.

Coconut handles the differences between Python and Coconut pattern-matching behavior as follows:
- Coconut warns you whenever you would use a pattern-matching construct with different behavior in Python vs. Coconut,
- such warnings provide an alternative syntax to explicitly state what behavior you're looking for, and
- Coconut selects what default behavior to use based on whether you used Coconut-style pattern-matching syntax or Python-style pattern-matching syntax, thus preserving full compatibility with both Python and Coconut.

As for compiling to something other than Python source, no, there are no plans for that. Python source is the only possible compilation target for Coconut that supports the ability to produce universal code that runs the same on all Python versions—such behavior is not possible with Python bytecode.
