### ISSUE TITLE
Improve interpreter auto-completion

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#575]
See [`prompt_toolkit` auto-completion](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html).

**Comment by tbsexton** [comment]
Another option that embraces type-annotations is the [`typer-cli`](https://typer.tiangolo.com/typer-cli/) component of `Typer`. Been very useful for us, though we're already using Pydantic/FastAPI to some degree.
