### ISSUE TITLE
Type inference for Wildcard Partials

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#581]
Inspired by [pfun's documentation](https://pfun.dev/useful_functions/#curry), I tested Coconut's type annotation behavior when currying functions. Worked pretty great!

Default currying/partials: 
```python
from inspect import signature
def fun(a:int, b:str)->str = str(a)+b

>>> signature(fun)
<Signature (a: 'int', b: 'str') -> 'str'>

>>> signature(fun$(1))
<Signature (b: 'str') -> 'str'>

>>> signature(fun$(1, "2"))
<Signature () -> 'str'>
```

However, using the syntax for partials in alternate order:
```python
>>> signature(fun$(?, "2"))
<Signature (*args, **kwargs)>
```
This loses the information we might have needed for e.g. type checking or dependency injection.

**Comment by evhub** [comment]
Currently, using [`reveal_type`](https://github.com/evhub/coconut/issues/574) on `coconut-develop`, I can see the proper return type:
```python
> co --mypy
Coconut Interpreter:
(enter 'exit()' or press Ctrl-D to end)
>>> def f(x: int, y: str) -> str = y * x
>>> a = f$(?, "a")
>>> reveal_type(a)
<function f at 0x0000011959E0C820>$(?, 'a')
<string>:35: note: Revealed type is '__coconut__._coconut_partial[builtins.unicode*]'
>>> a(10) |> reveal_type
'aaaaaaaaaa'
<string>:37: note: Revealed type is 'builtins.unicode*'
```
but it can't detect improper argments:
```
>>> dub = f$(2, ?)
>>> dub(3)
6
>>> reveal_type(dub)
<function f at 0x00000242563575E0>$(2, ?)
<string>:43: note: Revealed type is '__coconut__._coconut_partial[builtins.unicode*]'
>>> 10 |> dub |> reveal_type
20
<string>:45: note: Revealed type is 'builtins.unicode*'
```

**Comment by evhub** [comment]
@tbsexton Looking into this a bit, I don't think it's really possible to get MyPy to do any better than the above. I could still try to make the `signature` match, though I'm not sure what the use case would be for that—it'd be runtime-only, so no effect on static type checkers.

**Comment by tbsexton** [comment]
@evhub ah, ok makes sense. Actually I wonder if there is a way to use the more classic "flip" function. Current behavior: 

```
from typing import TypeVar
from inspect import signature 

Ta = TypeVar("Ta")
Tb = TypeVar("Tb")

def flip(func: (Ta, Tb) -> Tc) -> (Tb, Ta) -> Tc =
    (x, y) -> func y x
    
def f(x: int, y: str) -> str = y * x

f |> flip |> signature
>>> <Signature (x, y)>
```

That's not quite right, and I'm confused as to why mypy doesn't use the type sig of `flip`?

**Comment by evhub** [comment]
@tbsexton `signature` just does runtime introspection—if you want to get the MyPy type, you have to use [`reveal_type`](https://github.com/evhub/coconut/issues/574). See:
```python
> coconut --mypy
Coconut Interpreter:
(enter 'exit()' or press Ctrl-D to end)
>>> from typing import TypeVar
>>> Ta = TypeVar("Ta")
>>> Tb = TypeVar("Tb")
>>> Tc = TypeVar("Tc")
>>> def flip(f: (Ta, Tb) -> Tc) -> (Tb, Ta) -> Tc =
     (x, y) -> f y x

>>> def f(x: int, y: str) -> str = y * x
>>> f |> flip |> reveal_type
<function flip.<locals>.<lambda> at 0x000001F645BFAB80>
<string>:46: note: Revealed type is 'def (builtins.unicode*, builtins.int*) -> builtins.unicode*'
>>>
```

**Comment by tbsexton** [comment]
Perfect!
