### ISSUE TITLE
Add flatten built-in

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#582]
Moved from discussion in #105.

**Comment by evhub** [comment]
An enhanced version of `chain.from_iterable` is now available as a built-in under the name `flatten` with added support for `reversed`, `len`, `repr`, `in`, `.count()`, `.index()`, and `fmap`.

**Comment by aananko** [comment]
@evhub, looks like there is something personal between you and flatmap :)

Anyway, the final result is completely reasonable, imho - `flatten..map` is not much longer than `flatmap`, and `flatten..map` or `map$(...) |> flatten` should have the same readability as (or even better than, depending on the reader's background) `flatmap`.
