### ISSUE TITLE
`flatten` treats iterable-once objects not carefully enough

### ISSUE THREAD

**Issue by aananko** [evhub/coconut#583]
```python
>>> (range(2) for _ in range(2)) |> flatten |> list
[]
```
but
```python
>>> (range(2) for _ in range(2)) |> flatten |> iter |> list
[0, 1, 0, 1]
```
Looks like `list()` constructor does notice `__len__` and calls it first, and `flatten.__len__` consumes the generator.

**Comment by evhub** [comment]
Good catch! I thought I tested that case, but I guess not.

**Comment by aananko** [comment]
Your response time is incredible, thanks!
