### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'

### ISSUE THREAD

**Issue by Gurkenglas** [evhub/coconut#585]
```
gurkenglas@Gurkenglas-PC:~/.local/lib/python3.9/site-packages/lenses$ coconut --ipython notebook
Traceback (most recent call last):
  File "/home/gurkenglas/.local/lib/python3.9/site-packages/coconut/command/command.py", line 293, in handling_exceptions
    yield
  File "/home/gurkenglas/.local/lib/python3.9/site-packages/coconut/command/command.py", line 129, in cmd
    self.use_args(parsed_args, interact, original_args=args)
  File "/home/gurkenglas/.local/lib/python3.9/site-packages/coconut/command/command.py", line 255, in use_args
    self.start_jupyter(args.jupyter)
  File "/home/gurkenglas/.local/lib/python3.9/site-packages/coconut/command/command.py", line 719, in start_jupyter
    custom_kernel_dir = install_custom_kernel()
  File "/home/gurkenglas/.local/lib/python3.9/site-packages/coconut/kernel_installer.py", line 64, in install_custom_kernel
    os.makedirs(kernel_dest)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'
(you should report this at https://github.com/evhub/coconut/issues/new)
Exiting due to PermissionError.
gurkenglas@Gurkenglas-PC:~/.local/lib/python3.9/site-packages/lenses$ coconut -v
Coconut: Version 1.5.0 [Fish License] running on Python 3.9.5 and Cython
cPyparsing v2.4.5.0.1.2
```
got coconut via `python3.9 -m pip install coconut`.

**Comment by evhub** [comment]
I added a better error message and allowed Coconut to continue even if it encounters an error like this. There's not much else I can do, since this is actually a real error that's telling you that you need to run with `sudo` to give Coconut the necessary permissions to install the Jupyter kernel.

**Comment by Gurkenglas** [comment]
```
gurkenglas@Gurkenglas-PC:~/.local/lib/python3.9/site-packages/lenses$ python -m pudb coconut/coconut/main.py --jupyter
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/coconut/command/command.py", line 312, in handling_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/coconut/command/command.py", line 142, in cmd
    self.use_args(parsed_args, interact, original_args=args)
  File "/usr/local/lib/python3.9/dist-packages/coconut/command/command.py", line 272, in use_args
    self.start_jupyter(args.jupyter)
  File "/usr/local/lib/python3.9/dist-packages/coconut/command/command.py", line 775, in start_jupyter
    custom_kernel_dir = install_custom_kernel()
  File "/usr/local/lib/python3.9/dist-packages/coconut/install_utils.py", line 63, in install_custom_kernel
    make_custom_kernel(executable)
  File "/usr/local/lib/python3.9/dist-packages/coconut/install_utils.py", line 92, in make_custom_kernel
    shutil.rmtree(icoconut_custom_kernel_dir)
  File "/usr/lib/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.9/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'kernel.json'
(you should report this at https://github.com/evhub/coconut/issues/new)
Exiting with error: PermissionError
```
this as well. (running it in a debugger should pause execution.) is the correct way to handle this really to use sudo each time? jupyter says not to, and it might take some effort to get vscode to put sudo in front of that jupyter kernel invocation.

**Comment by evhub** [comment]
@Gurkenglas You'll need to use `sudo` once to install the kernel files, though as long as you stick with the same Coconut installation after that point you shouldn't need to run it with `sudo` again. I made the error message less scary in the situation where there's already a kernel installed in that location, that way it's more clear that you don't strictly need to run it with `sudo` if you're fine just using whatever kernel file was last installed there rather than re-installing a new one.

**Comment by Gurkenglas** [comment]
Without sudo, coconut appears to contradict itself. With sudo, coconut doesn't see the cPyparsing installed in the same site-packages folder.
(If you find these reports tedious, we can let it drop - I'm assuming you would find them interesting even if they were merely generated by sophisticated CI.)
```
gurkenglas@Gurkenglas-PC:~/.emacs.d/pen.el$ pip install --upgrade coconut-develop>=1.5.0-post_dev71
gurkenglas@Gurkenglas-PC:~/.emacs.d/pen.el$ coconut --jupyter
Warning: Failed to update Coconut Jupyter kernel installation (try again with 'sudo').
Coconut: Installing Coconut Jupyter kernels...
Coconut: Successfully installed Jupyter kernels: coconut, coconut_py, coconut_py2, coconut_py3
gurkenglas@Gurkenglas-PC:~/.emacs.d/pen.el$ coconut --jupyter
Warning: Failed to update Coconut Jupyter kernel installation (try again with 'sudo').
Coconut: Installing Coconut Jupyter kernels...
Coconut: Successfully installed Jupyter kernels: coconut, coconut_py, coconut_py2, coconut_py3
gurkenglas@Gurkenglas-PC:~/.emacs.d/pen.el$ sudo coconut --jupyter
[sudo] password for gurkenglas:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/coconut/_pyparsing.py", line 46, in <module>
    import cPyparsing as _pyparsing
ModuleNotFoundError: No module named 'cPyparsing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/coconut/_pyparsing.py", line 59, in <module>
    import pyparsing as _pyparsing
ModuleNotFoundError: No module named 'pyparsing'
Traceback (most recent call last):
  File "/usr/local/bin/coconut", line 5, in <module>
    from coconut.main import main
  File "/usr/local/lib/python3.9/dist-packages/coconut/main.py", line 35, in <module>
    from coconut.command import Command
  File "/usr/local/lib/python3.9/dist-packages/coconut/command/__init__.py", line 20, in <module>
    from coconut.command.command import *  # NOQA
  File "/usr/local/lib/python3.9/dist-packages/coconut/command/command.py", line 30, in <module>
    from coconut.compiler import Compiler
  File "/usr/local/lib/python3.9/dist-packages/coconut/compiler/__init__.py", line 20, in <module>
    from coconut.compiler.compiler import *  # NOQA
  File "/usr/local/lib/python3.9/dist-packages/coconut/compiler/compiler.py", line 37, in <module>
    from coconut._pyparsing import (
  File "/usr/local/lib/python3.9/dist-packages/coconut/_pyparsing.py", line 85, in <module>
    raise ImportError(
ImportError: Coconut requires pyparsing/cPyparsing version >= 2.4.5 (run 'pip install --upgrade cPyparsing' to fix)
gurkenglas@Gurkenglas-PC:~/.emacs.d/pen.el$ pip install --upgrade cPyparsing
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cPyparsing in /home/gurkenglas/.local/lib/python3.9/site-packages (2.4.5.0.1.2)
```

**Comment by evhub** [comment]
@Gurkenglas I certainly do appreciate the error reports. I've cleaned up the error messages a bit more so they'll be more informative (e.g. actually telling you where to install cPyparsing so it ends up the right spot if it somehow wasn't installed previously and removing the seeming contradiction you noticed), but you will still need to follow the instructions in the error messages. To get the latest version, just `pip install -U coconut-develop>=1.5.0-post_dev72`.

**Comment by bj0** [comment]
I just ran into the permissions issue while messing with nix + coconut + jupyter. Write permissions to the installation directory may not always be possible (as is the case with a nix store), so `coconut --jupyter console` will always fail.

Is there a way to bypass this or install the kernel as its own package?

**Comment by bj0** [comment]
@evhub since I'm trying to do it all through Nix, I am unable to use pip. Nix is its own package manager and much more strict about controlling versions, and it does not allow write access to the "install" directory.

I'm not sure how much you know about nix (I'm just learning it myself), but I believe it essentially does a `pip install` from source during it's "build phase" and then copies everything to the read-only store.  I'm tettling it to install `coconut-develop[jupyter]>=1.5.0-post_dev72`.

Everything seems to install (ipython works, jupyter works, coconut by itself works), but `coconut --jupyter console` throws `PermissionError` and exits.

**Comment by evhub** [comment]
@bj0 Can you show me what the error message looks like? Also, if Jupyter can already see the Coconut kernel, but you just can't run `coconut --jupyter console`, you can also always just do `jupyter console --kernel coconut` (or `jupyter console --kernel coconut_py` if `coconut` isn't available).

**Comment by bj0** [comment]
I'm not sure if jupyter can see the coconut kernel, when I do `kernelspec list` it only shows a python3 kernel in the nix store.  It sees coconut kernels that I have installed previously using pyenv (it doesn't work well with them), but i'm trying to use nix-only (i'm not sure how to prevent it from looking at those other locations).  

The error I'm getting is:

```
coconut --jupyter console
Traceback (most recent call last):
  File "/nix/store/zqacxzvd98jpxcwagm3adhr2b58l41ff-python3-3.9.4-env/lib/python3.9/site-packages/coconut/command/command.py", line 347, in handling_exceptions
    yield
  File "/nix/store/zqacxzvd98jpxcwagm3adhr2b58l41ff-python3-3.9.4-env/lib/python3.9/site-packages/coconut/command/command.py", line 143, in cmd
    self.use_args(parsed_args, interact, original_args=args)
  File "/nix/store/zqacxzvd98jpxcwagm3adhr2b58l41ff-python3-3.9.4-env/lib/python3.9/site-packages/coconut/command/command.py", line 265, in use_args
    self.start_jupyter(args.jupyter)
  File "/nix/store/zqacxzvd98jpxcwagm3adhr2b58l41ff-python3-3.9.4-env/lib/python3.9/site-packages/coconut/command/command.py", line 821, in start_jupyter
    custom_kernel_dir = install_custom_kernel()
  File "/nix/store/zqacxzvd98jpxcwagm3adhr2b58l41ff-python3-3.9.4-env/lib/python3.9/site-packages/coconut/util.py", line 117, in install_custom_kernel
    make_custom_kernel(executable)
  File "/nix/store/zqacxzvd98jpxcwagm3adhr2b58l41ff-python3-3.9.4-env/lib/python3.9/site-packages/coconut/util.py", line 152, in make_custom_kernel
    shutil.rmtree(icoconut_custom_kernel_dir)
  File "/nix/store/xlx3ggrknn1a082f2h8j712pjg7wz151-python3-3.9.4/lib/python3.9/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/nix/store/xlx3ggrknn1a082f2h8j712pjg7wz151-python3-3.9.4/lib/python3.9/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/nix/store/xlx3ggrknn1a082f2h8j712pjg7wz151-python3-3.9.4/lib/python3.9/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'kernel.json'
(you should report this at https://github.com/evhub/coconut/issues/new)
Exiting with error: PermissionError
```

**Comment by evhub** [comment]
@bj0 I see—that specific error should only give a warning if you use `coconut-develop>=1.5.0-post_dev82`, though I'm not sure if that'll actually help, since `coconut --jupyter console` is likely to still just fail if it can't install any kernels (though you should still try, it might just work on the newest version). There's not that much I can do if it doesn't work on the latest version, though, since without write permissions to the directory where the kernels need to be stored, there's no way to install the kernels.

**Comment by bj0** [comment]
Hmm, I'll try it tomorrow on my other computer, but looking at how other kernels are handled in the jupyterWith nix project[1], I may need to explicitly write out the kernel.json file in the nix install script.  Is that in the code somewhere?  Or do you generate it dynamically.

    [1]: https://github.com/tweag/jupyterWith/blob/master/kernels/ipython/default.nix

**Comment by evhub** [comment]
@bj0 The `coconut_pyX` kernel files are static and stored [here](https://github.com/evhub/coconut/tree/develop/coconut/icoconut/coconut_py), [here](https://github.com/evhub/coconut/tree/develop/coconut/icoconut/coconut_py2), and [here](https://github.com/evhub/coconut/tree/develop/coconut/icoconut/coconut_py3), but the `coconut` kernel file is generated dynamically at install time (in `coconut/icoconut/coconut`). All kernels then need to be installed into `share/jupyter/kernels`.

**Comment by bj0** [comment]
Ok I learned enough to get it to work.  For anyone else who's interested here's whats what:

I used [jupyterWith](https://github.com/tweag/jupyterWith) to create the jupyter environment, but I had to add a custom kernel for coconut.  I based it off one of their pre-existing ones, it was pretty straightforward.

I also had to use [mach-nix](https://github.com/DavHau/mach-nix) to pull an updated coconut, since the one in nixpkgs is 1.4.3, and I wasn't sure of all the dependencies for building from scratch.

The files are below, a `shell.nix` file to launch with `nix-shell`, and a `coconut/default.nix` file that has the kernel definition.  I couldn't find a coconut icon on the doc site so i just copied a random icon from jupyterWith (it's used when you launch jupyter lab).

`shell.nix`
```
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz) {} }:

let
    mach-nix = import (builtins.fetchGit {
        url = "https://github.com/DavHau/mach-nix";
        ref = "refs/tags/3.3.0";
      }) {
        # python = "python38";
        pypiDataRev = "e747f31df341f0b8fe9bef114043bdc51acbbcaf";
        pypiDataSha256 = "0knpr745w8xklklbb915z1084xymy0w1vi9hz9ss56hii70v4wrg";
    };

    jupyter = import (builtins.fetchGit {
        url = https://github.com/tweag/jupyterWith;
    }) {};

    # make a python with updated coconut
    mnPython = mach-nix.mkPython {
        requirements = ''
            coconut>=1.5.0
        '';
        ignoreCollisions = true;
    };

    # create kernel
    icoconut = pkgs.callPackage ./coconut {
        name = "coconut";
        python3 = mnPython.python;
    };

    # create jupyter environemnt
    jupyterEnvironment = jupyter.jupyterlabWith {
        kernels = [ icoconut ];
        # add console
        extraPackages = p: [ p.python3Packages.jupyter_console ];
    };

in
    jupyterEnvironment.env.overrideAttrs (oldAttrs: {
        shellHook = oldAttrs.shellHook + ''
            jupyter console --kernel coconut_coconut
        '';
    })
```

`coconut/default.nix`
```
{ stdenv
, python3
, name ? "nixpkgs"
, packages ? p: []
, pkgs
, pkg ? "coconut"
}:

let
  kernelEnv = python3.withPackages ( p: [ p."${pkg}" ]);

  kernelFile = {
    argv = [
      "${kernelEnv.interpreter}"
      "-m"
      "coconut.icoconut"
      "-f"
      "{connection_file}"
    ];
    display_name = "Coconut " + name;
    language = "coconut";
    logo64 = "logo-64x64.svg";
  };

  icoconut = stdenv.mkDerivation {
    name = "icoconut-kernel";
    phases = "installPhase";
    src = ./coconut.png;
    buildInputs = [];
    installPhase = ''
      mkdir -p $out/kernels/coconut_${name}
      cp $src $out/kernels/coconut_${name}/logo-64x64.png
      echo '${builtins.toJSON kernelFile}' > $out/kernels/coconut_${name}/kernel.json
    '';
  };
in
  {
    spec = icoconut;
    runtimePackages = packages pkgs;
  }
```

This works great, launching a coconut+jupyter console.  One thing to note is that the way jupyterWith works, there is a separate "shell" environment that is different than the kernel environments, which means coconut is not available in the shell.  This means you can't `coconut --jupyter console`, so you must `jupyter console --kernel coconut_<name>`.

I was able to fix this by using jupyterWith's overlay feature, and with 1.5.0dev82, It worked with warings:

```
PermissionError: [Errno 13] Permission denied: 'kernel.json'
CoconutWarning: Coconut Jupyter kernel installation failed due to above error (try again with 'sudo').
CoconutWarning: failed to install 'coconut' Jupyter kernel (falling back to 'coconut_pyX' kernels instead)
Coconut: Installing Jupyter kernels 'coconut_py', 'coconut_py2', 'coconut_py3'...
CoconutWarning: could not find 'coconut' kernel; using 'coconut_py3' kernel instead
Coconut: Successfully installed Jupyter kernels: 'coconut_py', 'coconut_py2', 'coconut_py3'
Jupyter console 6.4.0

Coconut 1.5.0-post_dev82 [Fish License]
```

Unfortunately, it also created kernel files in `~/.local/share/jupyter/kernels`, which I didn't want it to do, so for now I'll just use what I have above.


PS: it's easy to use the development version with the following changes:

```
    ...

    # make a python with updated coconut
    mnPython = mach-nix.mkPython {
        requirements = ''
            coconut-develop>=1.5.0dev82
        '';
        ignoreCollisions = true;
    };

    ...

    # create kernel
    icoconut = pkgs.callPackage ./coconut {
        name = "coconut";
        python3 = mnPython.python;
        pkg = "coconut-develop";
    };

```

Note that `mach-nix` works off a *snapshot* of pypi that's fixed with a revision and hash, so if you want to use a newer dev build than what's in the snapshot you have to get a new revision/hash from https://github.com/DavHau/pypi-deps-db.  Or you can just figure out how to build it from source.

**Comment by evhub** [comment]
@bj0 Glad you got it working! Let me know if there's anything else I can do to help make Coconut easier to use with nix.

**Comment by bj0** [comment]
I would just like to put in a quick update for anyone who finds this and tries to use nix with coconut.  I was able to significantly simplify it.

I put it up in a repo at https://github.com/bj0/nix-coconut

If you have nix with flakes support, you can run it directly from there with `nix run github:bj0/nix-coconut`
