### ISSUE TITLE
Add --and for doing extra compilation with the same arguments

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#587]
```bash
coconut src dst --and src2 dst2 --and src3 dst3 --target x.y
```
should be equivalent to
```bash
coconut src dst --target x.y
coconut src2 dst2 --target x.y
coconut src3 dst3 --target x.y
```
and also enable `--jobs` to do all the compilation simultaneously.

**Comment by nlipsyc** [comment]
Hi! I think I'll take a swing at this if it's still relevant.

**Comment by evhub** [comment]
@nlipsyc That'd be great! And yep, this is definitely something on the to-do list for the next version.

**Comment by nlipsyc** [comment]
Great! I put together https://github.com/evhub/coconut/pull/595.  A few of the tests are failing, but it looks like those are broken in the rest of the builds too. Let me know what you think.
