### ISSUE TITLE
Website does not support TLS

### ISSUE THREAD

**Issue by raxod502** [evhub/coconut#590]
```
% http https://coconut-lang.org

http: error: SSLError: HTTPSConnectionPool(host='coconut-lang.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'coconut-lang.org' doesn't match either of 'www.github.com', '*.github.com', 'github.com', '*.github.io', 'github.io', '*.githubusercontent.com', 'githubusercontent.com'"))) while doing GET request to URL: https://coconut-lang.org/
```

Originally reported in https://github.com/evhub/coconut/pull/589 with an attempted fix that did not actually work.

**Comment by evhub** [comment]
Finally figured out what was wrong and fixed this; just needed to update the `A` record to point to new GitHub IP addresses.

**Comment by raxod502** [comment]
Heh, nice! I think you can just a CNAME instead of an A record FWIW, and avoid any need for manual updates.

**Comment by evhub** [comment]
I have a CNAME for the www subdomain but I think for the apex domain it would need to be an ALIAS record which Google domains doesn't support.

**Comment by raxod502** [comment]
Ah unfortunate, you could always consider putting it behind CloudFlare which I believe would let you tack that on without changing the underlying registrar.
