### ISSUE TITLE
Submit highlighter extension to VSX open registry 

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#591]
Saw commit 63974ae and that #586 was resolved! :tada: 

If you're not opposed to it, could the extension be submitted to the [Open VSX](https://open-vsx.org/) registry? Mostly for those of us who prefer to use [vscodium](https://github.com/VSCodium/vscodium)...see the note [here](https://github.com/VSCodium/vscodium#extensions-and-the-marketplace).

VSCodium is a fairly nice open source option to dev w/ Coconut, at least while there's not quite an LSP to use with Emacs (#513) :smile:

**Comment by evhub** [comment]
@tbsexton Done! See: https://open-vsx.org/extension/evhub/coconut
