### ISSUE TITLE
Automatic concatenation of ``f-string``s not working properly

### ISSUE THREAD

**Issue by servadestroya** [evhub/coconut#592]
With vanilla python, contiguous string literals concatenate automatically, which is useful for breaking long literal strings into multiple lines. This functionality is preserved in coconut for normal strings, but with f-strings the transpiler produces code that uses the ``.format`` method, breaking this functionality.

```python
# Regular strings
"hello ""there"

# F-strings
f"hello "f"there"
```

Results with python:
![image](https://user-images.githubusercontent.com/24995257/126850028-452570f6-1420-4666-8fd8-5d493f2f73a4.png)

Results with coconut:
![image](https://user-images.githubusercontent.com/24995257/126850051-fe81c80d-1b77-43ac-9e6e-559807bf575d.png)

**Comment by evhub** [comment]
Thanks for the bug report! This should be fixed now on `coconut-develop`, just `pip install --upgrade coconut-develop>=1.5.0-post_dev76` to get the fix.
