### ISSUE TITLE
How to implement method chaining

### ISSUE THREAD

**Issue by hamzamohdzubair** [evhub/coconut#594]
[Related Stackoverflow question](https://stackoverflow.com/questions/68539601/how-to-implement-two-methods-one-after-the-other-in-coconut)

How to chain multiple methods that modify the object but do not return anything.

#### Python:
```python
m = Model()
m.fit()             # does not return anything
m.summary()
```

#### Coconut:
```python
(
    data
    |> Model
    |> .fit()             # does not return anything
    |> .summary()         # therefore, this throws an error
)
```

**Comment by ArneBachmann** [comment]
Probably using a `map`? Or simply use the same code as in Python, which is pretty short already.

**Comment by evhub** [comment]
If you really want to use pipes for this, you can do
```python
m = (
    data
    |> Model
    |> (def m -> m.fit(); m)
    |> .summary()
)
```
though the Python code will also work in Coconut just fine.

**Comment by hamzamohdzubair** [comment]
This answer solves more than one problem! Thanks a lot.
