### ISSUE TITLE
Argument expansion erroneusly detected as "not positional"

### ISSUE THREAD

**Issue by fakuivan** [evhub/coconut#627]
```
$ coconut -V
Coconut: Version 1.6.0 [Vocational Guidance Counsellor] running on Python 3.10.0 and Cython cPyparsing v2.4.7.1.0.0
```

Something like the following works fine in regular python
```python
print(*[1,2],3)
```

However in coconut this doesn't compile. I'm assuming the compiler confuses that argument expansion as "not a positional argument". Maybe the parser sees the asterisk before the argument and confuses it with ``**kwarg``? Just a guess.

![image](https://user-images.githubusercontent.com/15100012/144082181-6ec05c12-74a8-4de1-8396-7b96293adcb4.png)

**Comment by evhub** [comment]
@fakuivan Should be fixed now if you `pip install -U coconut-develop>=2.0.0-a_dev15`.

The problem it was complaining about was that you were using a starred argument before a positional argument, so if you want to fix it without updating Coconut, it should also work if you just do
```python
print(*(1, 2), *(3,))
```
