### ISSUE TITLE
Add `coconut[kernel]` installation option for a lightweight Coconut + Jupyter kernel dependencies install

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#629]
Users of `conda`/`mamba` environments with often use `nb_conda_kernels` to keep notebook server and extensions consolidated to a single environment, and access various language kernels from other environments on the machine. This is to prevent needing so many separate jupyter client instances running (one for each environment), instead letting a single client "see" all the environments that have one or more language kernels installed. 

Compatibility with `nb_conda_kernels` was already solved in #540, but looking at what exactly the enabling dependency spec `coconut[jupyter]` _needs_, from [this section of `coconut.constants`](https://github.com/evhub/coconut/blob/27a4af9dc06667870f736f20c862930001b8cbb2/coconut/constants.py#L543), this will install _another_ instance of jupyterlab to the current conda environment, which is adding a lot of overhead when  the kernel should be simply showing itself to the separate instance of jupyter notebook/lab in its own environment. 

- Can we remove the dependency on jupyterlab and others when installing the "coconut kernel" do reduce overhead for these environment installs? I would like to be able to use coconut in jupyter without reinstalling jupyterlab each time (i.e. via nb_conda_kernels)
- I believe a more common practice is to have a separate repository/package to _only_ provide the kernel to the language, e.g. `coco_kernel`. Here's an example of the [dependency needs for octave_kernel](https://github.com/Calysto/octave_kernel/blob/master/pyproject.toml), which is using the [`metakernel`](https://github.com/Calysto/metakernel) tool to do a lot of the heavy lifting. Would you be interested in a separate `coco-kernel` repo based on `metakernel` to lighten up the dependency of coconut kernels for jupyter?

**Comment by evhub** [comment]
@tbsexton Just `pip install coconut` should install Coconut's Jupyter kernel, no need for `pip install coconut[jupyter]` unless you also want to get a known-to-be-compatible version of Jupyter installed alongside Coconut. If that's not the case, that should be noted as a bug.

**Comment by tbsexton** [comment]
Ahhh ok, so I was referring back to [your comment here](https://github.com/evhub/coconut/issues/540#issuecomment-628264742), which is I guess why I got in the habit of adding `coconut[jupyter]` to all of my `environment.yml` files. 

If I understand correctly, coconut is installing a kernelspec that is compatible with e.g. `nb_conda_kernels` and others, alerting them that "hey, there's this coconut language kernel here, ready to be used!". However, it has an unstated dependency on `ipykernel`, since without that, the kernelspec-manager will get caught in an infinite loop (trying to load coco-kernel, which asks for ipykernel, which isn't installed)

Again, looking at other language kernel implementations, they seem to be broken out into a separate repo to avoid this: 
- the "language" obviously doesn't _need_ a hard dependency on ipykernel, since that installs python bindings to the jupyter kernelspec manager
- the "language kernelspec" _does_ need ipykernel, and it is _listed_ as an install-requires for the separate "lang-kernel" package. 
- "language kernelspec" _also_ has a dependency on "language", so the lovely workflow consequence here is 
   - users wanting to run e.g. R in jupyter need only to install `irkernel` in the respective environment, not `R` itself
   - users _not caring_ about jupyter aren't forced into having the kernelspec at all, and won't get caught in an infinite loop clicking on that kernelspec without ipykernel on accident. 

Does this make sense? If we remove the kernel stuff from coconut (core) and make it a separate package and/or option (`coconut[kernel]`?), it will mimic the expected kernel installation workflow from other languages out there.

**Comment by evhub** [comment]
> If I understand correctly, coconut is installing a kernelspec that is compatible with e.g. `nb_conda_kernels` and others, alerting them that "hey, there's this coconut language kernel here, ready to be used!". However, it has an unstated dependency on `ipykernel`, since without that, the kernelspec-manager will get caught in an infinite loop (trying to load coco-kernel, which asks for ipykernel, which isn't installed)

Yep, that's right. `coconut[jupyter]` will make sure to install all the necessary dependencies, though like you pointed out it also installs other Jupyter-related stuff as well.

> Does this make sense? If we remove the kernel stuff from coconut (core) and make it a separate package and/or option (`coconut[kernel]`?), it will mimic the expected kernel installation workflow from other languages out there.

I like the idea of adding a lighter-weight install option like `kernel` for just Coconut + IPython + ipykernel. I'll modify this issue to do that.

**Comment by evhub** [comment]
@tbsexton As of `coconut-develop>=2.0.0-a_dev26`, you can now `pip install coconut-develop[kernel]` to get just the kernel dependencies rather than a full Jupyter installation.
