### ISSUE TITLE
Examples for `takewhile` is wrong.

### ISSUE THREAD

**Issue by peawyoyoyin** [evhub/coconut#637]
From coconut docs:

> ##### Example
> 
> **Coconut:**
> ```coconut
> negatives = takewhile(numiter, x -> x < 0)
> ```
> 
> **Python:**
> ```coconut_python
> import itertools
> negatives = itertools.takewhile(numiter, lambda x: x < 0)
> ```

This seems to have wrong order of parameters (according to the [python docs on itertools](https://docs.python.org/3/library/itertools.html)), as the iterable should be the second parameter of takewhile.

**Coconut:**
```coconut
negatives = takewhile(x -> x < 0, numiter)
```

**Python:**
```python
import itertools
negatives = itertools.takewhile(lambda x: x < 0, numiter)
```

I tried running coconut code with `takewhile` as well, code from the examples throws errors.

**Comment by evhub** [comment]
@peawyoyoyin Thanks for catching this! Should be fixed on the [develop version of the documentation](https://coconut.readthedocs.io/en/develop/DOCS.html) now (and will go to master once the next version of Coconut is released).
