### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by neskuk** [evhub/coconut#643]
hello there
i have tried several times to install coconut on my laptop (win8 sp3). i can't do it with pip (doesn't work at all) and also not with package manager in tonny editor. 
can anyone tell me why?

the error messages: 

Collecting coconut
  Downloading https://files.pythonhosted.org/packages/49/5c/4953c7a3dec6a1bc63e80371715df30196f467d29aec1b5ec78b42224cb3/coconut-1.6.0-py2.py3-none-any.whl (146kB)
Collecting pygments>=2.3; python_version >= "2.7" (from coconut)
  Downloading https://files.pythonhosted.org/packages/1d/17/ed4d2df187995561b28f1073df24137cb750e12f9879d291cc8ab67c65d2/Pygments-2.11.2-py3-none-any.whl (1.1MB)
Collecting prompt-toolkit>=1; python_version >= "3" (from coconut)
  Downloading https://files.pythonhosted.org/packages/fb/37/4f9ae5a6cd0ebdfc1fbafcfd03e812df1ed92a92bf0bee09441c52164f58/prompt_toolkit-3.0.24-py3-none-any.whl (374kB)
Collecting cPyparsing<2.4.8,>=2.4.7.1.0.0; platform_python_implementation == "CPython" (from coconut)
  Downloading https://files.pythonhosted.org/packages/a9/70/b40155e3dc29492a5c3e3bdb8650164816dc112417cf9d56313ba9ce8b41/cPyparsing-2.4.7.1.1.0.tar.gz (1.1MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting wcwidth (from prompt-toolkit>=1; python_version >= "3"->coconut)
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Building wheels for collected packages: cPyparsing

# first error

  Building wheel for cPyparsing (PEP 517): started
  Building wheel for cPyparsing (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Zdenek\AppData\Local\Programs\Thonny\python.exe' 'C:\Users\Zdenek\AppData\Local\Programs\Thonny\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Zdenek\AppData\Local\Temp\tmp1pjax2po'
       cwd: C:\Users\Zdenek\AppData\Local\Temp\pip-install-2nri2c8g\cPyparsing
  Complete output (5 lines):
  [1/1] Cythonizing cPyparsing.pyx
  running bdist_wheel
  running build
  running build_ext
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cPyparsing
  Running setup.py clean for cPyparsing
Failed to build cPyparsing
ERROR: Could not build wheels for cPyparsing which use PEP 517 and cannot be installed directly

Process failed, return code: 1

second error-window:
********************************************************************************
Traceback (most recent call last):
  File "C:\Users\Zdenek\AppData\Local\Programs\Thonny\lib\site-packages\pkg_resources\__init__.py", line 2681, in version
    return self._version
  File "C:\Users\Zdenek\AppData\Local\Programs\Thonny\lib\site-packages\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zdenek\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 544, in _cmd_get_active_distributions
    for dist in pkg_resources.working_set
  File "C:\Users\Zdenek\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 544, in <dictcomp>
    for dist in pkg_resources.working_set
  File "C:\Users\Zdenek\AppData\Local\Programs\Thonny\lib\site-packages\pkg_resources\__init__.py", line 2689, in version
    raise ValueError(msg, self)
ValueError: ("Missing 'Version:' header and/or PKG-INFO file at path: c:\\users\\zdenek\\desktop\\coconut-4game\\coconut-1.6.0\\coconut.egg-info\\PKG-INFO", coconut [unknown version] (c:\users\zdenek\desktop\coconut-4game\coconut-1.6.0))

**Comment by evhub** [comment]
The error seems pretty self-explanatory; you need Microsoft C++ build tools >=14.0. There's a download link in the error message. Alternatively, if you run `pip install --upgrade --no-deps coconut pyparsing<3` or `conda install -c conda-forge coconut` you can install Coconut with vanilla `pyparsing` rather than `cPyparsing`, which will be substantially slower but won't require you to download the C++ build tools.

**Comment by neskuk** [comment]
danke evan..
ich werde es weiter versuchen.coconut scheint
DAS tool zu sein, dass ich schon lange suche.
...

Am Di., 18. Jan. 2022 um 21:47 Uhr schrieb Evan Hubinger <
***@***.***>:
