### ISSUE TITLE
ABC.coco compiled to abc.py not ABC.py

### ISSUE THREAD

**Issue by hlizard** [evhub/coconut#656]
According to the document "```When Coconut compiles a .coco (or .coc/.coconut) file, it will compile to another file with the same name, except with .py instead of .coco```", it should be compile to ABC.py.

win10

Coconut: Version 2.0.0-a_dev50 [How Not to Be Seen] running on Python 3.7.9
and Cython cPyparsing v2.4.7.1.1.0

**Comment by evhub** [comment]
This is not exactly a bug—it happens because Windows is a case-insensitive file system, so when Coconut canonicalizes the destination path it converts it to lowercase. Probably it's better to just avoid case canonicalization to avoid this, though.

**Comment by Sitwon** [comment]
Does it lowercase the filename on Windows regardless of the filesystem settings? NTFS is internally case-sensitive, so ABC.py and abc.py could be two different files on an NTFS filesystem in Windows. However depending on the OS configuration applications will generally pretend that the filesystem is case-insensitive for backwards compatibility.

See also: 
  - https://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity
  - https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/

**Comment by evhub** [comment]
Should be fixed now if you `pip install -U coconut-develop>=2.0.0-a_dev51`.

@Sitwon I believe it wouldn't care about the directory settings, since the Python docs for `os.path.normcase` seem to imply it just checks whether it's on Windows or not.
