### ISSUE TITLE
coconut --jupyter qtconsole runs python kernel rather than coconut kernel.

### ISSUE THREAD

**Issue by kksgandhi** [evhub/coconut#717]
Command: `coconut --jupyter qtconsole`

Outcome: a jupyter qtconsole running python as the kernel

Expected: a jupyter qtconsole running coconut as the kernel

Notes:

- Running `coconut --jupyter console` runs a jupyter console w/ coconut, as you'd expect
- Setting `c.JupyterConsoleApp.kernel_name = 'coconut'` in `~/.jupyter/jupyter_qtconsole_config.py` causes the jupyter qtconsole to be run with coconut as the kernel.

**Comment by evhub** [comment]
Fixed on `coconut-develop>=3.0.0-a_dev8`. Simple workaround for this also is just to run `jupyter qtconsole --kernel coconut`.

**Comment by kksgandhi** [comment]
Thank you!
