### ISSUE TITLE
Change pipe operator

### ISSUE THREAD

**Issue by yggdr** [evhub/coconut#719]
Currently the pipe operator injects its left argument into the last position of the callable `'pipe' |> f$(0)`. I find that python libraries are not very unified about where the "main" argument of their functions goes, first or last. So I find myself wishing to have an easy operator that inserts in the first position instead of the last just about as often as the other way around.

Now, the `?` syntax allows one to do that (and more), but I'd like to suggest that it might make sense to have one operator each for inserting into the first and into the last position. I believe these two cases are abundant enough to warrant talking about this. Unfortunately my preferred syntax would be quite a change: make `|>` insert into the first position, and add a new operator `|>>` to do what `|>` does currently: insert into the last position. So I can understand if this is not well received.

**Comment by evhub** [comment]
I think this is confusing and I'm not sure what the use case would be over `x |> f$(?, y)`.
