### ISSUE TITLE
Operator functions incompatible with multi-word operators

### ISSUE THREAD

**Issue by yggdr** [evhub/coconut#721]
Right now coconut's operator functions are restricted to single-word operators.`(is)` and `(+)` work as expected, but `(is not)` and `(not in)` are `CoconutParseError`s. This is currently not explicitly stated, the multi-word operators are simply missing from the list of available operator functions, making it easy to gloss over the list of `operator.<something>` that come from python, and concentrating only on the new coconut operators.
So if this restriction isn't easy to lift, I'd like to suggest adding a warning about it to the docs and refer to the example from the addpattern-decorator-section, that uses a function composition `(. is None) ..> (not)`.

This came about when I tried using them in pattern matching with implicit partial application of the form `(. <op> <arg>)`. Here I have seen an additional gotcha: while `(is not)` is an invalid operator function, `(. is not None)` _is_ valid and is compiled like `(. is (not None))`.

**Comment by evhub** [comment]
As a workaround, you should be able to do
```
(is) ..> (not)
```
or even
```
operator is not
(is not) = (is) ..> (not)
```

**Comment by evhub** [comment]
This is live now on `coconut-develop>=3.0.0-a_dev11`.

**Comment by yggdr** [comment]
Wow, that is impressive! Thanks!
