### ISSUE TITLE
multiline pipe

### ISSUE THREAD

**Issue by setop** [evhub/coconut#722]
Instead of writing 

```[1,2,3] |> filter$(x -> (x & 1) == 1) |> list |> len |> print```

I'd like to be able to write

```
[1,2,3] 
|> filter$(x -> (x & 1) == 1)  # filter odd 
|> list 
|> len 
|> print
```

As seen in [Elixir](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/calendar/date.ex#L176)

Currently if I try this, I get syntax error.

```
CoconutParseError: parsing failed (line 4)
  |> filter$(x -> (x & 1) == 1)
  ^
Coconut exiting with error: CoconutParseError
```

**Comment by evhub** [comment]
Just use Python's implicit line continuation inside parentheses, the same way you would for any other long sequence of Python operators:
```python
(
    [1,2,3] 
    |> filter$(x -> (x & 1) == 1)  # filter odd 
    |> list 
    |> len 
    |> print
)
```
