### ISSUE TITLE
Cannot access hidden directories on linux in xonsh

### ISSUE THREAD

**Issue by caedmon-kitty** [evhub/coconut#726]
coconut version 2.2.0
xonsh version 0.13.4
coconut installed using pip - pip install -U coconut

Attempts to reference directories beginning with a '.' character (linux hidden directories) results in an error.
⇨ cd .local
cd: no such file or directory: .l

⇨ cp .xonshrc.now .xonshrc
cp: missing destination file operand after '.xonshrc.now'
Try 'cp --help' for more information.

xontrib unload coconut does not solve the problem. 
xonsh --no-rc does not solve the problem
xontrib unload coconut does not solve the problem.
The only fix is to comment out the call to CoconutXontribLoader() in coconut/integrations.py

As a work around is it possible to not auto load coconut on xonsh startup but be able to xontrib load is if needed?

**Comment by evhub** [comment]
Fixed on `coconut-develop>=3.0.0-a_dev21` (`pip uninstall coconut` and `pip install -U coconut-develop>=3.0.0-a_dev21` to get the fix). `xontrib unload coconut` should also be working on `coconut-develop` as of #724.

> As a work around is it possible to not auto load coconut on xonsh startup but be able to xontrib load is if needed?

This is how it used to work, but for some reason on the newest major version of xonsh doing it that way doesn't seem to work anymore and I'm not sure why.
