### ISSUE TITLE
Standalone mode disables multiple jobs on compiling directory

### ISSUE THREAD

**Issue by yggdr** [evhub/coconut#739]
It seems since the release of version 3 compiling an entire directory with `--standalone --jobs <some_number_or_"sys">` always results in a single compiler process, building each file in the directory one after another.
(Standalone mode is necessary due to #720)

Error given is `CoconutWarning: got --jobs <some_number_or_"sys"> but only compiling one file; disabling --jobs`

**Comment by evhub** [comment]
Fixed on `coconut-develop>=3.0.0-post_dev3`. As a workaround for `3.0.0`, try:
```
coconut --stand-alone <path/to/dir> --and <path/to/dir> <path/to/dir>
```
