### ISSUE TITLE
Add keeplines flag to improve debugging

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#74]
Currently, `pdb` uses some pretty basic regexes to find the right source code. These could easily be changed to do the same for Coconut. See <https://hg.python.org/cpython/file/3.5/Lib/pdb.py>.

**Comment by chuckwondo** [comment]
@evhub Would you mind elaborating a bit? Are you saying that the regex pattern for matching Coconut function signatures would need to be a bit more sophisticated?

Also, how do you see this rewrite fitting into Coconut itself? Are you suggesting pulling `pdb.py` into Coconut and tweaking the regexes?

**Comment by evhub** [comment]
@chuckwondo Honestly, I haven't put much thought into what the implementation of this would look like. It's been sitting on my back burner for a while and I haven't really been actively thinking about it. The goal here is to be able to see Coconut source code instead of compiled Python as you step through the debugger. Passing `--linenumbers` helps alleviate this problem a lot, since you'll see the source code line numbers in the compiled Python, but it's still not ideal. Ideally, you'd skip the step of having to look up what code was at that line number and just display it right there. I'm not really sure what the best way to accomplish that might be, though.

**Comment by chuckwondo** [comment]
This might only be an interim solution, but what if you put the line of Coconut code itself in the comment rather than just the line _number_?

**Comment by evhub** [comment]
@chuckwondo Not a bad idea! What would a good flag name for that be? `-k, --keeplines` maybe?

**Comment by chuckwondo** [comment]
@evhub Yes, that flag looks good to me. I've seen that name used in another tool that I'm familiar with, so I like the cross-tool naming consistency. The tool is completely unrelated (JSP -> Servlet translator), but does the same sort of thing (or at least it did in older versions), which reminds me, shouldn't we be referring to the Coconut compiler as a [transpiler](https://en.wikipedia.org/wiki/Source-to-source_compiler)?

**Comment by evhub** [comment]
@chuckwondo Great! I'll try to get `--keeplines` in the next release. And yeah, transpiler is probably the more accurate term, although I think it sounds somewhat silly, especially the verb form "transpiles." And it's not inaccurate to say that Coconut compiles to Python.

**Comment by evhub** [comment]
@chuckwondo This is now live in develop.
