### ISSUE TITLE
[xonsh] semi-colon command separation is still broken (sorry!)

### ISSUE THREAD

**Issue by Starwort** [evhub/coconut#762]
![image](https://github.com/evhub/coconut/assets/16487249/d2c03925-697c-421f-88b0-cd12e1163d27)

**Comment by evhub** [comment]
As of `coconut-develop>=3.0.2-post_dev7`, I've changed how Coconut parses `xonsh` commands to resolve some instances of this issue (e.g. `echo abc; echo abc` works now but `echo; echo` still doesn't) (`pip uninstall coconut` and `pip install coconut-develop>=3.0.2-post_dev7` to get the fix).

**Comment by evhub** [comment]
This should now be fixed as of `coconut-develop>=3.0.2-post_dev34`.
