### ISSUE TITLE
`if` + string w/o whitespace creates strange characters

### ISSUE THREAD

**Issue by kg583** [evhub/coconut#819]
```py
if "0":print("foo")         # foo

if"0":print("foo")          # SyntaxError: invalid character '▶' (U+25B6)

if"abcdef":print("foo")     # SyntaxError: invalid character '▶' (U+25B6)

if"0":
  print("foo")              # SyntaxError: invalid character '▶' (U+25B6)

if"":print("foo")           # (this one's fine, yielding no output)
```

The full error for all of those is
> ```
> File "<string>", line 1
>    if ▶0⏹:  #1: if"0":print("foo")
>       ^
> SyntaxError: invalid character '▶' (U+25B6)```

Notably, the referenced transpiled code is independent of the source string.

**Comment by evhub** [comment]
Fixed as of `coconut-develop>=3.0.4-post_dev13` (`pip install -U coconut-develop>=3.0.4-post_dev13` to get the fix).
