### ISSUE TITLE
unicode alternative of multiple-argument pipe backward `↤*` does not work

### ISSUE THREAD

**Issue by JayXon** [evhub/coconut#822]
docs says `↤*` is an alternative to `<*|`

ascii works
```py
print <*| [1,2]
```
unicode alternative gives parser error
```py
print ↤* [1,2]
```
```
CoconutParseError: parsing failed (line 1)
  print ↤* [1,2]
  \~~~~~~^
```
pipe forward works fine

**Comment by evhub** [comment]
Fixed as of `coconut-develop>=3.0.4-post_dev17` (`pip install -U coconut-develop>=3.0.4-post_dev17` to get the fix).
