### ISSUE TITLE
Coefficient syntax error message is too specific

### ISSUE THREAD

**Issue by kg583** [evhub/coconut#827]
Coefficient syntax errors raise the following message:
```py
TypeError: implicit function application and coefficient syntax only supported for Callable, int, float, complex, and numpy objects
```
However, this message is too specific, as coefficient syntax can be applied to any variable, regardless of type:
```py
x = [1, 2, 3]
print(2x)

x = "foo"
print(2x)
```
It even parses fine the other way, with type checks distinguishing application and multiplication just fine:
```py
x = 1
print(x 2)

x = bytes
print(x 2)
```
All of this is to say that the error message could be improved to indicate that things are a bit more smart and relaxed than they seem. I'm not sure of a particular replacement yet, though, because the message _does_ accurately relay the situation for literals.

**Comment by evhub** [comment]
Well, it's a `TypeError`, not a `SyntaxError`—it works for variables, but only variables that point to objects of the right type. Documentation could potentially be improved here, though.

**Comment by evhub** [comment]
Ah, yes, I see the confusion. It is referring to the first object in the expression (the coefficient in your examples).
