### ISSUE TITLE
Empty `zip` objects error on `__len__`

### ISSUE THREAD

**Issue by kg583** [evhub/coconut#834]
Getting the length of an empty `zip` object (e.g. `len(zip())`) raises
```python
ValueError: min() iterable argument is empty
```
since the length is computed as the minimum length among the iterators, but no default value is set.

**Comment by neel11235813** [comment]
I have faced a similar issue as well

**Comment by evhub** [comment]
Fixed as of `coconut-develop>=3.1.0-post_dev3` (`pip uninstall coconut && pip install -U coconut-develop>=3.1.0-post_dev3`). Also universalizes `default=` argument for `min` and `max` built-ins.
