### ISSUE TITLE
Improve implicit partial application

### ISSUE THREAD

**Issue by shilkazx** [evhub/coconut#841]
Allow multiple reference of implicit partial.
What we can do is:
```
>>> [0, 1] |> .[1]
1
```
But we can't do this:
```
>>> [0, 1] |> .[1] + .[0]
 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'operator.itemgetter' and 'operator.itemgetter'
```
A nagging crossover could work, but why not improve the implicit partial:
```
>>> [0, 1] |> =>_[1] + _[0]
1
```

**Comment by evhub** [comment]
Implicit partials are intended to be for simple, straightforward operations that can't easily be built out of other operations, not to replace lambdas completely. In this case, however, Coconut does actually have an easy way to write this point-free using the [`lift` built-in](https://coconut.readthedocs.io/en/latest/DOCS.html#lift-and-lift-apart):
```python
>>> [0, 1] |> lift(+)(.[1], .[0])
1
```

**Comment by shilkazx** [comment]
Oh, it does implement the feature but using 'lift' under such circumstances is weirder and more cumbersome than implicit lambda.
Anyway, thanks for your good advice and I really love coconut.
