### ISSUE TITLE
docs: clarify what an entry of "yes" means for an operator

### ISSUE THREAD

**Issue by aidanmontare-fed** [evhub/coconut#856]
In the [Precedence table for operators](https://coconut.readthedocs.io/en/latest/DOCS.html#precedence), the associativity column has some values of "yes". Could the docs explain what this means?

**Comment by evhub** [comment]
Maybe "both" would be more clear? It's saying that it's left and right associative.

**Comment by aidanmontare-fed** [comment]
Oh okay, that clued me in enough to look up and remind myself that operators can be both left and right associative. Might just be my confusion.

"Both" or "left and right" does sound more clear to me.

Thanks for the clarification!
