### ISSUE TITLE
Multiline/-expression lambdas/anonymous functions?

### ISSUE THREAD

**Issue by Deleetdk** [evhub/coconut#90]
Not a bug, but I could not find an answer anywhere. I mostly use R and very much like the functional approach. Python lacks proper pipes which are essential IMO to functional programming, so I was happy to discover Coconut!

Another essential part of functional programming (to me) is using a bunch of anonymous functions. For instance:

```
#mean intercor by column
mibi = function(x) {
  v = sapply(1:ncol(x), function(col) {
    col = x[, col]
    (sum(col) - 1) / (ncol(x) - 1)
  })
  
  names(v) = colnames(x)
  
  v
}

mibi(r_cors$correlations[-1, -1])
```

So, we make a function, `mibi`, that finds the mean intercorrelation by column from a correlation matrix. The main part of the function is `sapply` (an implicit loop that returns a vector [equivalent to a simple list in Python]), which is given an anonymous function that spans 2 lines.

In [the Coconut documentation](http://coconut.readthedocs.io/en/master/DOCS.html#lambdas), there is an example of a lambda:

```
dubsums = map((x, y) -> 2*(x+y), range(0, 10), range(10, 20))
dubsums |> list |> print
```

Compared to the ordinary Python:

```
dubsums = map(lambda x, y: 2*(x+y), range(0, 10), range(10, 20))
print(list(dubsums))
```

But this is still only a one-liner lambda. How would one use multi-line/expression lambdas?

**Comment by evhub** [comment]
Thanks for the issue! Currently, Coconut only supports one-line, not multi-line lambdas. Multi-line lambdas is definitely a feature I could add, however. The reason I haven't yet is that in most cases I find that, since a `def` block is valid anywhere, it's always possible to simply use that when one feels the need to use a multi-line lambda.

I'm not opposed to adding multi-line lambdas, however. How does this look:
```
map(def (x, y) -> (
    some_func(x)
    some_other_func(y)
    ), xs, ys)
```
which would compile to something like
```
def _lambda(x, y):
    some_func(x)
    some_other_func(y)
map(_lambda, xs, ys)
```
which should do exactly what you want. Do you think that would be helpful?

**Comment by Deleetdk** [comment]
People have been requesting multi-line lambdas for years. They are not in Python because [the dictator doesn't like them](http://stackoverflow.com/questions/1233448/no-multiline-lambda-in-python-why-not).

Your example looks like it is missing the `return` call. R automatically returns the last object (i.e. the output of `some_other_func(y)` in your example), I'm not sure what Python does.

Otherwise, the syntax seems alright to me. It's basically using `()`'s just as one would use `{}`'s in other languages.

**Comment by evhub** [comment]
Good point—the proper compilation of the above would be
```
def _lambda(x, y):
    some_func(x)
    return some_other_func(y)
map(_lambda, xs, ys)
```
if that were to be added as a feature.

**Comment by evhub** [comment]
@Deleetdk @fredcallaway @ymeine I think I should be able to do this, the only issue is that I need to respect the Python rule that whitespace is ignored inside of parentheses. Thus, I think my solution will be to allow lambdas to contain statements (inside of parentheses), which includes Python's syntax for putting multiple statements together of putting a semicolon between them. I could even have it check for the use of multiple statement syntax and automatically return the last one. Thus,
```
map(def (x, y) -> (
    some_func(x);
    some_other_func(y)
    ), xs, ys)
```
would be how you would have to write the above example.

**Comment by evhub** [comment]
This is now line in develop. Still missing documentation, but that'll be added in develop soon as well. The final implementation is:
```
map((def (x, y) -> some_func(x); some_other_func(y)), xs, ys)
```
(note the required `def` at the beginning, and that it must be surrounded in parentheses)

**Comment by evhub** [comment]
@Deleetdk @fredcallaway @ymeine @mikeiavelli @Boscillator This is now finished in develop and will be released in the next version! Closing this issue.
