### ISSUE TITLE
Add an implicit itemgetter

### ISSUE THREAD

**Issue by evhub** [evhub/coconut#91]
The suggestion is to add an implicit partial that maps to `itemgetter`.

Edit: Removed the suggestion of
```
.1 => itemgetter(1)
```
since it overlaps with `float`s.

**Comment by candeira** [comment]
what do you do with the very legal Python float `.1` then?

```
pythkandinski@desire:~$ python3
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> .1
0.1
>>> type(.1)
<class 'float'>
```

If we make `.1` be an implicit itemgetter, it would be at the cost of losing strict superset quality.

**Comment by candeira** [comment]
Based on the suggested syntax for anonymous functions in https://github.com/evhub/coconut/issues/36, a shorter itemgetter could be:

```
$[1] => itemgetter(1)
$["foo", "bar"] => itemgetter(foo, bar]
``` 

Of course, if the suggestion from issue #36 is accepted that `$` and `?` be switched, the syntax would be:

```
?[1] => itemgetter(1)
?["foo", "bar"] => itemgetter(foo, bar]
```

**Comment by evhub** [comment]
Hahaha! Good point! I just put this down here word-for-word from a comment somebody made on the reddit thread—the overlap with the float never even occurred to me. I think
```
?[1]
```
is an alright choice for a normal slicing implicit partial, but it would also be nice to have one for iterator slicing as well. The natural extension would be
```
?$[1]
```
although I find that very symbol-heavy, which is something I'd like to avoid. Not sure what the solution to that is.

**Comment by candeira** [comment]
The other issue I see with this leading-dot itemgetter idea and strict Python compatibility is that this:

```
>>> "foo"                .upper
<built-in method upper of str object at 0x7ff060bfcf10>
>>> _()
'FOO'
>>> 
```

Is legal Python. So the Coconut parser would have to choose between full Python3 subset compliance and this itemgetter syntax.

**Comment by evhub** [comment]
@candeira For attribute and method getters, which already exist, Coconut first checks to see if they are valid Python like above, and only if they aren't do they become implicit partials. I think #36 will help resolve this issue, although I'd still like an implicit itemgetter syntax since a real itemgetter would be pickleable, whereas a lambda wouldn't.

**Comment by evhub** [comment]
@candeira I would like to add implicit itemgetter syntax, but I'm trying to decide between two different options.

Option 1:
```
?[0] # for normal sequences
?$[0] # for iterators
```

Option 2:
```
.[0] # for normal sequences
.$[0] # for iterators
```

Currently, I'm leaning towards option 2, since I think I like the look of it better, but I'm open to suggestions.

**Comment by candeira** [comment]
I like Option 2 better too, having given it a thought. Thanks for your work!

**Comment by evhub** [comment]
@candeira Thanks! I'm planning on the next release being fairly substantial, and this will definitely be included in it.

**Comment by evhub** [comment]
@candeira This is now live in develop!
