### ISSUE TITLE
Add file watcher

### ISSUE THREAD

**Issue by vovanz** [evhub/coconut#99]
Add `--watch` option for the compiler.
When compiler is launched in watch mode, it should wait for changes in file or files in directory and immediately recompile changed files.

BTW, this lib may be useful.
http://pythonhosted.org/watchdog/ 

Many tools like LESS (which is compiled to CSS) or languages compiled to JS have this feature and it makes development process much more comfortable.

**Comment by evhub** [comment]
Very good idea. I'll definitely try to get that in the next version.

**Comment by Boscillator** [comment]
I'm working on this.

**Comment by evhub** [comment]
In develop.
